### ISSUE TITLE
Proper Documentation for AskSusi API

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_server#100]
Proper Documentation for AskSusi API is not present currently.
Documentation will help application developers to easily integrate Susi in their projects.

**Comment by Orbiter** [comment]
wrap up of documentation requirements:

- [ ] show an image (by a given image URL)

- [ ] show a pie chart

- [ ] show a web search result (ask the client to perform the search)

- [ ] show a web search result (deliver the search result, just show it on the client)

- [ ] show rss feeds (very similar to a delivered web search result)

- [ ] show a table

- [ ] play a sound / a video on the client

**Comment by Orbiter** [comment]
..and an architecture picture similar to https://docs.api.ai/docs/key-concepts

**Comment by Orbiter** [comment]
documentation started in file https://github.com/fossasia/susi_server/blob/development/docs/susi_chat_api.md
(unfinished yet)

**Comment by tabesin** [comment]
Important use cases are product references e.g. links to amazon products and social meta tags/opengraph/twitter card/FB link posts.

For a model use case think of a set of skills that constitutes a persona which recommends you books.

**Comment by chashmeetsingh** [comment]
@Orbiter support for GIF can also be added?

**Comment by Orbiter** [comment]
documentation is continued in https://github.com/fossasia/susi_skill_data/blob/master/README_susi_skill_language_tutorial.md
chapter 12
