### ISSUE TITLE
Make an API to allow ADMIN and higher user role to change config of devices of any user

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#1000]
**Actual Behaviour**

Currently, no such API is present.

**Expected Behaviour**

An API needs to be implemented.
This is as per outlined in this [spreadsheet](https://docs.google.com/spreadsheets/d/116QIngPEW2QI_p6YEwcj_vQ0dVMTzWZTB-wjWC4s_2s/edit#gid=1053849824).
Ref: https://github.com/fossasia/susi_server/issues/897

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
can i take up this issue? @Akshat-Jain
