### ISSUE TITLE
Image error when editing skill

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#1008]
When editing the skill https://skills.susi.ai/Movies%20and%20TV/Westworld/edit/en I get the error: 

> Error processing your request
> Image path must be in format of images/imageName.jpg

I did not change any image. Is this an error in the server or frontend?

**Comment by hkedia321** [comment]
This was a problem in client side and has been fixed by PR [1193](https://github.com/fossasia/susi_skill_cms/pull/1193), hence closing this.
