### ISSUE TITLE
Make API to return a public skill's image

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_server#1031]
**Actual Behaviour**

No API present to return the skill's image. Currently, the clients are fetching the images from github directly.

**Expected Behaviour**

Make an API which extracts the skill's image from `susi_skill_data` folder locally and send it.

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
Please send the image as actual image, not using base64 encoding.

**Comment by hkedia321** [comment]
@Orbiter Yes, I have made changes in the `/cms/getImage.png` API so that it can be used for three use cases, depending on the parameters provided by the client:
- getting image for public skills
- getting image for private skills
- gettings image from local storage

Please review [#1036](https://github.com/fossasia/susi_server/pull/1036) and let me know if any changes are needed. Thanks!
