### ISSUE TITLE
Image broken on SUSI Server home page

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#1032]
**Actual Behaviour**

The image in the bottom left is broken (screenshot attached)

**Expected Behaviour**

To fix it

**Steps to reproduce it**

Open 'api.susi.ai'

**Screenshots of the issue**

<img width="555" alt="screenshot 2018-07-21 at 4 37 16 am" src="https://user-images.githubusercontent.com/29942790/43028862-fdf356ec-8c9f-11e8-87b9-cf2e4becf941.png">

**Would you like to work on the issue?**

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by stealthanthrax** [comment]
Sure @starlord1311 . Go for it 👍

**Comment by starlord1311** [comment]
what am i supposed to do? @stealthanthrax

**Comment by starlord1311** [comment]
@stealthanthrax its showing the image on my laptop

**Comment by akshatnitd** [comment]
Not reproducable
