### ISSUE TITLE
Add a parameter to indicate if the skill is a `Staff Pick` in skill metadata

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#1033]
**Actual Behaviour**

Currently, no such parameter is present.

**Expected Behaviour**

There should be a boolean parameter which should indicate whether a Skill is a `Staff Pick` or not.
Ref: https://github.com/fossasia/susi_skill_cms/issues/1217

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
can i take up this issue? @Akshat-Jain
