### ISSUE TITLE
getSkillMetricsData.json API gives 500 error

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#1049]
**Actual Behaviour**
* getSkillMetricsData.json API gives 500 error

**Expected Behaviour**
* It should return the list of skills with the metrics

**Steps to reproduce it**
* Open `https://skills.susi.ai`

**Would you like to work on the issue?**
Yes, I and @AnupKumarPanwar will be working on it

**Comment by AnupKumarPanwar** [comment]
Yes but sorting isn't working.

**Comment by anshumanv** [comment]
Yes correct, your PR should fix this hopefully - https://github.com/fossasia/susi_server/pull/1041 :+1:
