### ISSUE TITLE
Proper Naming of Susi Skill Concepts

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#106]
We need a good organization concept for new and stored skills. By definition, a 'skill' is a single conversation rule, like

```
open shuttle bay door
ok I open the shuttle door
```

For some applications, only a set of skills operate as a single expert entity. One example is the 'Geschenke' Expert System: https://github.com/fossasia/susi_server/blob/development/conf/susi/de_0810_ai_problem_solving_geschenke.txt

We also need a concept how to add tags to single skills or skill groups.

Maybe we should consider that a skill set (which is an 'expert' or a 'topic') is part of a group of such groups, i.e. a project. A project may consist of several experts which are there to solve one big challenge. Such groups may be considered to have special (super?-) users who are allowed to organize the work within such groups.

We need a concept to have a language definition, default languages and fail-over functions for missing languages for a skill set or a project.

None of the words used to describe the concepts should be considered as fixed, this issue is here to discuss the wording. And to collect missing concepts.

Please discuss.

**Comment by Orbiter** [comment]
Here is my proposal for a hierarchy:

```
* all skills
|
-- * Projects
    |
    -- * Experts
         |
         -- * Languages (en is default language)
             |
             -- * Skills  
```

**Comment by Orbiter** [comment]
We need 'hidden skills' to safely store console skills containing application keys. Where should we put that?

**Comment by tabesin** [comment]
Distinguish between "persona" and "skill". A persona is a set of configuration items for instance packages of skills., configuration files, avatars etc.

**Comment by Orbiter** [comment]
We will put this schema as directory structure into a new github project: https://github.com/fossasia/susi_skill_data
That data will be usable for susi as susi dream.
The final skill repository concept will be, that the default configuration of susi is a set of default dreams, all from that repository.

If we have confidence that this schema is usable, we will build a wiki-like environment which can be used to write the schema for https://github.com/fossasia/susi_skill_data using an online editor. That online editor will grow in https://github.com/fossasia/susi_skill_wiki

**Comment by Orbiter** [comment]
done with https://github.com/fossasia/susi_skill_data/issues/1
