### ISSUE TITLE
Best Of All Possible Worlds: AI/Bot Evaluation and Cherry-Picking

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#107]
To be able to be competitive with other chatbots/AI systems, we should evaluate which other bots are there and pick the best parts out of them.
- Lets collect links and please
- add a note what is most noticeable about them.

**Comment by Orbiter** [comment]
https://botsociety.io/
- nice UI to quickly define new skills

**Comment by mariobehling** [comment]
* http://rasa.ai
* https://mycroft.ai/ | https://github.com/MycroftAI/
* https://github.com/Melissa-AI

**Comment by daminisatya** [comment]
https://api.ai/

**Comment by sanchittechnogeek** [comment]
* wit.ai 
* alicebot.org | works using AIML

**Comment by mariobehling** [comment]
* http://hackaday.com/2017/01/26/build-your-own-p-brain/
* https://github.com/patrickjquinn/P-Brain.ai/

**Comment by tabesin** [comment]
Thanks for adding, main difference in better clarity and leanness of code base. 

Practical use case https://www.data.gv.at/anwendungen/flux/

**Comment by tabesin** [comment]
https://mumbrella.com.au/foxtel-message-launch-wentworth-rat-chatbox-share-show-secrets-439533

**Comment by Abhi2424shek** [comment]
botkit.ai
