### ISSUE TITLE
Make an API to allow OPERATOR and higher user roles to change password of any user

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#1076]
**Actual Behaviour**

Currently, such an API does not exist.

**Expected Behaviour**

An API needs to be implemented.
This is as per outlined in this [spreadsheet](https://docs.google.com/spreadsheets/d/116QIngPEW2QI_p6YEwcj_vQ0dVMTzWZTB-wjWC4s_2s/edit#gid=1053849824).
Ref: https://github.com/fossasia/susi_server/issues/897

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
I am not sure if we should implement this. This will lead to security issues for the users. It needs to be discussed.
