### ISSUE TITLE
Login not possibly, Accounting buggy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#108]
Android users have difficulties signing up. Please compare here https://github.com/fossasia/susi_android/issues/578

1. Signup link brings me to a JSON file.
2. Does not fetch email from the phone.
3. I get an email that I signed up for loklak. I signed up for SUSI AI!
4. Password does not work - cannot login.
5. Reset password still not working.

**Comment by chiragw15** [comment]
For the reset password feature, we are sending an email with link to change password, something like http://api.asksusi.com/apps/resetpass/index.html?token=oMmEJcQjNKYsbGnBMpMMXvcsjAyWv9 . But in android app we have a screen which asks for token id and new password like this -
![screenshot_20170416-145441](https://cloud.githubusercontent.com/assets/16978820/25070179/061cb90e-22b5-11e7-9a80-5f814b1b62cf.png)

So, we have two options now:
1.) We can only send the token id via email and not the complete url and user can copy it and paste it in android app and change password.
2.) We can send link to change password (like we are doing now) and remove the screen in android app and display a dialog like "Link to change password has been sent to you email id. Follow the link to cange password and login again"

@mariobehling @Orbiter what do you think?

**Comment by mariobehling** [comment]
@chiragw15 The token idea was taken from other apps, but they only display a 4-6 character tokens. 

I guess to make this usable, we should just follow 2.) for now. Thanks for pointing out the options!

**Comment by chiragw15** [comment]
Cool :+1: I'll make the issue in the susi-android repo regarding removing of forgot password screen and adding dialog box instead.

**Comment by Abhi2424shek** [comment]
Isn't this fixed yet?

**Comment by dynamitechetan** [comment]
@Abhi2424shek I tried resetting password in SUSI app. Now there is a link in the email to reset the password and its working fine.

**Comment by chiragw15** [comment]
@dynamitechetan it has been fixed. Someone should close this issue now.

**Comment by dynamitechetan** [comment]
yes 👍
