### ISSUE TITLE
Add a boolean parameter in skill metadata to mark system skills

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#1086]
**Actual Behaviour**

Currently, no such parameter is present in the skill metadata.

**Expected Behaviour**

A boolean parameter `systemSkill` should be added which if `true` would indicate that the skill is a system skill.
This is as per outlined in this [spreadsheet](https://docs.google.com/spreadsheets/d/116QIngPEW2QI_p6YEwcj_vQ0dVMTzWZTB-wjWC4s_2s/edit#gid=1053849824).
Ref: https://github.com/fossasia/susi_server/issues/897

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
@Akshat-Jain can i take up this issue?

**Comment by Akshat-Jain** [comment]
@starlord1311 I'm already working on this one. You can look for unassigned issues and claim them and start working on them. Thanks :-)
