### ISSUE TITLE
SUSI default skills not being applied to dream skill

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_server#1099]
**Actual Behaviour**

When we enable dream mode in SUSI chat, the other default skills in SUSI is not being applied. i.e, only the queries defined in the dream skill is being answered. For other general queries like `hi` we are not getting a response from SUSI.

Same is the behaviour for private skills and Persona.

**Expected Behaviour**

The SUSI default skills should be applied when dreaming or using private skill or using persona. So for queries such as `hi`, we should get the default answer from the susi public skill.

**Steps to reproduce it**

Apply a dream skill and test with queries like `hi`. 

**Screenshots of the issue**

Chat conversation after applying dream skill:
![image](https://user-images.githubusercontent.com/17807257/43506431-a828729c-9587-11e8-9bdb-df767d1e8b0b.png)

Dream skill: https://dream.susi.ai/p/testingdream
![image](https://user-images.githubusercontent.com/17807257/43506447-b86afa6c-9587-11e8-8d03-d3b496950fd0.png)

Response from SUSI Server for the query `hi` after applying the dream skill as above:
![image](https://user-images.githubusercontent.com/17807257/43506788-cdbc41e0-9588-11e8-953e-2696b4489ac1.png)

**Would you like to work on the issue?**

Yes, I would like to work on it, but I am unable to figure out what changes needs to be done. In [SusiService.java#L191](https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/api/susi/SusiService.java#L191), we are already including the general skills of SUSI, but still it is not being reflected.
![image](https://user-images.githubusercontent.com/17807257/43506513-eb7c0c02-9587-11e8-9420-2596176b951c.png)

**Comment by starlord1311** [comment]
@hkedia321 can i take up this issue?

**Comment by Orbiter** [comment]
fixed with https://github.com/fossasia/susi_server/issues/1099
