### ISSUE TITLE
Endpoint for getting server logs

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#1108]
Actual Behaviour
Currently admin users are not able to access to the server logs.

Expected Behaviour
*Make an endpoint that has Admin as minimal Access Role and returns the logs of the server.
API reference for now - https://api.susi.ai/threaddump.txt

Would you like to work on the issue?
@PrP-11 , Would you do it?

**Comment by PrP-11** [comment]
@akshatnitd Thanks but @Orbiter said he will work on this on server and I will take care on the frontend.

**Comment by Orbiter** [comment]
it's already implemented: https://api.susi.ai/log.txt?count=10
gives the 10 latest lines from the log.
This is not a json api, it returns plain text

**Comment by Orbiter** [comment]
ahh, fixed this in https://github.com/fossasia/susi_server/commit/2aff0530341a022a5101a5010725fbfc127bdd4c
