### ISSUE TITLE
Registration form doesn't submit correct parameters to the API

### ISSUE THREAD

**Issue by felixonmars** [fossasia/susi_server#1110]
**Actual Behaviour**

The API call looks like the following when submitting the registration form:
```
https://api.susi.ai/aaa/signup.json?signup=user@emailserver.compassword=***
```

And got the following error: signup or password empty

**Expected Behaviour**

There should be a "&" before the `password=***` part.

**Steps to reproduce it**

Just finish the registration form on skill.s.a.

**Comment by akshatnitd** [comment]
Solve already
