### ISSUE TITLE
Setup Server on Cloud

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#1128]
**Actual Behaviour**
* The server is not yet hosted on cloud.

**Expected Behaviour**
* Set it up with Docker and host it on the cloud after going through the documentation.
* Make a script that checks for new version on github and deploys the new version similar to https://github.com/fossasia/open-event-server/tree/development/autodeploy 
* Make the load balancing session-sticky

**Would you like to work on the issue?**
Anyone can take this up. 
For permissions, ask @Orbiter and @mariobehling

**Comment by sakshee-19** [comment]
@akshatnitd It is already deployed on Heroku, Docker, Scalingo, IBM Cloud, and Azure. Is this issue completed or something needs to be done?

**Comment by norbusan** [comment]
Agreed, this issue should be closed.
