### ISSUE TITLE
Implementing enable/disable features for skills

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#1129]
- [ ]  Storing information that a skill is switched on/off in a metadata structure very similar to skill rating)
- [ ]  Enabling the user to switch on specific skills for them (two parts: storing this in the users thought log and using that information in the susi_mind computation of the answer) 

**Would you like to work on the issue?**
Anyone can claim it

**Comment by sk9331657** [comment]
@akshatnitd Can I work on this issue?? Please assign it to me.

**Comment by akshatnitd** [comment]
@sk9331657 I think we should first discuss with the implementation before proceeding for it. What approach are you thinking of?

**Comment by sk9331657** [comment]
@akshatnitd  I guess skills are stored in tables using special reference??

**Comment by Orbiter** [comment]
it's implemented with the `::on` Parameter; also called "runnable skill"

https://github.com/fossasia/susi_server/commit/077a486bbcf690d7dec7d016d5e0e7ef4df21013
https://github.com/fossasia/susi_server/commit/767471d8a2a9ba20d47dcec58ddd3ed43f83b87a

This is the basic infrastructure to enable skills which can be enabled, aka just "skills".

A skill becomes an activated skill if it has the "::on" metadata inside.

After the "::on" there should be a name which is calle to activate the skill.
the skill can i.e. be activated by the phrase "start <skill>"
