### ISSUE TITLE
Usage of += in strings inside loop

### ISSUE THREAD

**Issue by yashasvi128** [fossasia/susi_server#1157]
**Issue**
As every String concatenation copies the whole String, usually it is preferable to replace it with explicit calls to StringBuilder.append() or StringBuffer.append()
In DAO.java += has been used in loop.  StringBuilder.append() or StringBuffer.append() can be used there.

**Would you like to work on the issue?**
Yes.

**Comment by ByeongGil-Jung** [comment]
Okay, I've modified it in 'SkillTransactions.java'
