### ISSUE TITLE
Susi logo is not aligned at the middle of the screen in responsive mode .

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_server#1164]
**Actual Behaviour**

Susi logo is not aligned at the middle of the screen when screen width is reduced .

**Expected Behaviour**

Susi logo should be aligned in the middle of the screen when screen width is reduced just like in https://chat.susi.ai/overview 

**Screenshots of the issue**

![logo](https://user-images.githubusercontent.com/32234926/46257668-38862f00-c4db-11e8-8f10-f9c0e8ad592d.PNG)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Actually, you are planning to replicate a bug. The logo should be aligned to the left in the same line with the below menus. Therefore I am closing this issue.
