### ISSUE TITLE
Susi AI not able to understand the meaning of sentence with misspelled words.

### ISSUE THREAD

**Issue by MayV** [fossasia/susi_server#1165]
**Actual Behaviour**
Susi Ai is not able to understand the meaning of sentence with misspelled words. To get weather report, if "weather" is misspelled with "whether", then susi is not able to get the meaning.

**Expected Behaviour**
Susi AI should be able to recognize the meaning of the sentence and irrespective of small spelling errors and should be able to give correct results.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![2018-10-01 2](https://user-images.githubusercontent.com/34806097/46298065-cdf8f000-c5bb-11e8-9448-3cee2eaa7837.png)

**Would you like to work on the issue?**
Issue can be assigned to anyone else also.

**Comment by Ishaan28malik** [comment]
yes i want to work on this issue 
please aasign me this 
also brief me about it and what should or what can i do ?..

**Comment by MayV** [comment]
I am codeheat participant. How can I assign this issue. Any mentor of this project can only assign this issue.

**Comment by MayV** [comment]
@Ishaan28malik I don't have much knowledge about how to resolve it, but I guess you need to make some changes so that AI can related between words and its closely related misspellings.
