### ISSUE TITLE
Bug: Hindi greeting instead of English greeting "Hi"

### ISSUE THREAD

**Issue by Niharika248** [fossasia/susi_server#1166]
**Actual Behaviour**

Both as an anonymous user as well as logged in user, I am getting the answer "accha ji" which means hi in Hindi. I have set my language settings in SUSI.AI to English. I am accessing the web service from India 

**Expected Behaviour**

If the browser is set to English and the language settings in SUSI.AI are also set to English, then all the conversations must be English.

**Steps to reproduce it**

See above.

**Screenshots of the issue**

![screen 1](https://user-images.githubusercontent.com/41536726/46410349-6fbc3200-c6cd-11e8-98c1-ede6186f99b8.PNG)

**Comment by Akshat-Jain** [comment]
@Niharika248 I think you can close this issue as this will be solved by https://github.com/fossasia/susi_skill_data/pull/347. Thanks :-)

**Comment by Akshat-Jain** [comment]
@Niharika248 Closing this issue as this has been solved. Thanks for pointing it out :-)
