### ISSUE TITLE
Help reduce build time on RPi

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_server#1167]
In `susi_linux`'s install script (running in Raspberry Pi), `susi_server` is installed by `git clone`, then built with `gradle`. This takes quite some time. Here is my suggestion for `susi_server` project to help reduce built time on RPi:

1. (Easy) Package `susi_server` source in tarball, including all dependencies (git submodules), and host in Releases tab of GiHub. With this, `susi_linux` instal script can download the tarball instead of doing `git clone`, which takes long time because git database of this repo is big (~ 200MB).

2. (Difficult) Package and distribute as _*.deb_ package. With this, there is no need to download `gradle`, build `gradle` and wait for `gradle` to build `susi_server`. Save a lot of time. It also help avoid random failure of `gradle`, which leads to fail to install both *susi_server* and *susi_linux*.

**Comment by norbusan** [comment]
Two comments here: First, with the switch to qemu3 we are not restricted to building on raspi, but can use qemu, which improves speed a lot.

But, if there is need, I can come up with a packaging for Debian (enough experience in this area, thought not with packaging java apps).

**Comment by hongquan** [comment]
Hi @norbusan 

I'm closing this issue, because @Orbiter already release pre-built tarball of susi_server here: http://download.susi.ai/susi_server/

(Forgot to update this issue).

But, in the future, I will re-organize codebase of susi_linux, in which, I may make it distributed in _*.deb_ file, and hence, will need susi_server to be packaged as _*.deb_ also.

**Comment by norbusan** [comment]
@hongquan If you want me to work on the Debian packaging, let me know. If there are some constraints about the layout, let me know, otherwise I do what I think is good for Debian packaging.
