### ISSUE TITLE
Intents don´t work in JSON

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#1168]
From @ftyers 

**Actual Behaviour**

Reflections in JSON don´t work.

**Expected Behaviour**

Reflections should work even in JSON...

**Steps to reproduce it**

```
què és la hora a *
!console:`translate2 $plaintext$`
{
  "url": "https://api.wolframalpha.com/v2/query?input=time%20in%20`translate1 $1$`&output=JSON&appid=9WA6XR-26EWTGEVTE&includepodid=Result",
  "path" : "$.queryresult.pods[0].subpods[0]"
}
eol

translate1 moscú
moscow

translate2 *
$1$
```

**LogCat for the issue**

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/238730/46920955-47c0ae80-cfaa-11e8-9762-354f5420d862.png)

**Would you like to work on the issue?**

**Comment by diru1100** [comment]
@Orbiter I am trying to solve this issue and wasn't able to recreate the issue from the comment above. Could you please help me understand .
