### ISSUE TITLE
Refactor the server code

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_server#1195]
**Actual Behaviour**

There should be minimum code duplicates and semantic errors.

**Expected Behaviour**

There are a lot of code duplicates and semantic errors present.

**Steps to reproduce it**

Open the project in any IDE and inspect the code.

**Would you like to work on the issue?**

Yes, I am working on it and refactoring the code component by component.

**Comment by norbusan** [comment]
Are all the issues you have seen resolved? If yes, this issue should be closed.

**Comment by ms10398** [comment]
They are not and other people are welcome to work on it if anyone wants to

**Comment by norbusan** [comment]
Indeed, looking at the code in IntelliJ and searching for duplicates is a waterfall of un-refactored code ...
