### ISSUE TITLE
Susi don't compute out some general questions

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/susi_server#1211]
**Actual Behaviour**

Doesn't know about word "**biggest waterfall**" or "**biggest waterfall in the world**" 

**Expected Behaviour**
Susi can show results through web , searched by the user.

**Screenshots of the issue**
![screenshot 30](https://user-images.githubusercontent.com/33255535/50471588-6516ed80-09db-11e9-8afa-b76d933aa149.png)

**Would you like to work on the issue?**
Someone can be assigned to this.

**Comment by dernDren161** [comment]
@Aakash-DD I would like to work on this issue. What would be the best way/method to fix this problem? wanting some guidance!! Thank You!
