### ISSUE TITLE
Server Broken?

### ISSUE THREAD

**Issue by BopItFreak** [fossasia/susi_server#1212]
When i got to https://api.susi.ai/susi/chat.json?q=hi

I get 
HTTP ERROR 500
Problem accessing /susi/chat.json. Reason:

    Server Error
Caused by:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by fragm3** [comment]
I am getting the same error @Orbiter @ms10398

**Comment by fragm3** [comment]
@fossasia/susi-ai-server-admin @fossasia/susi-ai-core-team

**Comment by Orbiter** [comment]
its fixed for now but there is something strange going on
