### ISSUE TITLE
Susi not able to answer properly on questions containing apostrophe

### ISSUE THREAD

**Issue by tusharfc** [fossasia/susi_server#1242]
**Actual Behaviour**

Susi answers are completely different than what it should answer due to a simple missing of apostrophe mark.Also it is replying some random symbols when it is being asked a specific question.

**Expected Behaviour**

It should have answered correctly when asked about name without apostrophe marks and also it should not reply some random symbols.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![screenshot from 2019-03-03 10-00-35](https://user-images.githubusercontent.com/39709378/53688773-02412a00-3d6f-11e9-9f97-8dedd880916d.png)

**Comment by AnupKumarPanwar** [comment]
![image](https://user-images.githubusercontent.com/10573038/55774449-c4909900-5ab2-11e9-8039-dfd9f6cc1966.png)

The behaviour is quite ambiguous.
