### ISSUE TITLE
Allow user to add name and profile picture.

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_server#1247]
**Actual Behaviour**
Currently during, registration susi does not ask for name of the user. Not even user is allowed to upload profile photo.

**Expected Behaviour**
Susi should ask for name of the user. It is a very essential feature for an assistant to communicate with the user. fossasia/susi_android#2101 fossasia/susi_android#2104
Currently, the app is not too user friendly to communicate with the user. Implemeting this will allow us to establish more user friendly features in the android client.

**Would you like to work on the issue?**
Yes. But I need time.

**Comment by baquer** [comment]
@atm1504, this feature is already present in Susi_Server, Please check Susi_Serevr APIs. User can set his/her user name and upload a profile picture using the APIs provided by susi_server

**Comment by atm1504** [comment]
@baquer thank you for your information. I would surely go through them, and if found sufficient to  use it in the app, then I will surely close the issue. : )
