### ISSUE TITLE
Implement notification feature.

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_server#1248]
**Actual Behaviour**
Currently, no method has been established which allows to send notification in the app.

**Expected Behaviour**
There should be a method to send notification in the app. This will allow to send important information to the user. Like we can inform the user about new skills of susi, greet the user during some special festivals. 

**Would you like to work on the issue?**
Need help to implement it.

**Comment by atm1504** [comment]
@iamareebjamal please provide your views regarding the addition of this feature. I think it is necessary. Because all most all of the apps(including assistant apps) have push notification feature.

**Comment by iamareebjamal** [comment]
No use unless server supports it. Open the issue on server

**Comment by mariobehling** [comment]
out of scope currently
