### ISSUE TITLE
Compress uploaded images before storing 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_server#1256]
**Actual Behaviour**
Currently the user can upload image of any size.

**Expected Behaviour**
Compress the image before storing it.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Please store the original image and generate a thumbnail version e.g. for thumbnail areas.

**Comment by mariobehling** [comment]
Please align with this issue as well and check how far things have been implemented: https://github.com/fossasia/susi_server/issues/537

**Comment by harsh-jindal** [comment]
@mariobehling This is already present when we create skill or bot. 
The function `createResizedCopy` resizes the image to 512 x 512
I'll implement this for upload avatar image
