### ISSUE TITLE
Create a skill with an API from an online service using the tutorial

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#126]
Create a skill with an API from an online service using the tutorial at https://github.com/fossasia/susi_server/blob/development/docs/skills/susi_skill_development_tutorial.md

The skill should make use of an API of an online service.

Add the skill first to http://dream.susi.ai and share it as a comment.

There is also information from this workshop available here https://www.youtube.com/watch?v=7U__K8yy1iY&t=996s

**Comment by DravitLochan** [comment]
shall I start by adding a skill which helps the user to query the value of one currency into another?
@mariobehling

**Comment by AliAyub007** [comment]
@mariobehling I am creating a skill so that we can check weather details for any specified city. Currently I implemented this for temperature and humidity values thought temperature is in kelvin right now but I am working on to make it to celcius.
here is the dream http://dream.susi.ai/p/check

**Comment by AliAyub007** [comment]
**BBC NEWS Api** 
http://dream.susi.ai/p/news 
This will return recent articles and news as a description.

**Weather Enhancement**
http://dream.susi.ai/p/weather
This will tell humidity percentage and will tell about next day's forecast. 

It has more things which can be implemented but as we can only receive one answer in console and that is issue #132

**Comment by chashmeetsingh** [comment]
#### Random Gif API (Giphy.com)
http://dream.susi.ai/p/random_giphy
Returns a random GIF

**Comment by uday96** [comment]
**Language translator**
http://dream.susi.ai/p/languageskills
Currently converts to french and german from english and also gives the meaning of a word in english. (working on a way to extend translation from any language to another).

**Cooking recipies**
http://dream.susi.ai/p/cooking
Gives the recipie to cook a particular dish.

**Comment by dynamitechetan** [comment]
**Throw a dice** 
http://dream.susi.ai/p/dice
Returns a random number from 1 to 6

**Comment by DravitLochan** [comment]
@dynamitechetan http://deckofcardsapi.com/ have a look at this API. This might enhance the skill you are working on :)

**Comment by madhavrathi** [comment]
Daily horoscopes and flip a coin
http://dream.susi.ai/p/madhavrathi

**Comment by madhavrathi** [comment]
has anyone figured out how to access root elements of json(what to pass within path) ?

**Comment by rishiraj824** [comment]
Tells you about the pokemon
http://dream.susi.ai/p/pokemon

Here's a consolidated list of APIs which one can use to create skills.
https://github.com/toddmotto/public-apis

**Comment by dynamitechetan** [comment]
**Shows gif for a given query**
http://dream.susi.ai/p/gif

**Comment by Fluepke** [comment]
**Retrieves the hottest image from imgur**
http://dream.susi.ai/p/imgur

**Comment by AliAyub007** [comment]
**Tells us about population of any country** 
http://dream.susi.ai/p/population

**Comment by madhavrathi** [comment]
Displays motivational quotes daily
http://dream.susi.ai/p/quote

**Comment by Fluepke** [comment]
**Display the current position of the international space station**
http://dream.susi.ai/p/iss

**Comment by DravitLochan** [comment]
**sports details from espn api**
http://dream.susi.ai/p/espn

**Comment by Fluepke** [comment]
**Sunrise**
http://dream.susi.ai/p/sunrise

Unfortunately, we cannot nest APIs. This would be useful, to first query a name to GPS converter and then query the sunrise API.

**Comment by sch00lb0y** [comment]
**University**
http://dream.susi.ai/p/university

**Comment by saurabhjn76** [comment]
### Day in History
Events, Births, Deaths on a particular date
http://dream.susi.ai/p/history

**Comment by jyoth1raditya** [comment]
Price of stock: http://dream.susi.ai/p/stockdata
Distance : http://dream.susi.ai/p/distance_between_cities
Time : http://dream.susi.ai/p/time_to_travel_between_cities
Your IP : http://dream.susi.ai/p/ip ( Not working due to, parsing of root )

**Comment by madhavrathi** [comment]
Tells Director of a particular movie(Finally solved accessing root elements, thanks to @Orbiter )
http://dream.susi.ai/p/director

**Comment by chiragw15** [comment]
@jyoth1raditya The IP skill will not work because the user doesn't directly call the API and thus the response will always be server IP. I tested the IP skill on different devices and found same IP address i.e 144.76.32.15 .

**Comment by DravitLochan** [comment]
http://dream.susi.ai/p/movie_n_shows

plot, imdb rating and genre. (quick extension of @madhavrathi 's skill)

**Comment by chiragw15** [comment]
1. Using semantic analysis to determine whether entered text is positive or negative.
http://dream.susi.ai/p/sentiment

2.  Determine gender of a person from his first name
http://dream.susi.ai/p/gender

3. Using github api to find information about person from his github username
http://dream.susi.ai/p/github

4. Calculating differentiation and integration of an expression
http://dream.susi.ai/p/advanced_math

**Comment by Manveer695** [comment]
To know the full form and country code of a space agency.
http://dream.asksusi.com/p/space

**Comment by AliAyub007** [comment]
**Tell acronyms**
http://dream.susi.ai/p/acronyms

**Tells about height of different buildings or places**
http://dream.susi.ai/p/height

**Tells Calling codes of countries**
http://dream.susi.ai/p/callingcode

**Tells about region of country whether it's Asia, africa or any other**
http://dream.susi.ai/p/region

**Tells us about area of country**
http://dream.susi.ai/p/area

**Tells us about Time Zone** 
http://dream.susi.ai/p/timezone

**Tells us about currency of countries**
http://dream.susi.ai/p/countrycurrency

**Generates random number**
http://dream.susi.ai/p/randomnumber

**Comment by DravitLochan** [comment]
working on meme generator and qr code generator. once finished, will attach the dream etherpad link as well!

**Comment by saurabhjn76** [comment]
**Draw a card**
http://dream.susi.ai/p/deckofcards

**Comment by dynamitechetan** [comment]
**Detects language of a sentence passed**
http://dream.susi.ai/p/detectlang

**Comment by DravitLochan** [comment]
@sch00lb0y [this](http://dream.susi.ai/p/university) works only for the first name of the university. for instance, if you are looking for Birla Institute of Technology and Science (i.e. bits) you must pass only 'birla' to get a valid response.

**Comment by Manveer695** [comment]
To answer questions like "Who is amitabh bachchan" or "who is taylor swift", using the Api of susi itself.
http://dream.asksusi.com/p/whotowhat

**Comment by amitiwary999** [comment]
#Find capital of any country
 http://dream.susi.ai/p/countrycapital

**Comment by dynamitechetan** [comment]
**Wikipedia summary**
http://dream.susi.ai/p/wiki

**Comment by amitiwary999** [comment]
**Some random chat**
 http://dream.susi.ai/p/simplechating

**Comment by saurabhjn76** [comment]
**Calendar**
http://dream.susi.ai/p/calendar

**Comment by isuruAb** [comment]
**check the book name** - build by google book api
http://dream.susi.ai/p/booknames

**Comment by AliAyub007** [comment]
**Social Shares** 
**Tells about social shares of specific platforms e.g social shares of 9gag**
http://dream.asksusi.com/p/social

**Comment by saurabhjn76** [comment]
**Question and answer**
http://dream.susi.ai/p/qna

**Comment by Orbiter** [comment]
ATTENTION! Thank you very much for creating so many dreams. Now we have a place to put the dreams permanently into a storage place and move it to production automatically.

in https://github.com/fossasia/susi_skill_data is the new storage place. Please read the readme carefully, find a place in the data structure and put your data there using a pull request. Use a peer reviewer to discuss the right storage location and to verify that your skill does work.
