### ISSUE TITLE
The project fails to build

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_server#1272]
**Actual Behaviour**
The Gradle wrapper is outdated and the project fails to build

**Expected Behaviour**
The project should build on execution `./gradlew build`

**Steps to reproduce it**
``` 
git clone https://github.com/fossasia/susi_server.git
cd susi_server
git submodule update --recursive --remote
git submodule update --init --recursive
./gradlew build
```
**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/14289201/59413797-e6bdd480-8ddd-11e9-9a53-c2a5b1596686.png)

**Would you like to work on the issue?**
Yes

**Comment by norbusan** [comment]
I guess you are running Java11. THere the tests fail. Please use Java8 for now.
