### ISSUE TITLE
bin/start.sh doesn't start the server after successful build

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_server#1278]
**Actual Behaviour**
![image](https://user-images.githubusercontent.com/14289201/59894611-e4bbcd00-93fe-11e9-8f3e-3348c02bd80a.png)

- The JARFILE name in `bin/preload.sh` doesn't match the generated one by the updated gradle wrapper

**Steps to reproduce it**
- build the project
- run `bin/start.sh`

**Would you like to work on the issue?**
yes

**Comment by Orbiter** [comment]
fixed with https://github.com/fossasia/susi_server/commit/21dac499963a1b709eff684512afbb95b9ac065c
