### ISSUE TITLE
Add a way to return SoundCloud URL like youtube URL

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#1280]
**Actual Behaviour**

Currently, the server only returns youtube id. 

**Expected Behaviour**
Add some way to return SoundCloud urls as well.

**Would you like to work on the issue?**
Url should be of the format: https://soundcloud.com/aries_ix/sayonara

**Comment by Orbiter** [comment]
implemented with
https://github.com/fossasia/susi_server/commit/d83bc88e74263ffd7b7ee23743edc66c002a698d
https://github.com/fossasia/susi_server/commit/8c86c5b802915c52b08039c360c6b74a5431aa93
