### ISSUE TITLE
Fix Loading of List User in Admin

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_server#1287]
**Actual Behaviour**
Currently the users loaded in admin panel.

**Expected Behaviour**
Fix it.

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
@Orbiter The issue is in getUsers.json, when we try to get all the user list, using parameter: `page`

Exact endpoint giving the error: `https://api.susi.ai/aaa/getUsers.json?access_token=7KkMUJmd2suogLKumJAo99qI3MpTzy&page=1`

**Comment by fragm3** [comment]
<img width="1680" alt="Screenshot 2019-07-14 at 12 24 08 PM" src="https://user-images.githubusercontent.com/18073126/61180326-4eac4880-a632-11e9-99f4-4d39f85eebb6.png">
