### ISSUE TITLE
Enhance Search Functionality in Skills SUSI

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#1291]
**Actual Behaviour**

Not present

**Expected Behaviour**

In response to PR https://github.com/fossasia/susi.ai/issues/2473, new search services and servlet needs to be created.

Options:

- [x] Names(already done)
- [x] Author/Developer
- [x] Examples
- [x] Description

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Currently working on Search By Author/Developer

**Comment by mariobehling** [comment]
Additionally I just identified more filters for:
* Reviewed Skills
* Staff Picks
* System Skills
* Non-system Skills

**Comment by fragm3** [comment]
@mariobehling I will create next PR for this, let's get https://github.com/fossasia/susi_server/pull/1292 merged. Thank you!

**Comment by fragm3** [comment]
Reviewed Skills, Staff Picks are already present as a filter on the left side of browse skill. Search using System Skills, and Non-system skills would be really helpful for users
