### ISSUE TITLE
Correct eclipseSetup.md

### ISSUE THREAD

**Issue by charany1** [fossasia/susi_server#13]
File link : https://github.com/fossasia/susi_server/blob/development/docs/eclipseSetup.md

Line 9 : Once the repository is ready using the Package Explorer navigate to org.loklak.LoklakServer . 

I couldn't find any file LoklakServer.java , probably it should be org.loklak.SusiServer .

**Comment by jig08** [comment]
@charany1 Thanks for pointing it out.
