### ISSUE TITLE
Enabling multiple console results as an answer

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#132]
**Current Behavior**

Right now console results as an answer is designed in that way to return only the first line.
!console:$name$

**Expected Behavior** 

It should return multiple results as answer.
!console:$name$, $place$, $Price$

related to issue #100

**Comment by chashmeetsingh** [comment]
Can we also store the key-value pair in variables and instead of having a path for a single item use those variables to get multiple results in console. Makes sense?
