### ISSUE TITLE
Make an endpoint to listUserDevices

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#1325]
**Actual Behaviour**
- Make an endpoint to listUserDevices. Currently, it comes with listUserSettings API

**Expected Behaviour**
- Make an endpoint to listUserDevices

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
Please inform me when this endpoint is created. I need to update it accordingly in the android client.

**Comment by akshatnitd** [comment]
@atm1504 The PR for it ready to be merged. Make a PR for it on the android repo, so that can be merged after it. Earlier the devices used to come in listUserSettings API, it won't come in the response of that API. Instead it would come in listUserDevices API. The structure of the response would be same as the listUserSettings API.
