### ISSUE TITLE
Parse root key value pairs from any json

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#133]
I wasn't able to extract root key values from the Susi chat API.

Here is my code

```
tweet about *
!console:$readme_3$
{
"url":"http://api.loklak.org/api/search.json?q=$1$",
"path": "$."
}
eol
```

I wanted to extract the value of any readme_*.

#### Expected Behaviour
Should parse and return the string value.

#### Actual behaviour
I get the webResult result.

**Comment by saurabhjn76** [comment]
As suggested by @Orbiter, the following would work.
```
tweet about *
!console:$object$
{
"url":"http://api.loklak.org/api/search.json?q=$1$",
"path": "$.readme_3"
}
eol
```

**Comment by chashmeetsingh** [comment]
@saurabhjn76 does that work for you?

**Comment by chashmeetsingh** [comment]
solved!
