### ISSUE TITLE
Handling private keys when using an API

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#134]
**Actual Behaviour**

Currently, there is no way to deal with private API keys for creating skills.

**Expected Behaviour**
There should be a way to deal with private keys.

**Comment by Fluepke** [comment]
This is very important question, as many open source projects face this problem! Let's find a solution for this issue.

So, here are my thoughts on this

1.  Convince everybody to offer open APIs to support FOSS 😀 (Ok, I know. That's seems rather unlikely)
2. A *key server* at which the developers register using their Facebook, Twitter, Google, whatever account. Via these accounts the server could automatically fetch API keys, which could be supplied to the local development setup via a command line tool and one single API key.
3. The *default way* (most projects, I have seen do it this way): Use a local config file for API keys that will be `git ignored`. This has the disadvantage that every developer needs to acquire API keys for all the services. Some API keys for German public transportation services even require you to ask in German for an API key.
4. Combing `2` and `3`: A command line tool that can automate the process of acquiring API keys (running only locally)

What do you think?

**Comment by Orbiter** [comment]
The private API keys in skills will be handled as a kind of 'hidden' skills in the upcoming susi skill wiki.

That wiki will enable that a user creates and edit a skill, but keeps it hidden from other users while it may be possible to share the skill function with everyone.

**Comment by Orbiter** [comment]
please open an issue at https://github.com/fossasia/susi_skill_wiki with that concept idea

**Comment by Fluepke** [comment]
The wiki idea sounds great. I'll push my thoughts there.

**Comment by Orbiter** [comment]
closed in favor of https://github.com/fossasia/susi_skill_wiki/issues/2

**Comment by Fluepke** [comment]
How about user specific APIs as discussed [here](https://github.com/fossasia/susi_server/issues/184)?
We need a way of storing user specific credentials to different services (e.g. Uber, IMAP, Deliveroo) to act as a client to these services, to offer more skills for interacting with the real world.

Sample use cases would be
* `Order me a Uber`: The user's credentials are used to order a Uber to his location
* `Order me a pizza`: Same as above concerning deliveroo
* `When does my train/flight depart?`: Emails are scanned for tickets

**IMO** this is a very crucial part to compete with other AI providers like `Google Now` as they are providing you these kind of information (When does my flight depart? etc.). This way the Susi AI could be integrated much more into the users' life.
