### ISSUE TITLE
Build instruction not correct?

### ISSUE THREAD

**Issue by julianfox** [fossasia/susi_server#135]
The build instruction seem not correct:
> git clone https://github.com/fossasia/susi_server.git
> cd susi_server
> ant
> bin/start.sh

On macOS Sierra system I get this error:
> Buildfile: build.xml does not exist!
> Build failed

All work perfectly fine with:
> ./gradlew build

Should we update the doc ?
I don't have any knowledge about JAVA so I prefer to ask before to submit a PR ;-)

**Comment by Orbiter** [comment]
Susi can be started with gradle run, but we may keep the start script as a convenience method and for people who do not know about gradle.

I guess it should be possible to run susi without gradle after a gradle assemble has been done. Can you do that rewrite?

**Comment by julianfox** [comment]
Yes I can run susi with bin/start.sh without any issue after the gradle assemble.

But is it normal to obtain this error with the "ant" command?:
> Buildfile: build.xml does not exist!
> Build failed

**Comment by duttaditya18** [comment]
Had the same issue. However, it works with gradle.
