### ISSUE TITLE
Add functionality to disable/enable catpcha

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#1373]
**Actual Behaviour**

Not present

**Expected Behaviour**

Required for PR: https://github.com/fossasia/susi.ai/issues/2796

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
If you refer to the web client issue, the goal there is actually to enable/disable captcha per message not to do in on a global level. So, this PR does not relate to the frontend entirely and does not solve the related issue there. Therefore I am reopening this here.

Please provide a way to enable/disable Captcha for specific message types.
