### ISSUE TITLE
Fix error due to multi search in skills

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#1375]
**Actual Behaviour**

If we apply search query, search filter in top bar in https://susi.ai/, we always get the same result. Endpoint: https://api.susi.ai/cms/getSkillMetricsData.json?access_token=xlSCD7NIHE7zxarj5G0ZU98VqCUrdP&language=en

**Expected Behaviour**

Please fix it. It might be a bug due to PR when I was creating multi-search functionality where a user can search based on skill example, description. Everything for working fine till this PR, but this PR was not implementing multi-search: https://github.com/fossasia/susi_server/pull/1292

So, I made a PR to implement multi-search, PR: https://github.com/fossasia/susi_server/pull/1307, with this we get all the skills always. This PR breaks the search functionality 

**Would you like to work on the issue?**

@Orbiter please help and fix this

**Comment by Orbiter** [comment]
@fragm3 Please submit more example queries for this endpoint where filters are used

**Comment by fragm3** [comment]
@Orbiter try any query, for example: https://api.susi.ai/cms/getSkillList.json?access_token=xlSCD7NIHE7zxarj5G0ZU98VqCUrdP&group=All&language=en&applyFilter=true&filter_name=descending&filter_type=rating&reviewed=true&staff_picks=false&q=testtt&search_type=skill_name,%20descriptions,%20examples,%20author. It's always giving the same result
