### ISSUE TITLE
Fix date in device over time

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_server#1388]
**Actual Behaviour**
Fix incorrect date format.

**Expected Behaviour**
Fix it.

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
please make an example to be able to reproduce the problem!

**Comment by harsh-jindal** [comment]
@Orbiter This issue was fixed by you in https://github.com/fossasia/susi_server/commit/f45a7aa935ac9b2bebd0e4c88be35141956d5bc0. Thanks
