### ISSUE TITLE
Chatting with bot

### ISSUE THREAD

**Issue by darkthunder007** [fossasia/susi_server#1401]
[**Actual]([url](url
<img width="864" alt="df" src="https://user-images.githubusercontent.com/53977169/65375919-e1630680-dcb7-11e9-92df-994d95414362.png">
)) Behaviour**

The bot gives out random output

**Expected Behaviour**

Output a better statement

**Steps to reproduce it**

Give inputs like Why, What

**Screenshots of the issue**

**Would you like to work on the issue?**

Get a chance to work on the code

**Comment by asha15** [comment]
@darkthunder007  I would like to work on this issue.Can i know from where the outputs are generated?

**Comment by darkthunder007** [comment]
@asha 15
I wanted to work on this issue. The susi chat bot gave those responses when I asked what.

**Comment by asha15** [comment]
@darkthunder007  OKay. All the best ;)

**Comment by darkthunder007** [comment]
to solve the issue, i added a skill to susi bot that when the user asks one word questions like what?,how?... the user has to give a clearer question for susi to respond to.
<img width="861" alt="dumdum" src="https://user-images.githubusercontent.com/53977169/65813960-735b9980-e1f9-11e9-8e2a-8c222f8c46c0.png">

**Comment by asha15** [comment]
@darkthunder007  Nice job. Can i know in which file the outputs are generated?

**Comment by darkthunder007** [comment]
If you use the skill 'Ask question' it works
