### ISSUE TITLE
BahnService not working and causing build failure.

### ISSUE THREAD

**Issue by Thebest1209** [fossasia/susi_server#1424]
**Actual Behaviour**

The build is failing as the BahnService is not working in the public-transport-enabler

**Expected Behaviour**

BahnService is not really required for the susi_server and build should be successful.

Steps to reproduce it

Remove BahnService

**LogCat for the issue**

/home/raviarora/GCI/susi_server/src/api/external/transit/BahnService.java:22: error: cannot find symbol
private BahnProvider provider = new BahnProvider();
^
symbol: class BahnProvider
location: class BahnService
/home/raviarora/GCI/susi_server/src/api/external/transit/JSONConverter.java:41: error: cannot find symbol
fareObj.put("network", fare.network);
^
symbol: variable network
location: variable fare of type Fare
/home/raviarora/GCI/susi_server/src/api/external/transit/JSONConverter.java:84: error: cannot find symbol
coordinateObj.put("lat", location.lat);
^
symbol: variable lat
location: variable location of type Location
/home/raviarora/GCI/susi_server/src/api/external/transit/JSONConverter.java:85: error: cannot find symbol
coordinateObj.put("lon", location.lon);
^
symbol: variable lon
location: variable location of type Location
/home/raviarora/GCI/susi_server/src/api/external/transit/BahnService.java:22: error: cannot find symbol
private BahnProvider provider = new BahnProvider();
^
symbol: class BahnProvider
location: class BahnService
/home/raviarora/GCI/susi_server/src/de/schildbach/pte/util/HttpClient.java:121: error: cannot find symbol
final MediaType contentType = MediaType.get(originalContentType.type() + '/'
^
symbol: method get(String)
location: class MediaType
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

**Screenshots of the issue**

![Screenshot from 2019-12-22 00-28-38](https://user-images.githubusercontent.com/46346108/71312535-2717a280-2452-11ea-9e1a-7e6d3f96f87a.png)

**Would you like to work on the issue?**

Yes!

**Comment by Orbiter** [comment]
removed the BahnService Submodule
