### ISSUE TITLE
Case Sensitivity for parameters

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#143]
when we are creating skills, the input parameters being used as $1$ ,$2$ are being converted to lower case. This is an issue for few endpoints like fixer.io where 
http://api.fixer.io/latest?base=USD&symbols=EUR  works but
http://api.fixer.io/latest?base=usd&symbols=eur   does not

**Expected behaviour :**
Maintain case sensitivity for parameters

**Comment by amitsin6h** [comment]
want to work on this bug

**Comment by DravitLochan** [comment]
@Orbiter  Does this needs to be implemented?
