### ISSUE TITLE
No api to handle  mathematical expression

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi_server#1440]
**Actual Behaviour**

No api to handle  mathematical expression

**Steps to reproduce it**

substitute 10+1 as input

**Would you like to work on the issue?**

no

**Comment by Nikunjbansal99** [comment]
@anishagg17 I think this is not the issue just add "compute" before mathematical expression. It gives you the desired output. For reference take a look at Snap attached below.

![Capture](https://user-images.githubusercontent.com/46066280/73616100-210e0780-4635-11ea-9e81-b052c203d910.PNG)

 I suggest close this Issue.
