### ISSUE TITLE
SignUp Problem in Android App

### ISSUE THREAD

**Issue by Nikunjbansal99** [fossasia/susi_server#1446]
**Actual Behaviour**

On Registering the new Email-Id. It shows Email address already exist. Hence, not registering the new Email-Id.

**Expected Behaviour**

Register a new user.

**Steps to reproduce it**

<i> Open SUSI.AI App.
<ii> Click on Sign Up for SUSI.
<iii> Enter new Email-Id.

**Screenshots of the issue**
![Screenshot_2020-02-03-02-30-32-90](https://user-images.githubusercontent.com/46066280/73615508-7d215d80-462e-11ea-921f-3ed2b66757cb.png)
![Screenshot_2020-02-03-02-31-07-41](https://user-images.githubusercontent.com/46066280/73615509-7f83b780-462e-11ea-9c5c-21ca4525d6fb.png)

**Would you like to work on the issue?**
No

**Comment by haran2248** [comment]
yes i would like to work on this can you please guide me?

**Comment by mariobehling** [comment]
Please open this in Android repo.
