### ISSUE TITLE
Some Links Broken 

### ISSUE THREAD

**Issue by viditvarshney** [fossasia/susi_server#1452]
**Actual Behaviour**

> The links are broken in the footer-wrapper class
> The **overview** and **blog** are broken 
> 

**Expected Behaviour**

> These should redirect to the specific page.

**Steps to reproduce it**

> only the correct URL will work

**Screenshots of the issue**

![susi](https://user-images.githubusercontent.com/34159717/74108795-b6fce180-4ba3-11ea-8da5-30045db68a99.PNG)

**Would you like to work on the issue?**

> I would like to work on this issue

**Comment by siddhant-roy** [comment]
I would like to work on this issue

**Comment by Trimankaur** [comment]
Figured out that the link to Contact , Terms and Privacy are also broken. 
I would like to fix this issue. Can you help me get started as I am a beginner ?

**Comment by viditvarshney** [comment]
@mariobehling  Yeah After So much time This issue comes in light. I would like to work on it.

**Comment by viditvarshney** [comment]
@mariobehling can i work on this issue.

**Comment by prsk4u** [comment]
I would like to work on this issue

**Comment by bisham65** [comment]
i would like to work on this  issue

**Comment by viditvarshney** [comment]
Hey, @mariobehling Seems like there are some Important links that are broken as I mentioned above in screenshots.
Some are Overview, Blog, Contact, terms, Privacy.

**Comment by viditvarshney** [comment]
since the project is inactive for a long time. I'm closing this issue.
