### ISSUE TITLE
Pass author avatar along with the skills

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi_server#1462]
**Actual Behaviour**

Currently, author avatar is not passed along with the author skills.

**Expected Behaviour**

Author avatar need to be passed along with it.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Why?

**Comment by Dilshaad21** [comment]
@akshatnitd currently github user avatar is used in that place for author skills page
