### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [fossasia/susi_server#1464]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**Comment by iamareebjamal** [comment]
Done

**Comment by prodigysml** [comment]
Just adding on here. I found a security problem. Would it be possible to get a contact for security?

**Comment by iamareebjamal** [comment]
I have added you to a new security advisory
