### ISSUE TITLE
Test cases for JSONPATH

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#147]
Please write down all example json objects which you want to access with a jsonpath.

**Comment by madhavrathi** [comment]
https://api.littleastro.com/public/xiaoerge_dev_horoscope.php
@Orbiter In this, how can we display horoscope of a particular zodiac sign, entered by user.

**Comment by DravitLochan** [comment]
http://dream.susi.ai/p/horoscope
I found an API which does this in a pretty easy fashion. Please close this issue :)
