### ISSUE TITLE
Adding headers to an API request

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#156]
Is there any way we can add headers to an API request? This will enable us to consume more number of APIs.

**Comment by DravitLochan** [comment]
@mariobehling @Orbiter any info on adding headers and sending a POST request?

**Comment by DravitLochan** [comment]
@mariobehling @Orbiter I'd like to work on this issue. we can add an attribute "request_action" which will define the nature of request (GET/POST) while calling an external API. If it is POST then ask for attribute names and their values.
