### ISSUE TITLE
FileNotFoundError in docs/include.py on travis

### ISSUE THREAD

**Issue by pri22296** [fossasia/susi_server#161]
**Steps to reproduce it**

This error seems to only occurs on travis. It doesn't happen locally.

**LogCat for the issue**

    Traceback (most recent call last):
        File "include.py", line 68, in <module>
            main()
    File "include.py", line 63, in main
        include_file(filename)
    File "include.py", line 39, in include_file
        with open('..\\{}'.format(filename)) as file:
    FileNotFoundError: [Errno 2] No such file or directory: '..\\README.rst'

**Would you like to work on the issue?**

Yes

**Comment by DravitLochan** [comment]
Please close this issue as your pr looks promising.
