### ISSUE TITLE
Addressing Fact based queries

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/susi_server#163]
@mariobehling , Please help us how to address this issue. 

![screenshot_20170508-160426 1](https://cloud.githubusercontent.com/assets/24853337/25801511/87ee5958-340b-11e7-8839-882c69cb78b9.png)
![screenshot_20170508-160223 1](https://cloud.githubusercontent.com/assets/24853337/25801510/87ed716e-340b-11e7-8c15-9a43e810e2f8.png)

**Comment by DravitLochan** [comment]
I am also looking for an API which can respond with facts about a particular entity.

**Comment by saurabhjn76** [comment]
@jyoth1raditya check this dream [facts](http://dream.susi.ai/p/facts).

**Comment by jyoth1raditya** [comment]
@saurabhjn76 , Great work
