### ISSUE TITLE
Need sample responses for each type.

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#164]
I need a list of media and sample queries for each type of testing and implementation on the iOS app. Can someone provide the same?
Thanks!

**Comment by DravitLochan** [comment]
[List](https://github.com/fossasia/susi_android/issues/601)

**Comment by chashmeetsingh** [comment]
@DravitLochan could you add an example response for each query that is sent to the server?

**Comment by DravitLochan** [comment]
you need the JSON response?

**Comment by uday96** [comment]
@DravitLochan @chashmeetsingh Did you find sample JSON responses? If so, could you share the list of sample responses for each action type?

**Comment by DravitLochan** [comment]
@chashmeetsingh @uday96 Is it solved or needs to be looked after?

**Comment by chashmeetsingh** [comment]
not yet. Need responses for pie-chart and rss.

**Comment by uday96** [comment]
Also, there's  a diagram type. Need responses for diagram type too.

**Comment by DravitLochan** [comment]
@uday96 As stated [here](https://github.com/fossasia/susi_skill_data/blob/master/README_susi_skill_language_tutorial.md#table-actions), Right now we do not have support for responding to diagram type query.

**Comment by uday96** [comment]
Yea, but I also had that doubt. But check this out :https://github.com/fossasia/chat.susi.ai/issues/72  
Must confirm it once
