### ISSUE TITLE
Currently user messages are not saved in server

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_server#167]
**Actual Behaviour**

Currently user messages are saved in local storage using realm.

**Expected Behaviour**

users messages or chat should be saved on server so that he/she can retrieve it anytime from anywhere.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by DravitLochan** [comment]
@amitiwary999 Please proceed with closing the issue as now we have a memory servlet and open in respective client's repo to implement it there. :)
