### ISSUE TITLE
Encoding issue 

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#168]
**Actual Behaviour**

Sending `1+1` in the query send `1%201`.

**Expected Behaviour**

It should instead send `1%2B1` in the query.

This will help to consume the Wolfram API for computing problems.

**Comment by dynamitechetan** [comment]
It is working. 
If you test this on http://api.susi.ai/ and pass 1+1 it will encode it in 1%2B1.
http://api.susi.ai/susi/chat.json?timezoneOffset=-330&q=1%2B1

**Comment by chashmeetsingh** [comment]
Yup, thanks!
