### ISSUE TITLE
Propose a better Signup and Accounting Process using the Server Account APIs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#169]
The current signup and accounting process is confusing. SUSI provides access to server feature through the account apps, which are separate but currently added to the SUSI Server.

The result is, that if users request a new password, they will be redirected through a link to the JSON account response. Instead of being redirected there a better solution would be if they would be directed to their mobile app (if they are on a mobile). There are a number of items to think about. So, the first step to solve this issue would be to research how common apps like Facebook are taking care of that.

* How does it work if you request a new password from the web app of Facebook and other familiar services? What are the SUSI account apps missing?
* How does it work if a user signs up or requests a new password through the mobile app? What is different and missing with the SUSI Android app?

Based on the outcome, please propose how the SUSI accounting features can be improved and open an issue for its implementation.

**Comment by saurabhjn76** [comment]
Facebook provides 2 option for signing up. Email or Phone. It sends a confirmation code like “XXXXX is your Facebook confirmation code”. Also a redirection through a link which confirms the identity of the user. If SMS delivery fails, one can choose to receive the SMS code in a phone call or, if their phone number is associated with a Facebook account. Similar things happen for password recovery. Facebook also has [account kit](https://developers.facebook.com/blog/post/2016/12/20/introducing-instant-verification/?__mref=message_bubble) for instant verification.
In SUSI mobile app **an option for signing up with the phone can be added**. Through this
 if a user signs up or requests a new password through the mobile app, SMS texts for authentication purpose will be sent by the service provider and will be automatically read by SUSI for verifying it. This flow will help the user to save a lot of app switching from Susi to messenger app and then entering the authentication text to app again. Also, this will save the redirection through the browser. We can implement this using [digits by twitter](https://fabric.io/kits/android/digits/summary).
**suggestions?**

**Comment by Fluepke** [comment]
@saurabhjn76 `we're graduating our service into Firebase and officially sunsetting the Digits brand` ...
I took a look at firebase, which is not free open source (not even free of charge) software, thus we shouldn't use this as an authorisation mechanism.

**Comment by Fluepke** [comment]
My suggestion would be to use an open source authorisation mechanism called **`OAuth 2`**.
OAuth aims at solving a common problem on the internet: Having dozens of accounts.
Large web services like `Github`, `Facebook` and `GMail` can act as an OAuth Provider, thus making it possible for users to signup and login using one of their existing accounts.
Of course, we shouldn't force any of our users to use one of those unfree services. It must be possible to login and signup by email. However, we should not put too much effort into this (integration in the android app, etc.) as most people will go for the solution described above.

What do you think about this idea? This why we could achieve a **high conversion rate** and wouldn't need to annoy our users with creating yet another account. [86% of all users feel bothered by having to create new accounts on websites](https://conversionxl.com/social-login/).
