### ISSUE TITLE
refactor the docs and web pages

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#175]
**Actual Behaviour**

Some of the files are in context with loklak server.

**Expected Behaviour**

All the files should be stating procedures for susi_server

**Steps to reproduce it**
change the files with wrong info.

**Would you like to work on the issue?**
yes

**Comment by Fluepke** [comment]
We need much more documentation on the source code. Best would be to generate doxygen readable annotations and have doxygen generate the documentation automatically.

What do you think about this?
See http://www.stack.nl/~dimitri/doxygen/ for more info on doxygen.
