### ISSUE TITLE
Gitter hubot chatbot is not working

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#177]
I followed this tutorial https://github.com/Odonno/gitter-bot-how-to#prerequisites and tried making hubot for gitter but it didn't workout.
I tried with heroku and azure both but didn't work out. 

Here is respository for all work
https://github.com/AliAyub007/SUSI_gitterbot 

*readme file is auto generated.

**Comment by Manveer695** [comment]
I think we should close this now, right? @AliAyub007
