### ISSUE TITLE
currently for every single word query susi not replying correctly

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_server#179]
**Actual Behaviour**

if user query in single word susi is  replying in same format 'Expression is:   '

**Expected Behaviour**

It should reply according to query

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-05-13-18-44-25](https://cloud.githubusercontent.com/assets/14003244/26025776/9971474e-380c-11e7-80ee-e71edb68a192.png)

**Would you like to work on the issue?**

No, Currently I am working on susi android mini-project

**Comment by chiragw15** [comment]
@amitiwary999 sorry, my fault. Used * [here](https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/sentiment_analysis.txt) to input query. Fixed by orbiter . You can close this.
