### ISSUE TITLE
Calling APIs which need Oauth

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#184]
How can we call some APIs which needs Oauth, such as using the Uber API. We can say "Book me a cab" and susi will book a cab.
We are also authenticating a user on SUSI, so we can also store his Access Token for these type of services.

**Comment by Fluepke** [comment]
Please have a look at [this issue](https://github.com/fossasia/susi_server/issues/134) as it might solve your questions 😉
Maybe we should reopen this and discuss user specific API tokens as well there.
I think there will be a need to integrate user specific credentials / authorisation information to other services (e.g. email scanning -> "when does my flight depart?", deliveroo api -> "Order me a pizza").
