### ISSUE TITLE
Accurate response to queries related to "when"

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/susi_server#187]
**Actual Behaviour**
<img width="756" alt="screenshot 2017-05-18 23 11 25" src="https://cloud.githubusercontent.com/assets/24853337/26215881/9c7ba4cc-3c1f-11e7-8157-fe535031f398.png">

<img width="758" alt="screenshot 2017-05-18 22 50 50" src="https://cloud.githubusercontent.com/assets/24853337/26216418/a6f08560-3c21-11e7-8a9f-d5add41e6dc4.png">
<img width="800" alt="screenshot 2017-05-18 22 49 31" src="https://cloud.githubusercontent.com/assets/24853337/26216422/ac1d6030-3c21-11e7-8bfd-f6e17d0a60a8.png">

Currently reply is "When was this exactly?"

**Expected Behaviour**

To respond with date or year in which event happened.

**Comment by jyoth1raditya** [comment]
I am working on it. Please assign this issue to me

**Comment by chashmeetsingh** [comment]
Hey, @jyoth1raditya you can take a look at https://products.wolframalpha.com/api/explorer/, gives accurate responses.

**Comment by jyoth1raditya** [comment]
Thanks for sugesstion, I already sent PR to the issue. Using wolfram alpha.
