### ISSUE TITLE
Accurate response to queries related to "Who"

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/susi_server#188]
**Actual Behaviour**
<img width="619" alt="screenshot 2017-05-18 23 45 22" src="https://cloud.githubusercontent.com/assets/24853337/26217139/06a2207a-3c24-11e7-981b-f1ee158bb710.png">
<img width="611" alt="screenshot 2017-05-18 23 45 30" src="https://cloud.githubusercontent.com/assets/24853337/26217173/20793fc4-3c24-11e7-9219-dae04b2568e5.png">
<img width="619" alt="screenshot 2017-05-18 23 45 22" src="https://cloud.githubusercontent.com/assets/24853337/26217176/229ea794-3c24-11e7-86c8-2433e9abbbc2.png">

Returning some random comments

**Expected Behaviour**

To return name of the person and any additional details

**Comment by jyoth1raditya** [comment]
I am working on this issue

**Comment by saurabhjn76** [comment]
dream [facts](http://dream.susi.ai/p/facts) can answer such queries, but it is too general, you can make it specific.
![susi_chat](https://cloud.githubusercontent.com/assets/9781788/26217978/029cd1fc-3c27-11e7-9ca3-eaedfe793b0e.png)

**Comment by jyoth1raditya** [comment]
Solved the issue and sent PR to susi skiils.
The name od dream is "who"
