### ISSUE TITLE
SUSI AI verification

### ISSUE THREAD

**Issue by droms** [fossasia/susi_server#189]
**Actual Behaviour**
```json
{
"session": {
"identity": {
"type": "email",
"name": "contactable@protonmail.ch",
"anonymous": false
}
},
"message": "You successfully verified your account!"
}
```

**Expected Behaviour**

Shows a friendly html page to the user

**Steps to reproduce it**

Sign up from Android app and click on the verification link in the email

**Comment by sudheesh001** [comment]
This is the serverside, Showing the well formatted HTML should be done by the application that uses susi as it's API service.

**Comment by droms** [comment]
My mistake I thought this was responsible for email verification link
