### ISSUE TITLE
What are action types

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#198]
Please explain the concept of action types.

**Comment by Orbiter** [comment]
Different clients provide different kind of possible behaviour: some clients may be able to play a song, other may be able to draw a piechart.

The server must be able to return only such kind of actions, which the client is able to show.
That is done using action types.

for example, you can call susi with:
`http://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=who+are+you`
and get a result like:
```
{
  "query": "who are you",
  "count": 1,
  "client_id": "aG9zdF8xNzguMjAzLjIzMy4yMDk=",
  "query_date": "2017-05-28T09:53:14.262Z",
  "answers": [{
    "data": [{
      "0": "who are you",
      "intent_original": "are",
      "intent_canonical": "are",
      "intent_categorized": "be",
      "timezoneOffset": "-120"
    }],
    "metadata": {"count": 1},
    "actions": [{
      "type": "answer",
      "expression": "I was told not to talk to strangers if I am asked such private things"
    }]
  }],
  "answer_date": "2017-05-28T09:53:14.501Z",
  "answer_time": 239,
  "language": "en",
  "session": {"identity": {
    "type": "host",
    "name": "178.203.233.209",
    "anonymous": true
  }}
}
```
Here you see the action with type `answer` which tells the client to either write or say the `expression`. If the `answers` object would have an `actions` action with type `piechart` and the client is not able to render a pie chart, then we have a problem.

Therefore, the client must send it's abilities to the server, so the server can select only such skills which produce action types that the client understands. For example:

`http://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=who+are+you&actions=answer,piechart,table`

sends the information that the client is able to render answer, piechart and table actions

**Comment by psikarwal** [comment]
I guess the commit of @Orbiter, explains enough.
Can this issue be closed @mariobehling @Orbiter.
