### ISSUE TITLE
Short-Hand Notation question issue

### ISSUE THREAD

**Issue by sagarchoudhary96** [fossasia/susi_server#2]
# Short Hand Notation issue
If we use short hand notations in questions it replies with default message. like if we ask:-
 

> hw r u?

 then it replies with

> you can ask me anything,but not that :)

**Comment by shivenmian** [comment]
Not a valid issue. That's true for all bots.

**Comment by sagarchoudhary96** [comment]
But like in allo ...if we see it responds to short hand questions too...

**Comment by shivenmian** [comment]
That doesn't make it important. Our dataset should cover more **essential** data, and also the number of shorthands can be a lot for different phrases so doesn't make sense.
