### ISSUE TITLE
Adding limit to the response

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#208]
**Actual Behaviour**

Currently, the data object outputs all the response fetched from the skill

**Expected Behaviour**

There should be a limit to the number of items in the data object

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=universities+in+united+states

We can add a limit parameter in the query to limit the number of objects.

**Comment by Orbiter** [comment]
added a length parameter in https://github.com/fossasia/susi_server/commit/d64ab795663846077c98896404585c203b583f7b

The skill takes now a 'length' attribute which limits the number of lines for the given number.

Please test the skill and add a client implementation.
For details, see https://github.com/fossasia/susi_server/commit/d64ab795663846077c98896404585c203b583f7b

**Comment by DravitLochan** [comment]
@Orbiter I think it is not complete yet. I tested it on [this](http://dream.susi.ai/p/images) dream. The API by default sends 10 links. I added length = 5 in etherpad but still there are 10 responses. Please see.
