### ISSUE TITLE
Improving Susi Apps page

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_server#212]
**Actual Behaviour**

http://api.susi.ai/apps/applist/index.html This is current page. 

**Expected Behaviour**

* Need to replace loklak with Susi. 
* Adding information about the project. 

@mariobehling @Orbiter What all changes needs to be done here? Do we need to change theme? Do we have to remove it completely and make it from scratch? What extra things need to be added?

**Would you like to work on the issue?**
yes

**Comment by DravitLochan** [comment]
I have already opened #175  related to this. It did not mention app/web pages but I am already working on it. I have also updated the issue. You may close it :)

**Comment by DravitLochan** [comment]
@Orbiter @mariobehling Please guide!

**Comment by chiragw15** [comment]
@DravitLochan I went through each and every issue on the tracker before opening this issue to avoid duplicated. Your issue clearly stated "refactor the docs" which you changed it to "refactor docs and web pages" **few hours** ago.
![screenshot from 2017-06-01 14_41_37](https://cloud.githubusercontent.com/assets/16978820/26673146/7b7e3e1e-46d9-11e7-8523-6762fe6963be.png)
Please please please don't do this kind of stuff. If you want to work on the issue, you should have just told me. I would have find some other issue and worked on. I really don't have a problem doing that. But these kind of stuff really demotivates me.

**Comment by chiragw15** [comment]
Apart from that, this issue is not just about changing "loklak" with "susi" but about changing theme and structure of apps page. May be even implementing it from scratch.

**Comment by DravitLochan** [comment]
I am sure you did go through all the issues and tried to avoid duplicates. I did not intend to demotivate you and hence I mentioned that " It did not mention app/web pages but I am already working on it." Theme looks good to me hence I focused on changing loklak to susi and make changes in relevant information only. 
Cheers

**Comment by chiragw15** [comment]
`"It did not mention app/web pages but I am already working on it"` 
This is not how fossasia or any other open source organization works. You have to clearly state in the issue what are you working on. How can other people know what are you working on if you don't clearly mention the issue. If I create an issue regarding "updating loklak to susi in docs", it means I will update loklak to susi in docs and nothing else. I don't know, this issue is yours now. @mariobehling will guide you about the theme and all. Cheers.

**Comment by DravitLochan** [comment]
okay! My bad. Please continue with your work

**Comment by chiragw15** [comment]
No, I have just started it. You are doing it for long time. Continue it. Let's be effective and work more. But next time please create relevant issues. :+1:

**Comment by mariobehling** [comment]
The apps page should be deleted as soon as other ways are ready. Therefore closing it.
