### ISSUE TITLE
Add AskSusi to zulip

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#23]
Propose and implement integration with Zulip. What needs to be done on the Susi project? There is an issue here on the zulip project: https://github.com/zulip/zulip/issues/2168

**Comment by vedantrathore** [comment]
@mariobehling can I work on this, I'll try to do it and post here or the gitter channel If I run into any issues.

**Comment by mariobehling** [comment]
@vedantrathore Yes, cool. Zulip recently brought out some documentation: Instructions for all integrations are at https://github.com/zulip/zulip-gci/blob/master/tasks/webhook-integrations.md.

**Comment by AnaghHegde** [comment]
@mariobehling Is this still open?.Can i work on this ?

**Comment by DNS-404** [comment]
SUSI has been integrated to Zulip. https://github.com/fossasia/susi_zulipbot
So, I'm closing this.
