### ISSUE TITLE
Susi Wiki Concept

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#242]
This is a concept for the management of the skill repository https://github.com/fossasia/susi_skill_data
aka
The "Susi Skill Wiki"

We want a personal assistant where the users are able to write and edit skills in the most easiest way that we can think of. To do that we develop:
- a very simple skill language
- a very simple skill editor

The skill editor should be done as a 'wiki'-like system as idea. To create the wiki, we do an API-centruc approach:
- the susi_server acts as API server
- a web front-end (angular, react, ... techn. not decided yet) with act as client of the API and provides the user interface

The skill editor will be 'expert-centric', an expert is a set of skills. That means if we edit one text file, that text file represents one expert an it may contain several skills which all belong together.

An 'expert' is stored within the following ontology:
```
* model
|-- * group
    |-- * language
         |-- * expert
             |-- skill
```

Therefore, we can access every expert with the 4-tupel
```
{model, group, language, expert}
```

Using that schema, we can organize all skills in https://github.com/fossasia/susi_skill_data

The following api endpoint accesses a single text within that repository:
http://api.susi.ai/cms/getexpert.txt?model=general&group=knowledge&language=en&expert=wikipedia

If you call that enpoint, you get the plain text of the expert.

To realize the wiki on the server side, we need the following **API endpoints**:
- loading experts (done, see above)
- creating experts, create a history for that expert
- modifying an expert, modifying the history for that expert
- deletion of an expert including it's history (consider this really needs different rights)
- listing of experts for given `{model, group, language}`
- listing of languages for given `{model, group, expert}`
- listing of groups for given `{model}`
- listing of models for given `{}`

That should not be too difficult. The API endpoints are servlets in
https://github.com/fossasia/susi_server/tree/development/src/ai/susi/server/api/cms
where there are already some dummy classes for the servlets as named above.

Please use https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/api/cms/ExpertGetTxtService.java as template to create all other endpoints.

**Comment by Orbiter** [comment]
Please open issues for all API endpoints and work on them:
* place the work to https://github.com/fossasia/susi_server/tree/development/src/ai/susi/server/api/cms
* omit historization for the first implementation step, we do this later
* omit authorizaton for the first implementation step, we do this later
* every call to the API endpoint must use the 4-tuple `{model, group, language, expert}` as attributes in the query parameters, like in http://api.susi.ai/cms/getexpert.txt?model=general&group=knowledge&language=en&expert=wikipedia

**Comment by chiragw15** [comment]
IBM Watson conversation is similar to susi skill wiki. It lets you develop your own skills and train them on their model. They also have structure similar to susi skill wiki. The have workspaces, intents, dialogs, entities etc. It is not that similar but the concept is same: Let user define his own skills. We can make front end similar to it (ref image http://nicolasquintero.com/img/work/convo_8.png ) with a chat interface on the right and editing interface on the left. They have similar apis too for adding, deleting and modifying workspaces (in our case experts) and some other similar apis. Incase we need some ideas about front end or apis, we can also look at their structure. (https://www.ibm.com/watson/developercloud/conversation/api/v1/#introduction).

**Comment by Orbiter** [comment]
@chiragw15 good point, yes that can be an inspiration, lets point out which details we could use for Susi as well

**Comment by jyoth1raditya** [comment]
Thanks for guidance @Orbiter 👍
