### ISSUE TITLE
Adding a video/audio action type

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_server#252]
**Actual Behaviour**

Currently `mixcloud` is searched and the webpage address is given which may/may not contain data.

**Expected Behaviour**

An action type of an audio/video should be returned + the audio/video file url that needs to be played.

**Steps to reproduce it**

http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=play+wildest+dreams
Above query will help.

**Comment by chiragw15** [comment]
Proposed implementation : Make a skill with query " play * " . Use youtube api to fetch list of videos with search query $1$ . Send the list of first 10 urls of the video fetched from youtube api to client along with action type "play". eg
```
"actions : [
{
        "type": "answer",
        "expression": "Here is a list of videos."
      },
      {
        "type": "play",
        "links": [{"https://www.youtube.com/watch?v=ID1"},{"https://www.youtube.com/watch?v=ID1"}]
      } 
}]
```

**Comment by chashmeetsingh** [comment]
Yes, let's create one for it then.
