### ISSUE TITLE
Implement "Delete Account" feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#26]
Currently there is no feature to delete an account. Please implement this feature.

**Comment by Orbiter** [comment]
should it be possible to gain access to historic data (i.e. edited rules) when an account is re-created for the same user?

**Comment by mariobehling** [comment]
Not sure. Maybe yes.

**Comment by Orbiter** [comment]
implemented with https://github.com/fossasia/susi_server/commit/a2a6150e40dde14f3122625e20d8cbbb7a8d5e14

This does not delete the assigned permissions, not the accounting data and not the accumulated personal log (susi variables) and the edited rules. If the user creates the account again, the values are still there.

**Comment by Orbiter** [comment]
can be tested on the 'log in' page within the app range
