### ISSUE TITLE
Memory servelet support for displaying entire chat history

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#261]
**Actual Behaviour**

As of now, the clients use the memory servelet - https://github.com/fossasia/susi_server/commit/7d6245904c995a3aa5452e1ddbc99c35bddc9d86 to get chat history. But the servelet returns only 10 recent messages.

**Expected Behaviour**

We need a method in which we must be able to get the entire user history and not just a recent 10 or few.

Few ideas:
 1.  Removing the cognitions limit in the servelet and return the entire history. (This is a bad approach I guess cause the history could be huge?)
 2.  A method to give history messages as a group of a few (say 10) based on a request parameter determining how recent messages must be returned.
 For ex: suppose a user has 100 messages in total numbered 1 - 100 with 1 being most recent and every query to servelet returns 10 messages,  and say the request parameter is ```groupNo```
   So request like http://api.susi.ai/susi/memory.json?groupNo=0 must return messages 1-10
   and http://api.susi.ai/susi/memory.json?groupNo=1 returns 11-20 and so on, handling corner cases.
Something like this would allow the client to dynamically query history as the user scrolls up.

Please do suggest any other alternatives. The basic necceessity is to be able to access the entire chat history of the user

**UPDATE:**
A working solution as of now:
  1. Client sends the last message's identifier (preferably ```query_date``` or ```answer_date``` as of now or a new ```message id``` could be introduced) as a request parameter
  2. Server searches for the particular message using the identifier from the request param, in the cognitions array and returns the next few messages(say min(10,messages left)) along with the count of messages left in the user history (so that client knows when to stop querying for history)
This way client can dynamically query history accordingly without worrying about sync.

**Comment by chiragw15** [comment]
@uday96 in second approach we will also need to send number of messages along with reponse. Like suppose total number of messages of user are 27. So, first and second response will include "numberOfMessages = 10" , the third one will include "numberOfMessages = 7" and the fourth one will include "numberOfMessages = 0". So, now since we have numberOfMessages = 0 , we know that there are no more messages, so we will stop sending a request for more results. What say?

**Comment by saurabhjn76** [comment]
@uday96 @chiragw15 sounds good !!

**Comment by uday96** [comment]
@chiragw15 Yes, that sounds good. Also, I have a doubt, in the meantime while we make queries for history, in case the user converses with susi, will the current conversation also be recorded in the history? If so, we need a method to get the history accordingly avoiding duplications as the indices of the history messages in the cognitions will change. Any ideas?

**Comment by chiragw15** [comment]
@uday96 No, we will only make queries for history when user scrolls up. Lazy Loading technique.

**Comment by uday96** [comment]
@chiragw15 No, thats fine, what i meant was, the current session messages will also be stored as history right? Initially when the session just started, if the user history is say 100 (1-100) messages, and we make our first call to get 10 (1-10) recent messages. Suppose the user continues to chat for some time and has 5 new messages in the current session and then scrolls up, we then make a call to the servelet, but this time, the servelet might actually have 105 messages instead of 100, so the indices of the messages to query will change na? This time we need 15-25 and not 11 to 20 because of the current session messages being synced (Will they actually sync with history that soon?). Am i clear?

**Comment by uday96** [comment]
So, in that case my idea is to send the count of messages currently present in the client so that the servlet just has to return count - count + 10.
For ex: initial call : count=0, so servelet returns 0-10
   For next call when user has some 5 new messages in the current session + 10 history messages previously queried: count=15, so servelet return 16-25 (here im assuming the current messages have been synced with history)

This is a better approach i guess if the syncing with history is happening for the current session too.

**Comment by chiragw15** [comment]
Yes, I got the problem with this approach now. This approach shall not work then. There will be duplicates if a user queried. Different approach : 
Instead of sending group number along with query, we can send somehow send a reference (don't know what's reference gonna be, maybe exact query_time of the message, It will be different for all messages) to the last message we have on client and get next 10 messages.

**Comment by uday96** [comment]
@chiragw15 If the sync between client and history has very little delay, the count approach will work i guess. If it takes time to sync, I think sending an identifier or reference for the last message like you said is better. We wouldnt need groupNo also then, just identify the message in cognitions array and return 10 more from there  :smile: 

The count approach would be faster as we already know the index of the message in the cognitions array.
But the last message identifier/reference approach sounds more accurate. :+1:

**Comment by chiragw15** [comment]
@uday96 This identifier/reference way, we won't even have to worry about if the messages are being synced or not. It will be fast too. We can find the index of the message in cognitions array in O(logn) time using binary search. There will not be much difference in time taken.

**Comment by uday96** [comment]
@chiragw15 True, I agree. Im also in for the message identifier method :+1:

**Comment by uday96** [comment]
```query_date``` or ```answer_date``` could be used as identifier and the response must also include remaining messages in history so that client knows when to stop making calls like you suggested.
This sounds like the final working model? @chiragw15 Right?

**Comment by chiragw15** [comment]
Yes, we can use query_date and answer_date. There won't be any problem with it, I guess. Alternatively, if possible, we can also define a new reference as "message_id" which can be send in the response and then use it as reference. We need to confirm it from @Orbiter if this is possible. This way will be better. But if it's not possible, the query_date reference is fine.

**Comment by chiragw15** [comment]
@Orbiter Can you please guide a little on this issue if this is the intended solution for this?

**Comment by uday96** [comment]
Closing via https://github.com/fossasia/susi_server/pull/323
