### ISSUE TITLE
Location skill error

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#269]
**Actual Behaviour**

**Query :**  http://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=where+am+i
Though the optional parameters latitude and longitude are not given in the server call, the server still returns a map type response but with incomplete information.

**Expected Behaviour**

If the location cannot be given, the action cannot be performed because the information is missing. It is the responsibility of the server (and the skills) to perform accordingly.

**Steps to reproduce it**

Query :  http://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=where+am+i

>"actions": [
      {
        "type": "answer",
        "select": "random",
        "phrases": ["You are here: https://www.openstreetmap.org/#map=13/$latitude$/$longitude$"]
      },
      {
        "type": "anchor",
        "text": "Link to an Openstreetmap for your location"
      },
      {
        "type": "map",
        "zoom": "13"
      }
    ]

**Comment by DravitLochan** [comment]
@uday96 Until we do not have location details on the server for the user, It is not possible to get this result from the server.
