### ISSUE TITLE
Installation is failling while installing loklag file is missing

### ISSUE THREAD

**Issue by dexta11** [fossasia/susi_server#27]
![s1](https://cloud.githubusercontent.com/assets/22263960/20455967/b09b7fb4-ae8e-11e6-9d95-eabb766936fe.png)
![s2](https://cloud.githubusercontent.com/assets/22263960/20455970/b21dc22a-ae8e-11e6-9103-74c839a068a2.png)

**Comment by BrainBuzzer** [comment]
https://raw.githubusercontent.com/fossasia/susi_server/2f8184b2ba1c1c7dc4c48f051aac3182bec0a5ef/conf/susi/susi_cognition_boilerplate.json.example

Save this file in your folder `/conf/susi/` and you will be ready to go.

**Comment by dexta11** [comment]
Thank You.. :)

**Comment by jig08** [comment]
@BrainBuzzer @dexta11 Issue resolved ?

**Comment by dexta11** [comment]
No still getting same error.

**Comment by dexta11** [comment]
issue resolved thank you.:)
