### ISSUE TITLE
Add mockup designs for the WIKI

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#278]
add the designs for the wiki, once the design is discussed and finalized. We can move forward with implementation steps.

**Comment by dynamitechetan** [comment]
![image](https://user-images.githubusercontent.com/14369357/27013632-d9ad0c30-4f04-11e7-884e-1d246811cd48.png)

**Comment by Orbiter** [comment]
Can we have an editor bar above the skill text which contains buttons like "if the user says..." and then, if that was pushed "susi says"/"susi shows an image"/"susi says + provides pre-defined answers"

Like the visual editing buttons in a normal wiki, but here they would write down templates.

**Comment by chiragw15** [comment]
@dynamitechetan The mockup looks great. A little suggestion. Can we have a display/hide option for chat to increase workspace area. User can click on that button to hide chat interface, then click on the button again to display it. Like the cross in the top right corner of the photo. What say?
![screenshot from 2017-06-12 09 14 55](https://user-images.githubusercontent.com/16978820/27018741-4481bbdc-4f50-11e7-8991-7ab60f4ed44f.png)

**Comment by dynamitechetan** [comment]
@Orbiter  please tell us which one you think is fine
![image](https://user-images.githubusercontent.com/14369357/27032251-a4fe482c-4f91-11e7-8dcc-eabd43d4c6cd.png)
![image](https://user-images.githubusercontent.com/14369357/27032259-addf25a6-4f91-11e7-8f7c-5e6eca200bd0.png)

**Comment by mariobehling** [comment]
Please follow the design and colors of the chat app and open relevant issues in the wiki repository. The server tracker is not the right place as we have a dedicated repo and tracker for the wiki. Therefore closing it.
