### ISSUE TITLE
Common UI for all the clients.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_server#280]
**Actual Behaviour**

Right now we have totally different UI for all the clients.

**Expected Behaviour**

There are many other assistants like Siri, Hound, Cortana, Alexa and Google Assistant. What we want is a common UI for all the susi clients (like facebook messenger). So, what we can do is pick all the best items from these assistants, tweak them a bit and come up with a good common UI for all susi clients. 

@Fluepke @dynamitechetan @saurabhjn76 @DravitLochan @jyoth1raditya 
@mayank408 @amitiwary999 
@Manveer695 @AliAyub007 
@betterclever
@chashmeetsingh 
@isuruAb @rishiraj824 @uday96 @madhavrathi 
Need ideas on this.

**Comment by mariobehling** [comment]
We need to discuss and follow up on this elsewhere as this is not directly related to the server.
