### ISSUE TITLE
Create a Console Rule Learning App

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#29]
We want to be able to make it easy to create new console rules. Those rules are the method to attach external knowledge to susi. To check and store new console rules, there is now the rule learning backend api, the details are described here: https://github.com/fossasia/susi_server/blob/development/src/org/loklak/api/learning/ConsoleLearning.java#L45-L163

To store a new console rule, the user has to enter at least the following entries:
- the external json API address
- an example input for that API
- a name for the new console rule

Furthermore, the user must submit a jsonpath which points into a result array within the JSON from the console API. The new back-end process supports the user by finding that jsonpath automatically.

What we need:
- an input window for those three options
- a 'verify' button which calls the backend. That will return a lot of information together with the jsonpath which the user can edit. 
- a 'store' button which can be used when the user is satisfied with the back-end verififaction.

**Comment by daminisatya** [comment]
@Orbiter Is this issue open to everyone? Or a GCI Task?

**Comment by mariobehling** [comment]
Open to anyone. It might be useful to split it into sub-issues once a basic version is there.

**Comment by daminisatya** [comment]
Cool, I would like to work on the basic outline for this.

**Comment by Orbiter** [comment]
We would like to have GCI tasks for students to create console rules using this feature. I don't think that the GUI for this back-end is very complex. The complexity is only to understand what it means. The App itself is probably a very easy thing.

**Comment by daminisatya** [comment]
@Orbiter i think we should tag this for GCI.

**Comment by Orbiter** [comment]
hi Damini, whats the status here?

**Comment by daminisatya** [comment]
@Orbiter I havent started on it yet. Will send the updated code this weekend.

**Comment by BrainBuzzer** [comment]
I'm on it.

**Comment by daminisatya** [comment]
@BrainBuzzer sure assigning it to you. Any help you can comment here.
