### ISSUE TITLE
Deploying Fossasia bot repositories onto heroku instead of our personal repositories 

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#291]
**Actual Behaviour**

Currently bots are hosted from the repositories that we own not from Fossasia bot repositories. 

**Expected Behaviour**

Bots should be hosted from fossasia bot repositories so that if any new feature or change gets pulled to fossasia bot repository it should be deployed automatically. 

**Steps to reproduce it**

In order to host bots from fossasia repositories onto heroku I need to be an owner of that repository. Right now I can fork a repository and host it but it will be only from my end if I pull changes to fossasia bot repository they won't get upload as that repository is not deployed. 

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
@AliAyub007 Do you need to be owner or admin? Which repository should be the first to try?

**Comment by AliAyub007** [comment]
Owner I think because heroku only shows repositories I own for deploying. We can first try with susi_telegrambot [https://github.com/fossasia/susi_telegrambot](url)

**Comment by mariobehling** [comment]
@AliAyub007 I made you an admin of this repository. If it does not work, we need to work together to make this work from my FOSSASIA owner account.

**Comment by AliAyub007** [comment]
@mariobehling Yes it worked. I have successfully deployed telegram bot from Fossasia repository and enabled automatic deployments. Kindly accept this PR ( https://github.com/fossasia/susi_telegrambot/pull/14 )now it will prevent heroku from sleeping after few minutes of inactivity.

**Comment by mariobehling** [comment]
@AliAyub007 Please get two contributors to approve your pull requests.

**Comment by AliAyub007** [comment]
Yes done 👍

**Comment by AliAyub007** [comment]
![admin](https://user-images.githubusercontent.com/25840461/27140298-9d654a8a-513e-11e7-9ed1-ef3b53890eef.PNG)

@mariobehling I got this when I tried deploying other bot repositories.

**Comment by Manveer695** [comment]
@mariobehling Yes sir, we need the access to deploy the susi bot repo's to Heroku. That way we can properly check if the repo present in Fossasia account are working properly or not. Thank you.

**Comment by mariobehling** [comment]
Please try again. I added admin rights.

**Comment by AliAyub007** [comment]
Yes sir working now. Thanks

**Comment by Manveer695** [comment]
@aliayub007 let's close this issue then.
