### ISSUE TITLE
Update the APIs(servlets) to keep the flow of server and website 

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#294]
**Actual Behaviour**
Currently, server looks in the 'html' directory to respond to API calls related to them. For instance to get a list of all the apps, client has to make a call here->http://api.susi.ai/cms/apps.json
To respond to this, what server does is gets the list of apps present in html/apps/ directory and encodes their app.json file as an array and sends to the client.
But now when the site is shifted to accounts.susi.ai, server won't be able to make this local reference. 

**Expected Behaviour**
Change this working of the server and update all the servlet end points with a new approach.

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
I don't this the `accounts.susi.ai` repository should use http://api.susi.ai/cms/apps.json as endpoint, it should organize itself in a different way. The apps.json should not be altered or adopted for this.

**Comment by DravitLochan** [comment]
then should we traverse to each app directory and pick the app.json ?
