### ISSUE TITLE
Servlet to delete a message

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#295]
**Actual Behaviour**
No message can be deleted. All the messages are stored in server.

**Expected Behaviour**
Since all the clients are contacting server for previous messages, We should have delete message(s) functionality in all the clients.

**Steps to reproduce it**
Add a servlet which receives a parameter from clients to delete a message. 

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
@mariobehling should this feature be implemented and corresponding issues open in client repos as well?

**Comment by Orbiter** [comment]
What is a message? And why should we delete it?

**Comment by DravitLochan** [comment]
We should give an option to user to delete message(s). Those messages which are retrieved from previous logs and displayed whenever a new session of an already registered user is initiated. There could could be multiple reasons a user might want to delete some messages.

**Comment by mukul7** [comment]
I wanted to work on this. can i claim this?
