### ISSUE TITLE
Setup automatic builds for SUSI Server on Dockerhub

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#297]
loklak has an automatic build. Please implement the same for SUSI server on Dockerhub. Request access if needed.

https://hub.docker.com/r/fossasia/susi_server/

**Comment by jyoth1raditya** [comment]
@mariobehling, I am working on this. I need access of fossasia account to build auto-builds of susi.

**Comment by abishekvashok** [comment]
@mariobehling can I work on this?

**Comment by abishekvashok** [comment]
:CC: @jyoth1raditya

**Comment by abishekvashok** [comment]
@mariobehling pls close this as it was solved.

**Comment by norbusan** [comment]
Agreed, this should be solved. @mariobehling do you agree?
