### ISSUE TITLE
Use Accounting object to read and write user properties 

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/susi_server#298]
**Actual Behaviour**

As of now, the **Accounting** object is not used at all to enable clients to throw in user data to the server. Refer https://github.com/fossasia/chat.susi.ai/issues/119#issuecomment-305562267 for more.

**Expected Behaviour**

As pointed out by @Orbiter in chat, in DAO there is an accounting JSONTray object which is not used at all. And there is an accounting_temporary object which has a non-persistent http access history. One needs to distinguish them better. What needs to be done here is the so far unused accounting JSONTray is to be used to simply write our user settings. One can re-name it to user_settings or we re-name accounting-temporary to user-access-log.

**Steps to reproduce it**

These lines in the code have been added https://github.com/fossasia/susi_server/blob/development/src/ai/susi/DAO.java#L357-L363
to now easily access an accounting object. That is the place to write user properties inside. One has to write and read into those objects. Then one can use that **new API** to read and store user settings.

**Would you like to work on the issue?**

Anyone is free to take this up.

**Comment by Orbiter** [comment]
We simply need an api endpoint to write to and read from the mentioned object
