### ISSUE TITLE
Add Support for Emoji Characters

### ISSUE THREAD

**Issue by addiittya2006** [fossasia/susi_server#3]
Support for Emoji Unicode Characters needs to be added to Susi server to parse emoji input for the API. Multiple rules regarding Emojis also need to be defined.

**Comment by jig08** [comment]
>Multiple rules regarding Emojis also need to be defined.

@addiittya2006 Explain pls.

**Comment by addiittya2006** [comment]
For Susi to parse Emoji characters, we need to define rules for that Emoji related to the Emoji Character based on its unicode. Susi shall be able to predict basic expressions based on the Emoji entered by the user.
[Maybe sometime in the future proposal] because of a lot of Emoji Characters.
This issue was referenced from fossasia/susi_android#36.

**Comment by Orbiter** [comment]
I cannot see how this issue is different from a "support full UTF-8 support" requirement. We have utf-8 support. Therefore I cannot see that anything has to be done for this issue. Please check the ability to use utf-8 (which then includes emojis) and if that works (which should) close this issue.

**Comment by sbhayana26** [comment]
Does the issue still need to be worked upon?

**Comment by Abhi2424shek** [comment]
@jig08 then consider opening it?

**Comment by Abhi2424shek** [comment]
Well is anyone working on it? Consider updating the description?

**Comment by addiittya2006** [comment]
We already have UTF-8 Support and all the emoji characters are unicode but The issue was proposed to parse the emoji as ascii text and then check rules against that.
@Orbiter @jig08 If you consider this a valid proposal, consider this otherwise the issue can be closed.
😕 -> 'confused face' -> rule confused
😁 -> 'grinning face with smiling eyes' -> rule extremely happy

**Comment by daminisatya** [comment]
@addiittya2006 Valid, go ahead and create rules for these emoji texts. Create an initial rule set and a PR. we will review it.

**Comment by jig08** [comment]
@addiittya2006 Sounds good. As @daminisatya create an initial PR for review so that we can take this forward :)

**Comment by addiittya2006** [comment]
Ok. As Soon as I am available to write code.

**Comment by mariobehling** [comment]
Susi already has Emoji support, but there are no skills written for it. Therefore closing it.
