### ISSUE TITLE
Generate a documentation site from the md files in a gh-pages branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#30]
The idea is to have one stop resource for Susi tech questions at http://dev.asksusi.com

Currently there are two places with resources for the server:
1. The Readme.md https://github.com/fossasia/susi_server/blob/development/README.md
2. The docs folder: https://github.com/fossasia/susi_server/tree/development/docs

Please autogenerate a simple documentation site on each new commit in the gh-pages branch.

**Comment by BrainBuzzer** [comment]
It is supposed to start from scratch then. Please create a new repo with dev.asksusi.com

**Comment by mariobehling** [comment]
Please put it into a gh-pages branch of this repository.

**Comment by adarsh-ideal** [comment]
@mariobehling I want to work on this. Please allow me to do that. I'l create a new gh-pages repository (it doesn't have one yet) for this on my forked repo. But then it will display the Readme and other instructions in docs folder of gh-pages branch instead of development branch. Is that okay?

**Comment by adarsh-ideal** [comment]
@mariobehling Can't wait for your reply. I'm working on this.
Please create a new gh-pages branch to merge my changes.

**Comment by mariobehling** [comment]
Done. Created a gh-pages branch.

Please delete the content and make a PR with your changes. Thanks!

**Comment by adarsh-ideal** [comment]
@mariobehling Thanks for creating the branch.
Should I just keep the Readme and docs folder, this branch is only for infromation and nothing else, isn't it.
I have done changes and it's available on my repo: https://adarsh-ideal.github.io/susi_server/
I'll make the PR after deleting all the contents except the required .md files. I haven't deleted them yet, just wanted to show you first.

**Comment by mariobehling** [comment]
@adarsh-ideal Thanks.

The goal is to generate the site from the Readme.md files in the development branch on each PR. Could you implement this? Cheers.

**Comment by adarsh-ideal** [comment]
@mariobehling I think this issue can be closed now. Or there is something else left?

**Comment by Abhi2424shek** [comment]
Is this being auto generated for each commit?

**Comment by BrainBuzzer** [comment]
No. We have to edit the documentation separately.

**Comment by Abhi2424shek** [comment]
@mariobehling @BrainBuzzer can I make it auto-generate then?

**Comment by BrainBuzzer** [comment]
Go ahead

**Comment by mariobehling** [comment]
This issue is not solved. The gh-pages branch should be auto-generated from the md files in the development branch on each commit.

**Comment by adarsh-ideal** [comment]
@mariobehling Please check the information you gave previously "Please autogenerate a simple documentation site on each new commit in the gh-pages branch" . It was gh-pages branch not development.

**Comment by adarsh-ideal** [comment]
@mariobehling Sorry if I misunderstood.

**Comment by adarsh-ideal** [comment]
@Abhi2424shek Are you working on it, tell me if you need some help. We could work on this together.

**Comment by Abhi2424shek** [comment]
@mariobehling or some other mentors can you add a variable named SOURCE_UPDATER in the Travis CI dashboard pls, the value of the secret variable will be given by me, when you are ready pls comment here.

**Comment by Abhi2424shek** [comment]
@mariobehling here are two PRs for to close this issue #60 and #61 please review and merge.
