### ISSUE TITLE
Add isimportant attribute in the response

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#301]
**Actual Behaviour**
Due to the fact that it was implemented in android app only(that to hardcoded) , it has been removed. There is no such parameter.

**Expected Behaviour**
There should be this parameter isImportant. A separate option should be there to read the question and response to it in each client. Main implementation on server to store isImportant in a message response.

**Would you like to work on the issue?**
Yes

**Comment by betterclever** [comment]
This is not present in any other assistant currently and personally I don't find its need. Opinions might differ though.

**Comment by DravitLochan** [comment]
I looked at whatsapp and proposed this. Notworking on this until we get a final decision for it.

**Comment by betterclever** [comment]
Whatsapp is a messaging app imo. Susi is a personal assistant. Thus, I don't find its utility here.
