### ISSUE TITLE
Free Dyno Hours for one month on Heroku got finished

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#303]
**Actual Behaviour**

We have hosted our bots onto heroku and they should run 24/7. 

**Expected Behaviour**

We are using free services so we have only 550 hours in month to use which got exceeded right now. We should make our bots run 24/7 non stop.

**Steps to reproduce it**

Finding any other hosting option or coming up with new idea for it.

**Screenshots of the issue**

![heroku](https://user-images.githubusercontent.com/25840461/27270497-fd0197ea-54d7-11e7-96ea-bb15f9465f6c.PNG)

**Comment by betterclever** [comment]
Suggestion: You may deploy it on Google Cloud Free tier

**Comment by AliAyub007** [comment]
As soon as my account will get out of 300$ free amount (which is already 221$ now due to susi_server deployment) it will also stop.

**Comment by mariobehling** [comment]
@AliAyub007 I think for us Heroku is a test service. We need to move to a more advanced set up.
1. Development branch -> deployed for testing on Heroku
2. Master branch -> deployed elsewhere for production (to be decided)

Therefore we don't need a keep it alive 24/7 on Heroku.

This project is both a) a software projcet and b) a service.

We don't consider b) the service in production right now and the deployment need to be added into the larger set up flow, which needs to be defined later.

Right now, we need to ensure all bots work as expected and every small step of set up functioning is documented, so anyone can set it up.

And, we need to set up the separation of development and master. Please take the necessary steps. Therefore I am closing this issue.

**Comment by AliAyub007** [comment]
@mariobehling  Oh okay thanks for clarification and guiding.
