### ISSUE TITLE
Limiting table type response to 10 top entries

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#308]
**Actual Behaviour**

Currently table type response returns as many entries as it contains. query universities in germany? returns 285 results now.

**Expected Behaviour**

It should return top 10 entries and it should contain three columns first two columns with text and third one with url as there should be consistency in table action so that it can be generically implemented in different clients.

**Comment by mariobehling** [comment]
@AliAyub007 This number of displayed results should probably be implemented in the client and there could be a button "more" if there are a lot of entries.

**Comment by AliAyub007** [comment]
Yes I thought of it but when I tried there was limit to send data from client like I couldn't send more than 12 entries so that's why. However trying to figure it out in a way. Hope will do it. 👍

**Comment by uday96** [comment]
Table type reponses also have a count attribute now which tell the client how many entries must be shown and for the query `universities in germany` , count = -1 which means server is asking the client to show all entries. I dont think the client should handle this, updating the relevant skill for universities in germany type queries should fix this.
Or are we talking about the case when the server is asking the client to show all rows and the number of rows is high?

**Comment by hkedia321** [comment]
I think this can be closed for now since more number of results should be handled by the client side and give options like "more", etc.
