### ISSUE TITLE
Issue running susi server

### ISSUE THREAD

**Issue by vivekkiran** [fossasia/susi_server#31]
I am unable to run susi server, I have followed the procedures mentioned in the Readme. I have built it using gradle.

Here are the logs.
Viveks-MacBook-Pro:bin devenv$ ./start.sh
susi detected that you did not yet run the installation wizard.
It let's you setup an administrator account and a number of settings, but is not mandatory.
You can manually start it by running bin/installation.sh
starting susi
susi server failed to start. See data/loklag.log for details. Here are the last logs:
Error: Could not find or load main class org.loklak.SusiServer
Viveks-MacBook-Pro:bin devenv$

**Comment by vivekkiran** [comment]
@mariobehling @daminisatya Please help!

**Comment by Orbiter** [comment]
maybe a problem with the main branch. I just merged everything from development to main, please try again.

**Comment by dexta11** [comment]
https://raw.githubusercontent.com/fossasia/susi_server/2f8184b2ba1c1c7dc4c48f051aac3182bec0a5ef/conf/susi/susi_cognition_boilerplate.json.example

Save this file in your folder /conf/susi/ and you will be ready to go.

**Comment by Abhi2424shek** [comment]
@vivekkiran any updates?
