### ISSUE TITLE
Implementing new action type : playaudio

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#325]
**Expected Behaviour**
Alert clients to play different type of audios. These might be coming from a URL(URL encoded as JSON object) or  maybe present locally with the client itself. 

**Steps to reproduce it**
More research and discussions are required on this.

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
We already have implemendet `audio_play` and `video_play`.
