### ISSUE TITLE
implement new action type : set alarm

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#327]
**Expected Behaviour**
implement an action type which allows users to set alarms.

**Steps to reproduce it**
handle query at server and respond accordingly to clients.

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
Initially what we can do is that when the server receives a request, it is processes it and sends the response to the respective client making the request.
@Orbiter Are we also handling the case that when a user makes a call for alarm via web chat client, it also sets his alarm in android and iOS?

**Comment by DravitLochan** [comment]
Should it be implemented as rss type or other action types (where users can make skills using that action type)?

**Comment by Orbiter** [comment]
I dont't know how to explain. We discussed this in detail. If you believe a rss action type is an option here then you did not understand why we use actions and specific actions for the one and only purpose of that action only.

Hint: https://github.com/fossasia/susi_server/blob/development/src/ai/susi/mind/SusiAction.java#L49

**Comment by Orbiter** [comment]
this kind of actions become superfluous with timed actions, see https://github.com/fossasia/susi_linux/issues/521
