### ISSUE TITLE
Susi server not replying appropriately.

### ISSUE THREAD

**Issue by fatimarafiqui** [fossasia/susi_server#34]
Susi's replies are not apt to many questions. Sometimes it throws adult content like the one I have shown in the snap.

<img width="280" alt="screen shot 2016-12-04 at 17 19 55" src="https://cloud.githubusercontent.com/assets/13470643/20865986/0f40be94-ba47-11e6-9345-54d6aa0c8aeb.png">

**Comment by Orbiter** [comment]
well that answer comes from urbandictionary.
We had already many complaints about those results.
So I remove that rule: https://github.com/fossasia/susi_server/commit/da1f08f5b73c04812b67c90b389760fe4e01d3a4
