### ISSUE TITLE
Open Phimpme app when user ask for taking a picture or other similar command

### ISSUE THREAD

**Issue by pa1pal** [fossasia/susi_server#356]
**Actual Behaviour**

We would like to have a feature where Susi app open the [Phimpme Android app](https://github.com/fossasia/phimpme-android) (if installed), when User ask for _"Take a pic", "Take a picture", "I want to edit the image", "Open image editor"_ etc..

**Expected Behaviour**

Launch Phimpme app app in case of above User commands.

**Comment by DravitLochan** [comment]
We are in transit of implementing this on the server. Will follow  you up on the issue.

**Comment by pa1pal** [comment]
@DravitLochan sure.

**Comment by mariobehling** [comment]
Not directly related to the server project.
