### ISSUE TITLE
Add "Edit" link to Analyse skill

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#360]
On the input "Analyse" SUSI show "My previous skill is defined in...", please add an "edit" option in a line below the current answer as follows:

`You can help to improve this skill and [edit it in the code repository here](add the correct link here).`

![screenshot_2017-07-09-13-18-15](https://user-images.githubusercontent.com/1583873/27993357-e1de904e-64a9-11e7-8948-4442cff0b679.png)

**Comment by saurabhjn76** [comment]
I would like to work on this

**Comment by mariobehling** [comment]
@saurabhjn76 

The current result of the output is as below: Instead of "edit the code here" and then the link, the idea was that "edit the code here" is linkified. Please help to fix this.

<img width="337" alt="screen shot 2017-07-10 at 2 53 24 pm" src="https://user-images.githubusercontent.com/7692626/28011337-9c205fb6-657f-11e7-94fa-eab304e9a179.png">

**Comment by saurabhjn76** [comment]
@mariobehling the current PR linkifies the text, in web-client, it is working,
![image](https://user-images.githubusercontent.com/9781788/28130198-c04273ea-6753-11e7-95e7-5897a2f5a25c.png)

 for android, I have opened https://github.com/fossasia/susi_android/issues/834. @chiragw15  Please help in fixing it. thanks
