### ISSUE TITLE
Update eclipse installation doc

### ISSUE THREAD

**Issue by meriki** [fossasia/susi_server#362]
**Actual Behaviour**
The steps to install Susi on Eclipse IDE lists SusiServer.java under `org.loklak`. Also, the gradle build fails due to a git submodule dependency on transporter module.

**Expected Behaviour**
Change the path to the SusiServer.java file and add commands to fix the dependency issue.

**Steps to reproduce it**
Setup susi_server on an IDE like eclipse/intellij

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
Please close this issue if resolved!
