### ISSUE TITLE
Sometimes in case of rss action type susi provide result less than count.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_server#365]
**Actual Behaviour**

Number of result provided by susi is less then count in case of rss action type.

**Expected Behaviour**

Number of result and count should be same otherwise it will create problem in client

**Example**
query 'ffgh'

"data": [
      {
        "title": "Browse: Top Level Community Video",
        "description": "",
        "link": "https://archive.org/browse.php?collection=opensource_movies&field=creator",
        "0": "ffgh",
        "1": "ffgh",
        "timezoneOffset": "-330",
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "ffgh",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_etherpad_dream": "stock"
      },
      {
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "ffgh",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_etherpad_dream": "stock"
      },
      {
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "ffgh",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_etherpad_dream": "stock"
      },
     {
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "ffgh",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_etherpad_dream": "stock"
      },
      {
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "dog",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_etherpad_dream": "stock"
      },

actions": [
      {
        "type": "answer",
        "mood": "sabta",
        "expression": "I found this on the web:"
      },
      {
        "type": "rss",
        "title": "title",
        "description": "description",
        "link": "link",
        "count": 3
      }
    ],

**Comment by DravitLochan** [comment]
on  querying "ffgh",  
`
{
	"query": "ffgh",
	"count": 1,
	"client_id": "",
	"query_date": "",
	"answers": [{
		"data": [{
				"title": "Browse: Top Level Community Video",
				"description": "",
				"link": "https://archive.org/browse.php?collection=opensource_movies&field=creator",
				"0": "ffgh",
				"1": "ffgh",
				"timezoneOffset": "-330",
				"answer": "I found this on the web:",
				"skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
				"query": "ffgh",
				"skill": "/susi_server/conf/susi/en_0090_fail.json",
				"_etherpad_dream": "starquotes"
			},
			{
				"answer": "I found this on the web:",
				"skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
				"query": "brazil",
				"skill": "/susi_server/conf/susi/en_0090_fail.json",
				"_etherpad_dream": "starquotes"
			},
			{
				"answer": "I found this on the web:",
				"skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
				"query": "quote star trek",
				"skill": "/susi_server/conf/susi/en_0090_fail.json",
				"_etherpad_dream": "starquotes"
			},
			{
				"answer": "dreaming enabled for starquotes",
				"skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0001_foundation.txt",
				"query": "dream starquotes",
				"skill": "/susi_server/conf/susi/en_0001_foundation.txt",
				"_etherpad_dream": "starquotes"
			},
			{
				"answer": "I found this on the web:",
				"skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
				"query": "quote star trek",
				"skill": "/susi_server/conf/susi/en_0090_fail.json",
				"_etherpad_dream": "starquotes"
			}
		],
		"metadata": {
			"count": 5
		},
		"actions": [{
				"type": "answer",
				"mood": "sabta",
				"expression": "I found this on the web:"
			},
			{
				"type": "rss",
				"title": "title",
				"description": "description",
				"link": "link",
				"count": 3
			}
		],
		"skills": ["/susi_server/conf/susi/en_0090_fail.json"]
	}],
	"answer_date": "",
	"answer_time": 1596,
	"language": "en",
	"session": {
		"identity": {
			"type": "host",
			"name": "",
			"anonymous": true
		}
	}
}
`
this is the complete response. count present in "metadata" attribute denotes total elements in answers    ->data array. The count you are referring here denotes number of attributes of  valid RSS feed. These are title, description  and link. So please close this issue as server is sending proper and valid response every time.

**Comment by amitiwary999** [comment]
So how can we decided number of result we have to show in client. Like there is only 1 result for 'ffgh' but for 'god' 10 result.

**Comment by uday96** [comment]
@DravitLochan I think the `count` attribute in 
```
{
          "type": "rss",
          "title": "title",
          "description": "description",
          "link": "link",
          "count": 3
 }
```
Tells the number of results to display i.e `min(length(response.answers[0].data), count)` should be displayed from response.answers[0].data where `count` is response.answers[0].actions[1].count in this case

**Comment by amitiwary999** [comment]
@uday96 but problem is for some queries like 'ffgh' data is less then count.

**Comment by uday96** [comment]
@amitiwary999 Oh okay. As of now to handle it you can display `min(length(response.answers[0].data), count)` results then on the client side until its fixed on server side :+1:
