### ISSUE TITLE
Javadocs are no more published to gh-pages

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/susi_server#366]
### Description
The logic for publishing javadoc exists in the `.utility/push-docs-to-gh-pages.sh` script. Unfortunately, there seems to be some error due to which the javadoc's generated documentation content is not being published anymore.

Discussing with @pri22296  in https://github.com/fossasia/yaydoc/issues/255, it was found that 
> This is the last commit where javadocs are present: https://github.com/fossasia/susi_server/tree/71b465bca1dca9dbd8c2a38d015e9b93e98512d2

> This is the commit that lead to the removal of javadoc https://github.com/fossasia/susi_server/commit/279c0c1788042fc99306c719890fb84943a42e94

Comparing relative commits in gh-pages branch:  https://github.com/fossasia/susi_server/compare/71b465bca1dca9dbd8c2a38d015e9b93e98512d2...6258845a1351f442b85b84a578339918cf143420

**Comment by dynamitechetan** [comment]
I am working on implementing swagger for API documentation. Do we still need javadocs? 
@mariobehling @saurabhjn76 @DravitLochan  please give your views.
