### ISSUE TITLE
Reset Password directs to asksusi.com and does not reset password

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#371]
Reset Password directs to asksusi.com and does not reset password.

Expected: Reset password directs to accounts.susi.com, where the functionality is implemented.

![screenshot from 2017-07-13 21-46-05](https://user-images.githubusercontent.com/1583873/28184723-c2c2d4fe-6814-11e7-801a-9faca82a1d12.png)

**Comment by mariobehling** [comment]
@DravitLochan  The password reset still does not work.

**Comment by DravitLochan** [comment]
1. This code needs to be merged on the original server.
2. gh-pages branch is not updated. Updating right now.

**Comment by DravitLochan** [comment]
@mariobehling Please close this issue as it has been fixed now!
