### ISSUE TITLE
 Implement Yaydoc docs generation in susi_server

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/susi_server#380]
[Yaydoc](https://yaydoc.fossasia.org) is FOSSASIA's own automatic documentation generation and deployment project. At the crux of it, Yaydoc generates a documentation website using the markdown present in a project's repository and keeps the website in sync with the changes made in project's documentation.

The project has been under development since the start of GSoC 2017 and we believe that it can be brought into production. For that, we'd like to start with the susi_server project. The project requires a `.yaydoc.yml` configuration file at the project's root directory. Adding necessary information in the configuration file and registering the project at https://yaydoc.herokuapp.com/ will be enough to generate the documentation website.

**Comment by DravitLochan** [comment]
@imujjwal96 Does this requires admin login?

**Comment by imujjwal96** [comment]
Eventually, it will be required. Right now, the yaydoc team(@pri22296, @sch00lb0y  and I) are currently working on it and testing it. We will then send a PR with changes required for the docs generation.

**Comment by abishekvashok** [comment]
Wasn't this fixed @imujjwal96 @DravitLochan
