### ISSUE TITLE
Universal Build System, Platform Independent Setup Instructions and Repository Cleanup

### ISSUE THREAD

**Issue by vivekkiran** [fossasia/susi_server#39]
@mariobehling @daminisatya @Orbiter 
I am working on to migrate the whole project build from ant to gradle based solution completely which would simplify lot of things for environment setup. Instead of having separate setup instructions for Windows, Mac and Linux, we can have a universal system, which works on any environment with least setup, all the user needs is gradle and jdk, thats it...
then the user would need to run only two commands on any environment..
gradle build && gradle run
 and all the dependencies would also be resolved through maven which can be configured through gradle... which would further reduce the repository size.., where as the current solution has many jar files which are being referenced through gradle and ant build file...
and the jar files alone occupies at least 30mb.... and the setup instructions are also too fragmented and not very clear, after implementing this it would reduce the repository size, and also the builds will be platform independent and easy to set up.

I would be able to complete this task in a week or two if everything goes well...

**Comment by mariobehling** [comment]
Awesome! Keep it up!

**Comment by Orbiter** [comment]
@vivekkiran yes that is a good idea, please do that!
Question: how can we purge the legacy libraries from loklak (i.e. elasticsearch, lucene etc) which are not used here?

**Comment by vivekkiran** [comment]
@Orbiter I have purged all the legacy libraries, now the project has only the libraries which are necessary, there where around 75 libraries which were there and most of them are not being used anywhere I got it down to 31 libraries even in that some of them are not needed but they are referenced in the project so I am not removing them as of now since they may need some refactoring. And I am also done with gradle build and generating artifacts and javadocs, as of now everything seems to be working fine. I am currently working on "gradle run", which will take some time.

**Comment by vivekkiran** [comment]
@Orbiter I have purged all the legacy libraries, now the project has only the libraries which are necessary, there where around 75 libraries which were there and most of them are not being used anywhere I got it down to 31 libraries even in that some of them are not needed but they are referenced in the project so I am not removing them as of now since they may need some refactoring. And I am also done with gradle build and generating artifacts and javadocs, as of now everything seems to be working fine. I am currently working on "gradle run", which will take some time.

**Comment by vivekkiran** [comment]
@Orbiter @mariobehling there has been good progress and I am almost there, there is just 1 blocker I am having right now I need this file susi_cognition_boilerplate.json.example , normally it should have been in https://github.com/fossasia/susi_server/tree/development/conf/susi but it isn't there. Please Help!

**Comment by Orbiter** [comment]
ah, sorry, yes just commited that: https://github.com/fossasia/susi_server/commit/819a85d8c82e8cff13c838208323b0ed9bbf6985

**Comment by Abhi2424shek** [comment]
@vivekkiran I guess it's safe to close it, is it?
