### ISSUE TITLE
adding images to skills 

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#392]
In reference to issue #383, we need to add images in skill to build skill page in susi_skill_cms.
Please suggest ways to handle this.

One way is to store them in some folder at susi_skill_data, and mention the image url in each skill.

**Comment by saurabhjn76** [comment]
@Orbiter @mariobehling @dynamitechetan, please provide your views

**Comment by dynamitechetan** [comment]
I am working on this.
