### ISSUE TITLE
Modify change settings endpoint to batch update settings

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#399]
**Actual Behaviour**

The current endpoint for changing settings accepts only one key and value in one server call. But the client has multiple settings and calling the server every time for each setting is throwing an error - `Your request frequency is too high`.

**Expected Behaviour**

Have a method of updating multiple settings in a single server call

**Would you like to work on the issue?**

@saurabhjn76 Can you look at this?

**Comment by saurabhjn76** [comment]
sure :+1:

**Comment by uday96** [comment]
Closing via https://github.com/fossasia/susi_server/pull/404
