### ISSUE TITLE
Create new file on modifyskill.json if skill does not exists

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#427]

**Comment by mariobehling** [comment]
What is this issue about? Why is there no description? What is your workflow? Quickly open an issue and add code that you have done before? This does not make sense.

**Comment by dynamitechetan** [comment]
Sorry, I forgot to open the issue previously. It was a small change, so I made the issue just before opening a PR.
Sorry I will not repeat this.
