### ISSUE TITLE
Improve OpenStreetMap displays and output on Server and Clients

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_server#429]
The map features have some confusing way of display and text. Please fix the following:

* [ ] Expected: Singapore is a place in Asia with a population of ... Here is a map.
   * "Here is a map" should incorporate the link already. No need to show the link additionally.
   * Do not show the info on OpenStreetMap and info "OpenStreetMap is a..."
* [ ] Do not show "Link to an OpenStreetMap for your location." It is not needed. We already have the link above.

![screenshot_20170730-020304](https://user-images.githubusercontent.com/16978820/28748195-f17af38c-74ce-11e7-95f1-8ff022f7e308.png)

![screenshot_20170730-021021](https://user-images.githubusercontent.com/16978820/28748197-f17c8d3c-74ce-11e7-9afb-d08f03197b0d.png)

**Comment by chashmeetsingh** [comment]
@hpdang this needs to be handled on the server which requires removing the `anchor` action type and adding the link to the answer action. @dynamitechetan can you make a PR for the same?

**Comment by chiragw15** [comment]
@hpdang The link is already removed in PR #428. The deployment is not updated yet. So when the deployment is updated, the result will be like: 
Message 1. Singapore is a place with population of 123456.
Message 2. [Link to Open Street map of Singapore](https://github.com).
Message 3. [Map Image]

Is this structure fine or should we remove Message 2 completely and add link in Message 1 only.

**Comment by uday96** [comment]
Instead of only telling about the population on  "where is Singapore..".  it is better to answer : Singapore is a place in Asia. Is a country and a city bordering Malaysia or something similar. Will try to use location features to show the corresponding place. Will work on this :+1:
