### ISSUE TITLE
modify !description & !image, to make them refer a skill instead of an intent

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#430]
**Actual Behaviour**

Currently, !image and !description is for a particular intent. As mentioned in comments [https://github.com/fossasia/susi_skill_data/issues/254#issuecomment-318979499](https://github.com/fossasia/susi_skill_data/issues/254#issuecomment-318979499) it should refer to a skill.

**Expected Behaviour**
Use global attributes using notion "::".

**Would you like to work on the issue?**
yes

**Comment by Orbiter** [comment]
this is an important one because the development of the skills depend on it. The longer it takes to make this modification the more skills must be changed to use the correct metadata setup

**Comment by saurabhjn76** [comment]
@Orbiter, this issue has already been fixed via #431, and the new skill format has been added #432 .
