### ISSUE TITLE
Get Skill Meta data in the Skill listing end point

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/susi_server#456]
**Actual Behaviour**

Currently, the Browse Skill page uses end point `http://104.236.109.233:4000/cms/getSkillList.json` which gives only the name of the skill.

**Expected Behaviour**

Add skill meta data similar to endpoint `http://35.192.82.114/cms/getSkillMetadata.json` for populating skills in the BrowseSkill component to complete PR https://github.com/fossasia/susi_skill_cms/pull/184

**Comment by rishiraj824** [comment]
@saurabhjn76 @dynamitechetan Please give your inputs. Thanks!

**Comment by saurabhjn76** [comment]
@rishiraj824 I will add feedback details in getSkillMetadata endpoint, then it would give all the data needed to show on browse skill component.

**Comment by mariobehling** [comment]
@saurabhjn76 The skill info should also be in the endpoint of the skill listing including the image in order to portray all skills on the front page at once with a single API call.

**Comment by saurabhjn76** [comment]
@mariobehling ok I will make the required changes :+1:
