### ISSUE TITLE
Add Private API key

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_server#46]
@mariobehling Will you please run this command on your system to remove travis errors.

    travis encrypt $(heroku auth:token) --add deploy.api_key

This is a reason why travis build is failing.

**Comment by mariobehling** [comment]
@BrainBuzzer Thank you!

@Orbiter I think this would be rather you.

**Comment by Abhi2424shek** [comment]
@mariobehling it's been a while sir any updates

**Comment by Orbiter** [comment]
fixed in https://github.com/fossasia/susi_server/commit/32b42fd29c3fe6aadb888a04aa9903cf2ec6c62f
