### ISSUE TITLE
Modify README.rst to remove old use of `ant` to build.

### ISSUE THREAD

**Issue by mehuled** [fossasia/susi_server#464]
**Actual Behaviour**

Documentation suggests use of `ant` to build the susi_server locally.

**Expected Behaviour**

Documentation to suggest the use of `gradle` build to build the susi_server locally. 

**Steps to reproduce it**

Edit README.rst

**Would you like to work on the issue?**
Yes.

**Comment by rupav** [comment]
@mehuled Please close this issue, I think its been solved as per your merged pull request #465 :) .
