### ISSUE TITLE
Move API documentation to docs folder 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#471]
The API documentation is still on the site itself here http://api.susi.ai/api.html. Please move the documentation to the docs folder and link it from the Readme.md.

**Comment by uday96** [comment]
Will do this :+1:

**Comment by manishv123** [comment]
i want to solve this issue can anyone tell how to move documentation?Should i copy the documentation from the link and paste it to some.txt file in docs folder and provide link to that file from readme.md.

**Comment by manishv123** [comment]
please someone review this pull request and ask for further changes if needed.

**Comment by manishv123** [comment]
please review new pull request and merge if no changes are needed or suggest changes that are required
