### ISSUE TITLE
update account verification link

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#473]
**Actual Behaviour**
api.asksusi.ai is sent for account verification link.

**Expected Behaviour**
accounts should be used similar to forget password.

**Steps to reproduce it**
first Implement in accounts, then change link here accordingly.

**Would you like to work on the issue?**
Yes

**Comment by MasterSlicer** [comment]
I am a newbie at FOSSASIA. I would like to  work on this issue. Can i be guided through please?

**Comment by DravitLochan** [comment]
We have many projects related to SUSI. One of them is accounts.susi.ai. If you have already registered with SUSI, you might have received an email verification link. Clicking on the verification link, you would have been redirected to a link which has JSON data. This issue has to be in sync with accounts project. To fix this issue, First a route has to be generated in accounts.susi.ai project. When redirected to accounts.. You might have to extract the JSON data and show an appropriate message to user. It is good to see your interest in the project. First step would be to open an issue [here](https://github.com/fossasia/accounts.susi.ai/issues). I will guide you properly on the issue in accounts project. Please open an issue there. :)

**Comment by MasterSlicer** [comment]
I've opened the issue in the accounts.susi.ai 
```https://github.com/fossasia/accounts.susi.ai/issues/136```
