### ISSUE TITLE
Enable users to activate and deactivate a skill

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#482]
With more and more skills we might want to enable users to activate and deactivate skills similar to Amazon. Propose and implement this.

![screenshot from 2017-08-11 09-39-58](https://user-images.githubusercontent.com/1583873/29204758-25a38562-7e79-11e7-889b-6a7f54c9a13b.png)

**Comment by Orbiter** [comment]
I would suggest to make this possible using a metadata string like 
```
::active no
```
That should then be parsed in the skill parser and should cause to ignore the whole skill

To add or remove this marker, we would need a service which should add or remove this. This provides then an API endpoint which must be used in the web client.

**Comment by saurabhjn76** [comment]
@Orbiter But what if a user might want to enable one skill, but it is disabled for another user?

**Comment by mariobehling** [comment]
This feature is about enabling/disabling for one user, just like with Alexa. There are other use cases and group enabling/disabling possible, but this is out of scope of this issue.
