### ISSUE TITLE
Change categories to match other assistants

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#483]
**Keep the following categories**
* Problem Solving
* Shopping

**Add the following categories and put skills into the relevant category**
Business & Finance
Communication
Connected Car
Education and Reference
Food and Drink
Games, Trivia & Accessories
Health and Fitness
Lifestyle
Local
Movies and TV
Music and Audio
News
Novelty and Humour
Productivity
Shopping
Smart Home
Social
Sports
Travel and Transportation
Utilities
Weather

**Comment by Orbiter** [comment]
I would like to suggest to not use the ```&``` character here, it might cause huge problems when used as file name in the file system. Can we replace this with 'and'?

**Comment by madhavrathi** [comment]
Working on it.

**Comment by madhavrathi** [comment]
@mariobehling @Orbiter Please suggest in which category should I put skill of Small Talk (English-Standalone-aiml2susi.txt).
@mariobehling I have renamed the category Education and Reference to Knowledge as All the servlets in server take knowledge model as default, so we should keep the knowledge model.

**Comment by mariobehling** [comment]
> Please suggest in which category should I put AIML files of Small Talk (English-Standalone-aiml2susi.txt).

I don't know. Iterate to get things moving forward. Avoid adding blockers that depend on continuous input. Help to move the project forward by iterating faster.

**Comment by madhavrathi** [comment]
@mariobehling I have updated the PR to fix this. It is now open for review
Thanks
