### ISSUE TITLE
Implement version history

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#489]
In order to track changes of skills we need a version history of a skill implemented similarly to a wiki like in Wikipedia. Please implement a version page and a way to compare and go back in the version history.

**Comment by Orbiter** [comment]
This must be done using the /cms/getSkillHistory.json servlet which shows the complete commit history of one file. The user should then be able to pick two and get a diff or the user should be able to pick one and check out that one ... which could then be committed which creates a roll-back.

**Comment by dynamitechetan** [comment]
It is already completed. From Skills CMS users can browse different revisions of a skill and can roll back to a specific version.

**Comment by AnupKumarPanwar** [comment]
@dynamitechetan @Orbiter @mariobehling Should this issue be closed?

**Comment by akshatnitd** [comment]
Implemented alreaady
