### ISSUE TITLE
Redesign start page of server similar to other services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#490]
* Implement top bar same as web chat including the menu dropdown on the right
* Add footer same as on web chat overview page
* Change the following
   * "Software and Rules for Personal Assistants" -> "SUSI.AI API Server for Artificial Intelligence Personal Assistants, Robots, Help Desks and Chatbots"
   * "Chat with a Personal Assistant: Artificial Intelligence for Information Retrieval." -> "This server provides an output of intelligent answers in JSON format for SUSI.AI clients" 
* Change font and style to match web chat service
* Add .ico same as on other pages
* Take out "Nice? To get latest news about susi, follow @0rb1t3r. Help to spread the news: Tweet about this"

**Comment by isuruAb** [comment]
i will work on it.
