### ISSUE TITLE
Make APIs for flagging and reviewing skills

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#494]
Like in Wikipedia when someone creates a wrong page then some other contributor flags it and then deletes it. We should follow that approach only. If there is a wrong skill people can request it to delete and admins/ moderators can delete it. 
It should be done on CMS and the Server as well.

**Comment by harshvardhan-takawale** [comment]
Hi, I am new to open source development and would like to try working on this issue. Can I take this up?

**Comment by dynamitechetan** [comment]
same as https://github.com/fossasia/susi_server/issues/538.
