### ISSUE TITLE
Susi_skill_data should be pulled using java client

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#499]
In reference to #240 
Currently, Susi_skill_data is pulled with a cronjob every minute. For the auto deployment and kubernetes deployment, the pulling mechanism must be done using the java client.

**Comment by Orbiter** [comment]
The susi_server has a Caretaker class which contains a loop that runs as long as susi is running. There a call to DAO.pull(Git) must be done in a fixed frequency; the frequency must be set in the config file. Default should be one minute.

**Comment by Orbiter** [comment]
The Idea behind this frequent pull is, that several susi_server instances should be used at the same time and should be accessed with a fail-over load balancer. In a case where one susi_server may fail, is maintained or has a problem another susi_server takes over. Then all skills must be available in the other instance as well.
