### ISSUE TITLE
Implement full support/ make full use of Wikidata features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#5]
How can we use wikidata and its expanded features?

Useful links
- https://query.wikidata.org
- https://www.wikidata.org/w/api.php
- https://www.mediawiki.org/wiki/Wikidata_Toolkit

A sample site that is getting answers from Wikidata:
- https://askplatyp.us
- The code of askplatypus https://github.com/ProjetPP/

**Comment by shivenmian** [comment]
@mariobehling Wikidata is already being used in susi_server. :)

**Comment by mariobehling** [comment]
I am completely aware. We are not using all its features and full potential.

**Comment by mariobehling** [comment]
For adding Wikidata skills, please follow current documentation. This is possible now.
