### ISSUE TITLE
Use Couscous for Documentation

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_server#51]
Currently, documentation is built with jekyll which makes us hard to put the directory structure. There is a library on github called [Couscous ](https://github.com/CouscousPHP/Couscous) which is built specifically for documentation. I guess it would be good if we use it.

**Comment by AnaghHegde** [comment]
@BrainBuzzer Looks interesting can i work on this ?.

**Comment by Abhi2424shek** [comment]
Closing in favour of #69
