### ISSUE TITLE
Bulky Docker image for Kubernetes

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/susi_server#513]
The Docker images for Kubernetes is too large. This is mainly because of using Ubuntu as base image and having too many layers while build.

### Steps to reproduce -

1. Build the Kubernetes Docker image
2. Take a look at the images size

**Comment by AnshulMalik** [comment]
Hey, are you talking about [this](https://github.com/fossasia/susi_server/blob/development/Dockerfile) dockerfile?

**Comment by singhpratyush** [comment]
@AnshulMalik: No, it is this one - https://github.com/fossasia/susi_server/blob/development/kubernetes/images/Dockerfile.

**Comment by AnshulMalik** [comment]
Okay, I'll look into it :)

**Comment by imujjwal96** [comment]
the ubuntu image itself is a lot bloated. Try using other images.

**Comment by singhpratyush** [comment]
@AnshulMalik: This may be helpful - http://blog.fossasia.org/optimising-docker-images-for-loklak-server/.

**Comment by AnshulMalik** [comment]
That's good article

**Comment by abishekvashok** [comment]
@singhpratyush pls review #582
