### ISSUE TITLE
Ability to filter skills in specific order

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_server#517]
**Actual Behaviour**

since skills are not sorted users can't find skills quickly
- [ ] Ascending filter
- [ ] Descending filter
- [ ]  Any other filters on which we can order them? (Latest -> oldest) maybe?

**Expected Behaviour**

Skills should be sorted in ascending order

**Would you like to work on the issue?**

anyone can get it

**Comment by DravitLochan** [comment]
I'll implement it

**Comment by DravitLochan** [comment]
@isuruAb Please extend this issue for ascending and descending order. Give this choice to the user at client side.

**Comment by DravitLochan** [comment]
@sudheesh001 sounds good. Will add them. :+1:

**Comment by DravitLochan** [comment]
@isuruAb ascending and descending are done. Code clean up is left (Will send a PR today positively). You might want to start implementing this in the client, i.e. in skill_cms. 
The end point '/cms/getSkillList.json' will change in the following given way : 
http://api.susi.ai/cms/getSkillList.json?applyFilter=true&filter_name=ascending&filter_type=lexicographical
http://api.susi.ai/cms/getSkillList.json?applyFilter=true&filter_name=descending&filter_type=lexicographical
Now a boolean parameter for applyFilter with filter_name(ascending) and filter_type(descending) needs to be sent.
I suppose let us implement this in the following way : 
at first, there will be normal rendering of data (This will be unsorted). Give an option to user to apply filters like ascending, descending, recent and oldest. If futher filters are required, please do notify. 
Sorry it took some time to update.

**Comment by isuruAb** [comment]
@DravitLochan please check the above links , both of them are giving me same result set. Aft this is ready, I will open issues correspondingly  on  susi_skill_cms. 👍

**Comment by uday96** [comment]
Why aren't we sorting the data on client side and making a server call? We can save ajax calls if this is implemented on client side right?

**Comment by DravitLochan** [comment]
@isuruAb ascending and descending are done. There is no attribute for oldest - newest. Will open relevant issue for adding an attribute. Please analyse the response for once and implement a filter in skill cms. Cheers
