### ISSUE TITLE
Critical: Most of Susi Commands are not executing properly

### ISSUE THREAD

**Issue by samsruti** [fossasia/susi_server#53]
@mariobehling 
Expect the general commands, Twitter/Loklak, RSS Feeds, Events, Wordpress, Github, Instagram, Date/Time, Wikipedia, Quora are not executing properly. 
Here is the list of commands:
https://github.com/fossasia/susi_server/blob/master/docs/AskSUSI.md

**12:40 AM, Today     you** 
Hello
 **Susi 12:40 AM, Today**
Hi, I'm Susi
**12:40 AM, Today     you** 
 How many times did melaniatrump get 0 likes ?
 **Susi 12:41 AM, Today**
**12:41 AM, Today     you** 
What are the reddit articles about Loklak ?
 **Susi 12:41 AM, Today**
I don't know how to answer this. Here is a web search result:
**12:42 AM, Today     you** 
Susi, Where can I get updates of the event billets-europeade-2016-concert-de-musique-vocale-25592599153 ?
 **Susi 12:42 AM, Today**
I don't know how to answer this. Here is a web search result:
**12:43 AM, Today     you** 
Susi, Can I view the articles from wordpress blog from http://ishothim.com/
 **Susi 12:43 AM, Today**
I don't know how to answer this. Here is a web search result:
**12:43 AM, Today     you** 
Can you find mariobehling on Github and give me information ?
 **Susi 12:43 AM, Today**
I don't know how to answer this. Here is a web search result:

Answers are not coming as expected.

**Comment by smokingwheels** [comment]
I am not really to sure about this problem yet, but a clue today I uncovered a minor problem, if you perform a wget to the API like below it throws a spanner in the works for History of the results in the output.

wget -T 1 --no-cookies --no-cache "http://localhost:4000/susi/chat.json?q=something with space URL"
wget -T 1 --referer=http://10.0.0.10 --no-cookies --no-cache "http://localhost:4000/susi/chat.json?q=a to  b also including a space"

I started the day with something like this.
wget "http://localhost:4000/susi/chat.json?q=Normal output"

[Info on wget, there are many others](https://www.gnu.org/software/wget/manual/wget.html)

Note: I did not have my Susi Server open to the internet.

**Comment by Orbiter** [comment]
most problems have been fixed. Questions that Susi cannot answer must be implemented as Susi Skill.
Please watch https://www.youtube.com/watch?v=EtKsjTR4ANI and https://www.youtube.com/watch?v=7U__K8yy1iY as an explanation on how to do that.

Text resources are here:

The Susi Skill language:
https://github.com/fossasia/susi_server/blob/development/docs/susi_skill_development_tutorial.md

How to deploy them permanently: 
https://github.com/fossasia/susi_server/blob/development/docs/submitting_skills_to_git.md
