### ISSUE TITLE
Make an endpoint to store images 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_server#537]
**Actual Behaviour**

There is no end point for store images on server.

**Expected Behaviour**

There should be an endpoint to store 

- custom theme background images.
- conversation images
- profile pictures

**Would you like to work on the issue?**

@DravitLochan

**Comment by DravitLochan** [comment]
Yes. Will do this.

**Comment by Orbiter** [comment]
Thats implemented in the Skill CMS Endpoint
