### ISSUE TITLE
modify alarm action type 

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#539]
alarm action type is present in console bang type. Separate bang type should be used.

**Comment by aviral1701** [comment]
I would like to work on this one.Please provide some help to began on the same.

**Comment by Orbiter** [comment]
Alarm actions must use the `timer_set` action.

Like:
```
set alarm to *
!console:alarm set to $1$
{"actions":[
{"type":"timer_set", "time":"`__convertDate2Time $1$`"}
]}
eol
```

where `__convertDate2Time` must be another intent which calculates any given date expression into a linux time.

**Comment by Orbiter** [comment]
timer_set actions become superfluous with timed actions, see: https://github.com/fossasia/susi_linux/issues/521
