### ISSUE TITLE
Return commit info in getFileAtCommitID

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#541]
**Actual Behaviour**

getFileAtCommitID doesn't return commit info like author name and commit date so in skill cms we need to make another call to getSkillHistory to get the required data

**Expected Behaviour**

Return commit info like author name and date in getFileAtCommitID to reduce the number of ajax calls made in skill cms

**Would you like to work on the issue?**

@dynamitechetan Please take a look

**Comment by rishiraj824** [comment]
@uday96 Definitely need this for PR https://github.com/fossasia/susi_skill_cms/pull/276 :+1:

**Comment by dynamitechetan** [comment]
@rishiraj824 getting the image would be challenging as image name and the original image might differ. Suppose in commit1 the image name was xyz.png but in commit 2 image name is abc.png. The server returns you the image name of commit1 which is xyz.png but now the image is present at abc.png so the image will be not found.

**Comment by rishiraj824** [comment]
Yes agreed, so in that case showing the latest image will be the solution here. What do you think @dynamitechetan ?

**Comment by dynamitechetan** [comment]
Yes.
