### ISSUE TITLE
Shift Current Deployment to Google Cloud

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_server#545]
We need to shift the deployment of the server to Google Cloud from the current platform. The major issue while shifting is that we have to make sure our current data is not erased. 
Propose and implement a way to shift the server to Google Cloud without deleting our current data and make sure everything works fine after deployment. 
Also, add the complete process of shifting to the documentation. 

@niranjan94 need your help here.

**Comment by Orbiter** [comment]
"current data" is the content of the settings and the log inside data. Parts of that should be considered 'private' since it contains log-in information for emails accounts.
