### ISSUE TITLE
Implement IFTTT for SUSI AI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#555]
How can we implement IFTTT for SUSI AI similar to Alexa?

Compare here: https://ifttt.com/amazon_alexa

**Comment by ParthS007** [comment]
@mariobehling  Can you please explain in detail . I am interested to work on it .

**Comment by DravitLochan** [comment]
@ParthS007 IFTTT is an If This Then That is a free web-based service to create chains of simple conditional statements, called applets. [more here](https://en.wikipedia.org/wiki/IFTTT). 
Please solve this and open a relevant PR. 👍

**Comment by ParthS007** [comment]
@DravitLochan  Can you please tell what type of applets and recipe is required?
