### ISSUE TITLE
Fix docs on mobile

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_server#56]
Currently, documentation part is created with semantic ui. The secondary menu which is a list is not responsive on mobile. So on mobile, that menu should be hidden showing a sidebar menu as like in semantic ui docs.

![](http://i.imgur.com/BukU8t3.png)

Reference: http://semantic-ui.com/modules/sidebar.html
http://semantic-ui.com/collections/grid.html -- check responsive grid part which explains how to show items mobile screen only while hiding on lage screen device.

**Comment by mariobehling** [comment]
We will develop guidelines for the UI in the respective sub projects. Therefore I am closing this. Thanks.
