### ISSUE TITLE
Error while building environment

### ISSUE THREAD

**Issue by nanspro** [fossasia/susi_server#562]
**Actual Behaviour**

Errors showing when i run ./gradlew build

**Expected Behaviour**
Build environment by installing dependancies

![workspace 1_004](https://user-images.githubusercontent.com/24641089/30239134-8b334c9e-9573-11e7-981b-f77c2d264e41.png)

**Comment by yashLadha** [comment]
It is not able to download the dependencies. Check that your network allows that.

**Comment by yukiisbored** [comment]
It looks like your connection fails to connect to services.gradle.org. Please check your Internet connection.

**Comment by mariobehling** [comment]
I guess this is not an issue. Closing it therefore. Please re-open if needed.
