### ISSUE TITLE
API Endpoint to get URL of the Skills Repository

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#564]
In CMS we are using 
>     let image = 'https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/
Instead of hard coding this we need to send it from the server.

**Would you like to work on the issue?**
Yes. I am working on this issue.

**Comment by mariobehling** [comment]
Actually SUSI.AI runs its own git. This git is automatically synced with Github. Instead of getting the URL from the Github repo, please implement an API endpoint to get the data directly from the SUSI.AI Git.
