### ISSUE TITLE
Privacy Issue: History of anonymous users displayed according to IP

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#567]
The history conversation with SUSI.AI is displayed according to the IP. If a user suddenly gets an IP that someone else used before is seems that the history is available to the new user then. Also, users in the same network get the same history and questions/answers of another computer appear.

Expected:
* Users should only see their own history.

Ideas: History of user chat should be tied to
* IP, Mac Address, Browser ID and set by a cookie

**Comment by Orbiter** [comment]
right now not only the IP is used for the computation of anonymous accounts.
The IP is salted with a hash computed by AbstractAPIHandler.getRequestHeaderSalt which combines User-Agent, Accept-Encoding and Accept-Language.

However, this salt can also be not enough. To create true identity salts we also can add a personal cookie. Clients without a cookie for anonymous authentication must create such.

**Comment by abishekvashok** [comment]
Yes a cookie will prove to be a good idea @Orbiter can I implement it?
