### ISSUE TITLE
Implement system skills and activate skills and deactivate skills for user accounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#570]
Certain skills are necessary to run SUSI.AI and should be considered as system skills. For other skills it should be possible to activate or deactivate them similar to Alexa. Please implement an API endpoint to activate or deactivate skills.

**Comment by yashLadha** [comment]
I would like to work upon this @mariobehling

**Comment by saurabhjn76** [comment]
@yashLadha go on 👍

**Comment by mariobehling** [comment]
We probably follow the Google model now. Therefore closing this.
