### ISSUE TITLE
Search a skill

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#574]
**Actual Behaviour**
User has to browse through all the skills to find one. 

**Expected Behaviour**
If relevant skill is found, return it as a json array 

**Steps to reproduce it**
Add tags attribute to skills. This will help search a skill.

**Would you like to work on the issue?**

Yes

**Comment by souravsingh** [comment]
@DravitLochan I am interested in working on this. How do I start?

**Comment by DravitLochan** [comment]
@souravsingh Good to see you are interested in this. The first step for this issue is to add a new attribute in metadata, i.e. "tags". I've opened an issue #585 and opened a pr #586 
Next steps would be to add relevant tags once #586 gets merged. Can you take care of the fact that relevant tags are added? Thanks

**Comment by Hsankesara** [comment]
Hey @DravitLochan, can I work on this issue?

**Comment by DravitLochan** [comment]
@Hsankesara I was half way done but no problem. Its good to see new contributors. Please provide detailed steps that you will follow.

**Comment by mariobehling** [comment]
Please follow up in the Skills CMS.
