### ISSUE TITLE
bug on getting a meme

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#579]
**Actual Behaviour**

When asked for a meme,it shows the path of the file

**Expected Behaviour**

It should show only the meme

**Steps to reproduce it**

ask susi to get me a meme

**Screenshots of the issue**
![issue](https://user-images.githubusercontent.com/29942790/30929960-c9d9c068-a3dd-11e7-88fc-d4c1573a9dd0.png)

**Would you like to work on the issue?**

Please assign it to someone

**Comment by felipewmartins** [comment]
Hi @mariobehling I would like to work on this activity.

**Comment by devsks** [comment]
I think this is  a good opportunity for me to start FOSS @mariobehling @stealthanthrax . I would like to get started by fixing this bug.

**Comment by DravitLochan** [comment]
@devsks @felipewmartins @stealthanthrax This is not an issue. Now we have a proper skill cms running on https://skills.susi.ai/
Please change it there. @mariobehling Please close this issue.
