### ISSUE TITLE
Enhance documentation on dev.susi.ai

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#580]
* Move yml to dedicated meta dev site repository at https://github.com/fossasia/dev.susi.ai
* Use Readme of the meta repo for the start page
* Rename "sub projects" to "Components"
* Start Page https://dev.susi.ai : Instead of showing the Readme of the SUSI Server and below the components -> Only show the list of all components including the SUSI.AI Server and move the SUSI.AI server to https://dev.susi.ai/susi_server
* On components (subproject pages) "Table of Contents" links back to http://dev.susi.ai. Expected: Direct back to the start page from the top logo (Don't hard-code it. We want it to work on other repos as well. Generate it to the domain in the yml file). 
* On pages don't make "Table of Contents" text into a link
![screenshot from 2017-09-29 00-21-28](https://user-images.githubusercontent.com/1583873/30992908-73b3e54a-a4ac-11e7-88b7-91a121cd9612.png)
* In the design of the page delete the top left menu. Expected: Follow the design of "chat.susi.ai" and add the same menu icon on the top right (same as on chat.susi.ai with the same links).
![screenshot from 2017-09-29 00-28-40](https://user-images.githubusercontent.com/1583873/30993054-4401726c-a4ad-11e7-854f-0fc8d57f5c30.png)

**Links**
* https://github.com/fossasia/sphinx_susiai_theme
* https://github.com/fossasia/yaydoc

**Comment by gabru-md** [comment]
@mariobehling where is the file that needs to be changed ? 
Can you provide me with the link so that i can change it ?

**Comment by ParthS007** [comment]
I want to work on this @mariobehling.

**Comment by ParthS007** [comment]
@mariobehling will I have to move every yml file to dev repo?

**Comment by Minkush-sopho** [comment]
@mariobehling can I work on this issue?

**Comment by KrUciFieR-Jr** [comment]
Can I work on this issue ?
