### ISSUE TITLE
add tags in meta data

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#585]
**Actual Behaviour**
Currently, there is no option to search for a skill. To allow the users to search for a skill, add relevant tags in the tags field.

**Expected Behaviour**
User should be able to search a skill on the basis of tags a skill has.

**Steps to reproduce it**
add "tags" field in the meta data.

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
@mariobehling @Orbiter @sudheesh001 Please add "hacktoberfest" label to this issue. :D

**Comment by Orbiter** [comment]
we should have some guidelines what kind of tags should be used. The danger is that people just use too many different words for the same topics. How can we handle that?

**Comment by DravitLochan** [comment]
@Orbiter Only approach I see is that moderators approve the tags. is it feasible?
