### ISSUE TITLE
Return "All" skills from all categories

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_server#587]
**Actual Behaviour**
Currently https://api.susi.ai/cms/getSkillList.json? returns skills of "Knowledge" category

**Expected Behaviour**
https://api.susi.ai/cms/getSkillList.json? must return all the skills (of all category types) when no filter is applied.

**Would you like to work on the issue?**
No. I am working on the webchat to implement "All" category to list all skills https://github.com/fossasia/susi_skill_cms/issues/333

**Comment by dynamitechetan** [comment]
If anyone is not working on this I can try.

**Comment by tstreamDOTh** [comment]
@dynamitechetan Nobody has claimed it. Can you work on it?

**Comment by r0b1nz** [comment]
So in **/cms/getSkillList.json**
**"group": "Knowledge",**
Should be -> **_"group": ""_** ?

I'll take this one.

**Comment by DravitLochan** [comment]
This issue has been pending for quite a long now. Working on this.

**Comment by AnupKumarPanwar** [comment]
I think there has been no progress towards solving this issue. So I would like to solve it.
