### ISSUE TITLE
Dockerfile: Use Alpine instead of Ubuntu

### ISSUE THREAD

**Issue by yukiisbored** [fossasia/susi_server#590]
By using Alpine instead of Ubuntu, we can decrease the image size exponentially due to Alpine's commitment to keep things small and excluding the unnecessary stuff.

**Comment by chiragw15** [comment]
Similar issue #513

**Comment by yukiisbored** [comment]
Closing this, marking it as dupe of https://github.com/fossasia/susi_server/issues/513
