### ISSUE TITLE
API to edit user's email

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#592]
**Actual Behaviour**

Currently, there isn't any way to change the email of a user.

**Expected Behaviour**

An API exposed, where user can change the email id. It needs to done, keeping in mind the requirements of fossasia/chat.susi.ai#839

The issue can be assigned to someone else.

**Comment by DravitLochan** [comment]
@akshatnitd Please edit the issue accordingly

**Comment by DravitLochan** [comment]
ok. I'll work on this. @Orbiter @mariobehling Does this really needs to be implemented?

**Comment by akshatnitd** [comment]
SInce, no acivity. I would like to work on it.

@Orbiter @mariobehling I would like to propose an approach. We can assign an id as a primary key to each user. It can be an integer. And then, email can be changed thereafter in the accounting model. But, many other endpoints need to be changed accordingly. Also, the existing data file should be modified accordingly. Should I go ahead with it?

**Comment by akshatnitd** [comment]
For implementing email change feature, we need to change the authentication.json, authorization.json, accounting.json files on the server and change the id for existing users. How shall we go about doing it?

**Comment by Orbiter** [comment]
I admit that identifying the user with the email address was a bad decision. Yes a random-like hash would be better.
As I remember, we have identifiers which are prefixed with "email:" to identify that the user id is an email. We could still follow that schema and replace the email identifier with another id like "id:<hash>". Then the original email address must be stored as well. Storage would take place only in one file: authentication ("who is the user"). To make it possible that email addresses within id-Objects are searchable, they would have to be indexed. That requires that the JsonTray Class would have to provide that. We could introduce a "@index" object which contains all searchable items there. We would also have to add a "user" object which must contain an array of user identifications which again would contain email addresses and such. We should also consider to also store old email addresses together with the attribute "deleted". Or should we actually delete old email addresses?

**Comment by mariobehling** [comment]
> Or should we actually delete old email addresses?

We should store those emails in case an account gets hacked this info is important to be able to reset an account in future.

**Comment by mariobehling** [comment]
I suggest an ID number. Please implement this as a unique identifier.

**Comment by mariobehling** [comment]
Related to https://github.com/fossasia/susi_server/issues/837

**Comment by mariobehling** [comment]
@akshatnitd As the UID is implemented please follow up.

**Comment by akshatnitd** [comment]
@Orbiter Can you please guide me on how shall I go about implementing it ?
