### ISSUE TITLE
Web search type queries not working

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_server#593]
**Actual Behaviour**

SUSI web search type response is not working.

**Expected Behaviour**
Return valid response for web search type queries.

**Steps to reproduce it**
Try searching fossasia :- https://api.susi.ai/susi/chat.json?q=fossasia
It will return `500 error` when it should return some valid response.

**Screenshots of the issue**

![500err](https://user-images.githubusercontent.com/20766601/31239894-5ab9e042-aa1c-11e7-8d0c-f4754a67c1b1.png)

**Would you like to work on the issue?**
No.

**Comment by RaiVaibhav** [comment]
![screenshot from 2017-10-06 00-58-35](https://user-images.githubusercontent.com/22278438/31248491-92707aae-aa31-11e7-9c7b-b4b1363648bd.png)
@zamhaq  Its working fine

**Comment by zamhaq** [comment]
@RaiVaibhav I think it just started working. However, the response is not valid `web search`.

**Comment by RaiVaibhav** [comment]
@zamhaq but it is returning JSON Data

**Comment by zamhaq** [comment]
@RaiVaibhav yes JSON data, but it does not contain valid `answer` and `action`, so this cannot be used on the client.

**Comment by Orbiter** [comment]
sorry for this, but that is caused by me as I removed the web search intents for the fail-case. That is obviously a bad thing to do. We just need better search results.
@mariobehling back with YaCy results, or even (!) yacygrid or which solution would be preferable?

**Comment by RaiVaibhav** [comment]
@zamhaq I get that 👍

**Comment by AnupKumarPanwar** [comment]
@Orbiter even the chat room keeps on showing replying animation for ever, for such input query.

![image](https://user-images.githubusercontent.com/10573038/36961705-8aefe762-2072-11e8-97ac-dc847490e7ef.png)
