### ISSUE TITLE
redirect user to new accounts site

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_server#596]
**Actual Behaviour**
currently on clicking accounts, user is redirected to https://api.susi.ai/apps/applist/index.html

**Expected Behaviour**
User should be redirected to https://accounts.susi.ai/

**Would you like to work on the issue?**
Yes

**Comment by pushkyn** [comment]
@DravitLochan I'd like to help with this issue. Need change the link for the "Account" top menu item, right?

**Comment by DravitLochan** [comment]
@pushkyn Please open a relevant pr.
