### ISSUE TITLE
Add a favicon to gh-page

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_server#599]
**Actual Behaviour**

The page currently has no favicon.

**Expected Behaviour**

It needs to have favicon

**Would you like to work on the issue?**

- [x] I'll do this

**Comment by lapmid** [comment]
@anshumanv  have you done this ??

**Comment by anshumanv** [comment]
@lapmid fixed in #600

**Comment by lapmid** [comment]
why this is open then #599 should be closed then

**Comment by anshumanv** [comment]
Waiting for a maintainer to merge it.
