### ISSUE TITLE
Clean up Readme file and take out features that were separated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#6]
Susi was split from loklak. Currently we have a lot of info that came from loklak. Please take out text that is related to loklak rather than susi, e.g. How do I analyze data acquired by Susi. (Are we still following elasticsearch's approach here?)

**Comment by AnaghHegde** [comment]
@mariobehling Can i work on this ?.I am new here done with my setup.

**Comment by Abhi2424shek** [comment]
@AnaghHegde go forward pls :)

**Comment by AnaghHegde** [comment]
@Abhi2424shek @mariobehling The readme files contains some links of dev.loklak.org/* . Can you guys please help me with the proper links. So that i can replace it with the new one?

**Comment by tabesin** [comment]
Remaining loklak references in the code base. [loklak.txt](https://github.com/fossasia/susi_server/files/932299/loklak.txt)

**Comment by mariobehling** [comment]
Remaining items.

app.json:	"logo": "https://raw.githubusercontent.com/loklak/loklak_server/master/html/images/loklak_anonymous.png",
app.json:	"website": "http://loklak.org",
app.json:	"repository": "https://github.com/loklak/loklak_server.git",
app.json:	"image": "mariobehling/loklak",
app.json:		"BUILDPACK_URL": "https://github.com/loklak/heroku_buildpack_ant_loklak.git"
docker-cloud.yml:  name: "loklak"
docker-cloud.yml:  image: mariobehling/loklak
docker-compose.yml:  name: "loklak"
Dockerfile:# hack until loklak support no-daemon
Dockerfile:# start loklak
manifest.yml:  buildpack: "https://github.com/loklak/bluemix_buildpack_ant_loklak.git"
manifest.yml:  image: "mariobehling/loklak"
manifest.yml:  logo: "https://raw.githubusercontent.com/loklak/loklak_server/master/html/images/loklak_anonymous.png"
manifest.yml:  repository: "https://github.com/loklak/loklak_server.git"
manifest.yml:  website: "http://loklak.org"
README.md:[![Docker Pulls](https://img.shields.io/docker/pulls/mariobehling/loklak.svg?maxAge=2592000?style=flat-square)](https://hub.docker.com/r/mariobehling/loklak/)
README.md:Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/loklak
README.md:Hey, this is the tool for that! Just put http://loklak.org/api/search.rss?q=%23susi into your rss reader. Oh wait.. you will get a lot of information about tasty Cambodian food with that as well. Alternatively you may also read the authors timeline using http://loklak.org/api/search.rss?q=0rb1t3r or just follow @0rb1t3r (that's a zero after the at sign)
README.md:Articles and tutorials are also on our blog at http://blog.loklak.net.
README.rst:https://groups.google.com/forum/#!forum/loklak
README.rst:http://loklak.org/api/search.rss?q=%23susi into your rss reader. Oh
README.rst:http://loklak.org/api/search.rss?q=0rb1t3r or just follow @0rb1t3r
README.rst:Articles and tutorials are also on our blog at http://blog.loklak.net.
README.rst:.. |Docker Pulls| image:: https://img.shields.io/docker/pulls/mariobehling/loklak.svg?maxAge=2592000?style=flat-square
README.rst:   :target: https://hub.docker.com/r/mariobehling/loklak/
scalingo.json:	"logo": "https://raw.githubusercontent.com/loklak/loklak_server/master/html/images/loklak_anonymous.png",
scalingo.json:	"website": "http://loklak.org",
scalingo.json:	"repository": "https://github.com/loklak/loklak_server.git",
scalingo.json:	"image": "mariobehling/loklak",
scalingo.json:			"value": "https://github.com/loklak/heroku_buildpack_ant_loklak.git"

**Comment by mariobehling** [comment]
Closing this issue. Following up here: https://github.com/fossasia/susi_server/issues/124
