### ISSUE TITLE
"use strict"; should be used in installation.js before line 23.

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/susi_server#606]
**Actual Behaviour**

Function is executing in normal mode

**Expected Behaviour**

It should execute in strict mode.

**Steps to reproduce it**

Add `"use strict";`

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Yes

**Comment by manishv123** [comment]
i want to work on this issue.
