### ISSUE TITLE
XDG messaging api compatibility

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_server#607]
**Actual Behaviour**

As we support multiple clients some hardware clients suggest "local actions" (just think of the SIRI.API) as a great way of improving user experience. The idea is to streamline that by supporting standardised messaging between clients and servers to benefit from the wide experiences made in desktop notifications design.

**Expected Behaviour**

Try to support the XDG desktop notifications api as a subset for the communications with the client
https://developer.gnome.org/notification-spec/

**Comment by starlord1311** [comment]
i would like to work on this. can i? @tabesin
