### ISSUE TITLE
[improvement] Driven to micro-service architecture

### ISSUE THREAD

**Issue by DengYiping** [fossasia/susi_server#610]
Scalability is essential for susi.ai, but current architecture is not scalable at all. 
Even if we use docker, the data is kept within the container.  If one part fails, all the parts will fail immediately.
Micro-service architecture will allow us to utilize the scalability features in cloud platform. 

The general idea is to split susi_server into different part:
1. docker data container: running elastic search, store user data and crawled data. Elastic search should be interconnected using docker network. (this part is not stateless)
2. docker main container: just connects to the docker data container(or login service) and serve the user(this part is stateless)
3. docker login service container: manage for login, logout, check if a user is logined. (this part is also stateless)
4. load balancer: balance the load, might check if it is logined. (also stateless)

Spinning up and down 2. 3. 4. should be straight forward, while spinning up the data container is a bit problematic. Once spinned up, we need to create some rules for it to scale down.

**Comment by mariobehling** [comment]
Good idea. Due to current resources we cannot implement this right now.
