### ISSUE TITLE
Add Contributing Guidelines and Code of Conduct

### ISSUE THREAD

**Issue by armen-gabrielyan** [fossasia/susi_server#615]
**Actual Behaviour**

**Expected Behaviour**

I think these documents will be helpful for the project.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

YES

**Comment by Mandeepsinghchadha** [comment]
hii.....i am new to his organisation and this project can you kindly guide me how to get started with the issues...thanks in advance

**Comment by ArmenGabrielyan16** [comment]
@Mandeepsinghchadha Please write your questions in this channel: https://gitter.im/fossasia/susi_server
