### ISSUE TITLE
To be able to login through facebook SDK on chromebot and chat.susi.ai

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#617]
**Actual Behaviour**

Only being able to log in through susi server

**Expected Behaviour**

To be able to login through facebook sdk

**Would you like to work on the issue?**

Yes, but I only know webd and want to use seperate facebook sdk for chromebot and web app

**Comment by stealthanthrax** [comment]
Mentors, will this be a correct way to solve this issue?

**Comment by stealthanthrax** [comment]
@Orbiter ,can I write the script directly in chromebot?

**Comment by hkedia321** [comment]
This can be implemented on server and accounts first, and then on client side. https://github.com/fossasia/susi_server/issues/625
