### ISSUE TITLE
Unable to build with Java 9

### ISSUE THREAD

**Issue by yashLadha** [fossasia/susi_server#618]
**Actual Behaviour**

Error while building the setup.

**Expected Behaviour**
Build should be successfull

**Steps to reproduce it**

Install with java 9 environment.

**LogCat for the issue**

Could not determine java version from '9.0.1'.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/18033231/33802832-c607ef48-dda6-11e7-892c-cbda955f17fc.png)

**Comment by abishekvashok** [comment]
@yashLadha update grade to the latest rc version.

**Comment by yashLadha** [comment]
But i executed the script that is mentioned in the documentation. May be changes needs to be done in that @abishekvashok

**Comment by abishekvashok** [comment]
@yashLadha try updaitng the gradle version in the repo or degrading your java

**Comment by yashLadha** [comment]
I have degraded the java version but the tests are failing so it is not able to build @abishekvashok :sweat_smile:

**Comment by Orbiter** [comment]
not a bug - we are using java 8
