### ISSUE TITLE
Create Desktop app for Susi with Electron

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_server#62]
Electron is nice library in order to develop the native web apps. I guess there should be a app for susi for desktop. I would like to work on it. Can anyone create a new repo for the app? @mariobehling @daminisatya @jig08 @Orbiter

**Comment by mariobehling** [comment]
Great! https://github.com/fossasia/susi_desktop

**Comment by ankitrgadiya** [comment]
@BrainBuzzer I'm also looking forward to learn about electron, If you can add a basic app to repo I can help with it.

**Comment by ankitrgadiya** [comment]
@BrainBuzzer @mariobehling created basic app. [PR](https://github.com/fossasia/susi_desktop/pull/1)
