### ISSUE TITLE
Build Failed , JDK 9.0.1, MAC OX SIERRA

### ISSUE THREAD

**Issue by akhileshPandey16** [fossasia/susi_server#620]
**Actual Behaviour**

Build does not complete after downloading has finished in the terminal, 
Susi running itself in the CHROME browser "http://127.0.0.1:4000/" when I tried to run it via terminal command bin/start.sh

**Expected Behaviour**

I expected the build to complete successfully

**Steps to reproduce it**

Install JDK 9 and try to build it on a Mac that needs to download the Gradle bin support file.

**LogCat for the issue**
> Task :test

api.external.BahnTest > testConnection FAILED
    java.lang.NullPointerException at BahnTest.java:16

api.external.DeliverooTest > testAPI FAILED
    java.lang.AssertionError at DeliverooTest.java:30

api.external.DeliverooTest > testDemo FAILED
    java.lang.AssertionError at DeliverooTest.java:38

14 tests completed, 3 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/Akhilesh/susi_server/build/reports/tests/test/index.html
Provide logs for the crash here

**Screenshots of the issue**

<img width="1440" alt="screen shot 2017-12-12 at 12 19 23 pm" src="https://user-images.githubusercontent.com/33291758/33871327-08082d3a-df38-11e7-97fd-de1ed470a04d.png">

**Would you like to work on the issue?**

I am new here and would be glad to help out, I might need some support getting started.

**Comment by akhileshPandey16** [comment]
<img width="765" alt="screen shot 2017-12-12 at 12 33 36 pm" src="https://user-images.githubusercontent.com/33291758/33871487-b51d944c-df38-11e7-8c58-ff68d666925f.png">
THIS is the Corresponding test report.

**Comment by starlord1311** [comment]
I am new here and would be glad to help out, I might need some support getting started.  @akhileshPandey16

**Comment by starlord1311** [comment]
can you tell what i am supposed to do @akhileshPandey16

**Comment by akhileshPandey16** [comment]
Sorry, I did not get what you meant, care to explain?
Thank You @starlord1311

**Comment by starlord1311** [comment]
@akhileshPandey16 to clear this issue can you tell what i am supposed to do? as i didnt get the issue properly

**Comment by akhileshPandey16** [comment]
Are you new Here @starlord1311?
<img width="846" alt="screen shot 2017-12-20 at 6 38 39 pm" src="https://user-images.githubusercontent.com/33291758/34208601-0b27036e-e5b5-11e7-814d-cbebc6c5b56e.png">
 
Because this is what you said.
So are you new here and need help getting started?
What's your Background?

**Comment by akhileshPandey16** [comment]
@starlord1311 have you ever contributed here before?
