### ISSUE TITLE
Running start.sh twice kills the service

### ISSUE THREAD

**Issue by harsh-98** [fossasia/susi_server#621]
**Actual Behaviour**

running start.sh twice kills the service 

**Expected Behaviour**

If the service is already running, it should everytime say  --

`Server is already running, please stop it and then start`
if the service hasn't stopped yet.

**Steps to reproduce it**

Run the start.sh twice and the service will be stopped.

**Would you like to work on the issue?**

Yes

**Comment by marvin08** [comment]
@harsh-98 I think everything is working fine as I am not able to reproduce this issue.

![screenshot from 2017-12-16 03 23 20](https://user-images.githubusercontent.com/28600022/34062010-86b51ab4-e210-11e7-9154-ce791bf8b1b0.png)

**Comment by harsh-98** [comment]
@marvin08 running twice kills the service since in preload.sh the logic for checking whether the service is alive kills it. Therefore after running it twice service is no longer active and we have to re-execute the start.sh for starting service again

**Comment by harsh-98** [comment]
@marvin have looked at it?

**Comment by harsh-98** [comment]
@marvin running twice kills the service since in preload.sh the logic for checking whether the service is alive kills it. Therefore after running it twice service is no longer active and we have to re-execute the start.sh for starting service again
