### ISSUE TITLE
Expose an API for handling login via social sites

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#625]
**Actual Behaviour**

Currently, only simple login functionality is present.

**Expected Behaviour**

There should be API exposed for handling login via Google, FB and should send a proper response. This takes care of the need of #617 as well.

**Steps to reproduce it**
NA

**Would you like to work on the issue?**
No

**Comment by zaynkorai** [comment]
I would like to work on this, 
but i think issue be opened in accounts.susi.ai repo.
