### ISSUE TITLE
Add API to delete the user's chat messages

### ISSUE THREAD

**Issue by srv-twry** [fossasia/susi_server#631]
**Actual Behaviour**

The server doesn't support deletion of user's chat messages.

**Expected Behaviour**

There should be support for deleting both an individual message as well as the whole chat history of the user.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

It can be assigned to someone else.

**Extra Information**

Discussed [here](https://github.com/fossasia/susi_android/issues/1081)

**Comment by harsh-98** [comment]
@srv-twry i would like to work on it.

**Comment by srv-twry** [comment]
Sure go ahead.

**Comment by agh372** [comment]
@srv-twry @harsh-98 Can I work on this issue, if it's okay?

**Comment by akshatnitd** [comment]
@agh372 I think you can work on it, since it is long unresolved

**Comment by Akshat-Jain** [comment]
@srv-twry As this issue is long unresolved, can I work on it ?

**Comment by srv-twry** [comment]
@Akshat-Jain Yes, please go ahead since it's been a week since @agh372 claimed it :)

**Comment by Akshat-Jain** [comment]
@srv-twry Okay, I'll start working on it. Thanks :-)

**Comment by agh372** [comment]
@srv-twry Actually I was waiting for the reply 😅 @Akshat-Jain  But it's fine, you carry on. :)

**Comment by akshatnitd** [comment]
@Akshat-Jain Are you working on it?

**Comment by Akshat-Jain** [comment]
@akshatnitd Okay, sure, go ahead :-)

**Comment by fragm3** [comment]
@akshatnitd please add this API
required by: https://github.com/fossasia/chat.susi.ai/issues/1325
