### ISSUE TITLE
Parallellize build

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/susi_server#632]
**Actual Behaviour**

Travis CI build is not parallelized

**Expected Behaviour**

Travis CI bulild should be parallelized

**Why should we do this**
We should do this to reduce build time and make user interaction with the logs easy and to improve accessibility of the logs. It also helps us the pin point which component was broken.

**Suggested Architecture**
Job 1 - build, test, deploy.
(we can't change this as we should deploy only when we pass all tests and compilation is successful)
Job 2 - Codecov

**Steps to reproduce it**

See a Travis Ci build log or .travis.yml file

**Would you like to work on the issue?**

Sure, taking it up as part of GCI.

**Comment by RahulMetre03** [comment]
I would like to work on that issue.Plz guide about I should do

**Comment by abishekvashok** [comment]
@RahulMetre03 sorry for that, I have worked on it and opened a PR.
