### ISSUE TITLE
Can't Save Multiple No.of Custom Themes

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/susi_server#641]
**Actual Behaviour**

A user can create a Custom Theme for  Susi and he can save it. If he wanted to have more themes he can make but he can't save them. 

**Expected Behaviour**

Every Custom Theme made by the Users should be Saved in the Susi Server

**Comment by duttaditya18** [comment]
@naveentherocker Please analyze technical bugs for the GCI Task.

**Comment by hkedia321** [comment]
Not relevant for here. Please look at https://github.com/fossasia/chat.susi.ai to implement such type of feature. Thanks.
