### ISSUE TITLE
Small issues and need to improve on UI

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/susi_server#642]
**Actual Behaviour**

![overlapsusi](https://user-images.githubusercontent.com/33794760/34641956-ac4d256e-f331-11e7-9f9e-cc3175259dcb.png)
- [ ] When I type a big message, message box overlapped on SUSI's messages

![noscroll](https://user-images.githubusercontent.com/33794760/34641973-e8014b4e-f331-11e7-895a-6abc4c8445bc.png)
- [ ] No scroll bar for scroll it. 

![unwant](https://user-images.githubusercontent.com/33794760/34641984-18649e1c-f332-11e7-966e-f5021d98b748.png)
- [ ] Remove unwanted white space in background.

![scrool](https://user-images.githubusercontent.com/33794760/34641992-382322c8-f332-11e7-9435-45e42386d3f3.png)
- [ ] Remove small scroll on message box while there is not any message.

![load](https://user-images.githubusercontent.com/33794760/34642037-03e1d170-f333-11e7-9346-42dde422a919.png)
- [ ] Add any other thing to show it's loading, this is low quality.

**Expected Behaviour**

> When I type a big message, message box overlapped on SUSI's messages.

Adjust margin

> No scroll bar for scroll it. 

Add a scroll bar

> Remove unwanted white space in background.

Remove the space and increase width of message showing area.

> Remove small scroll on message box while there is not any message.

Remove it

> Add any other thing to show it's loading, this is low quality.

Add a thing like turning round, clock....

**Would you like to work on the issue?**

Work anyone.

**Comment by isuruAb** [comment]
@STEdirisuriya  this is not relevant to this project. as i see this should be posted here
https://github.com/fossasia/chat.susi.ai

**Comment by STEdirisuriya** [comment]
@isuruAb Moved this to https://github.com/fossasia/chat.susi.ai/issues/1019

**Comment by zaynkorai** [comment]
this issue should be closed now
