### ISSUE TITLE
Haktoberfest: Identity needs to be protected

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susi_server#645]
**Actual Behaviour**

ID of anonymous users should be hidden

**Expected Behaviour**

History of anonymous users displayed according to IP

This may be a huge infringement to privacy and needs to be fixed.

# Open to work on

**Comment by hkedia321** [comment]
Please provide more detailed explanation about the issue and about the solution. Thanks. 
Closing this for now due to inactivity.
