### ISSUE TITLE
Build fails on Heroku. 

### ISSUE THREAD

**Issue by shashwat1002** [fossasia/susi_server#649]
**Actual Behaviour**

When Heroku tries to deploy the app,  the build fails and Heroku gives an error in the output windows
error:
`FAILURE: Build failed with an exception.
       
       * What went wrong:
       Execution failed for task ':compileJava'.`

**Expected Behaviour**

The app should deploy.

**Steps to reproduce it**

Attempt to deploy app to  Heroku.

**Screenshots of the issue**

(url
![error](https://user-images.githubusercontent.com/33834636/34718021-1a0dd0be-f55b-11e7-8a65-bf4fc95a9d3d.JPG)
)

**Would you like to work on the issue?**

Assign someone else to this issue.

**Comment by starlord1311** [comment]
i would like to work on this. can i @shashwat1002

**Comment by shashwat1002** [comment]
Yeah, sure.

**Comment by amanagr** [comment]
@starlord1311 when is this issue gonna be resolved?

**Comment by sudheesh001** [comment]
Thanks for reporting. Lets track this in #708 and have only one instance of the issue up rather than so many.
