### ISSUE TITLE
Add Continuous Integration and automatically deploy Master branch to Google Cloud

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#65]
Please test app deploy it with Kubernetes on Google Cloud to a test account. Share your deployment with a link in the issue.

You need to sign up for Google cloud. There is a free tier to start (you might need a credit card to sign up). Once you have it running, please make a pull request with the changes.

**Comment by hoangvanthien** [comment]
Why can't I access http://test.asksusi.com ?

**Comment by mariobehling** [comment]
@hoangvanthien You need to first deploy the system to Google and then talk to admin to set up test.asksusi.com.

**Comment by Abhi2424shek** [comment]
Can I work at this @mariobehling

**Comment by Abhi2424shek** [comment]
@mariobehling @jig08 can someone create the google api credentials and put it in the repo as stated in the tutorial as I don't have access to the Google cloud project

**Comment by Abhi2424shek** [comment]
I am still on it but require help from you guys, can you help @mariobehling by doing as stated above? Or give me access to the Google cloud terminal.

**Comment by Abhi2424shek** [comment]
@jig08bi can't proceed with @mariobehling collaborating 😢
