### ISSUE TITLE
Fails Build tests and hence build doesn't complete. 

### ISSUE THREAD

**Issue by shashwat1002** [fossasia/susi_server#650]
**Actual Behaviour**

Several build test fail. 

**Expected Behaviour**

all tests pass, successful build. 

**Steps to reproduce it**

execute `./gradlew build`

**LogCat for the issue**

`api.external.BahnTest > testConnection FAILED
api.external.BahnTest FAILED
api.external.DeliverooTest > testAPI FAILED
api.external.DeliverooTest > testDemo FAILED
api.external.DeliverooTest FAILED
Gradle Test Run :test FAILED
:test FAILED
 FAILURE: Build failed with an exception.
BUILD FAILED`

**Screenshots of the issue**

[
![err1](https://user-images.githubusercontent.com/33834636/34723478-ce9da436-f570-11e7-8b06-d5164b36df0f.JPG)
![err2](https://user-images.githubusercontent.com/33834636/34723490-d4195ab8-f570-11e7-8495-9bb4059b27bb.JPG)
![err3](https://user-images.githubusercontent.com/33834636/34723493-d73791b0-f570-11e7-8170-c3c9bce120ed.JPG)
![err4](https://user-images.githubusercontent.com/33834636/34723498-d91ed5e2-f570-11e7-9c63-ae7187c26e42.JPG)

](url)

**Would you like to work on the issue?**

Please assign tosomeone else.

**Comment by saurabhjn76** [comment]
@shashwat1002 Please close this issue, as this is same as #623.
