### ISSUE TITLE
Build failed on MacOSX

### ISSUE THREAD

**Issue by girijamanojkumarreddy** [fossasia/susi_server#654]
**Actual Behaviour**

3 tests are failing and able to pass 14 tests

**Expected Behaviour**

should pass all the tests without the error

**Steps to reproduce it**

> git submodule update --recursive --remote
> git submodule update --init --recursive
> ./gradlew build

**LogCat for the issue**
```
> Task :test

api.external.BahnTest > testConnection FAILED
    java.lang.NullPointerException at BahnTest.java:16

api.external.DeliverooTest > testAPI FAILED
    java.lang.AssertionError at DeliverooTest.java:30

api.external.DeliverooTest > testDemo FAILED
    java.lang.AssertionError at DeliverooTest.java:38

14 tests completed, 3 failed

FAILURE: Build failed with an exception.
```

**Screenshots of the issue**
![screen shot 2018-01-13 at 1 46 36 pm](https://user-images.githubusercontent.com/29457764/34904376-95f9b4ec-f86a-11e7-8856-1cbe65a6c172.png)

**Comment by AbhishekNadgeri** [comment]
Hey I faced the same issue. The problem lies in the test cases, it seems to be broken. You can use gradle to compile. 
Run gradle assemble. Then run start.sh in the bin folder. 
Hope it solves the issue

**Comment by girijamanojkumarreddy** [comment]
This issue can be resolved using `gradle assemble `command
