### ISSUE TITLE
Error message Wrong !!

### ISSUE THREAD

**Issue by Beta-King** [fossasia/susi_server#655]
**Actual Behaviour**
While signing up if you put down an email which already has an account it says, 'Failed. Try Again'

Please state here what is currently happening.

**Expected Behaviour**
While signing up if you put down an email which already has an account it should say, 'This email already has an account attached to it.' 

Then a dropbox stating what went wrong, for example:
- is this not your email
- did you forget your password
- would you like to try again
etc...

State here what the feature should enable the user to do.

**Steps to reproduce it**
go to https://accounts.susi.ai/signup
try this error for yourself by filling the fields which already have an account...

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Comment by Beta-King** [comment]
![screen shot 2018-01-14 at 10 21 34 am](https://user-images.githubusercontent.com/33036913/34912970-6837c638-f915-11e7-8c78-0463de1785ae.png) --> this is the error !!

**Comment by isuruAb** [comment]
please move this issue to below repo.
https://github.com/fossasia/chat.susi.ai

**Comment by Beta-King** [comment]
ohk :D
