### ISSUE TITLE
Open street map response is not same a expected for a given description.

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_server#658]
**Actual Behaviour**

Please state here what is currently happening.
When a user sarch for `INDIA`, the description comes out for INDIA(country) by susi but the open street map data comes out to be that of a town (see second pic)
![2018-02-12 1](https://user-images.githubusercontent.com/20624380/36082287-25770d7a-0fce-11e8-8b77-b263092c369a.png)
![2018-02-12](https://user-images.githubusercontent.com/20624380/36082289-26e2d81a-0fce-11e8-87ab-d191bad7160b.png)

**Expected Behaviour**
Same description and OSM behaviour

**Steps to reproduce it**
search `Where is India?` 

**Would you like to work on the issue?**
Yes, but a little guidance towards where to look for in the code-base this would be highly appreciated.
(I am new to SUSI)

**Comment by rupav** [comment]
I am thinking of adding a question to user then if he is asking about `town`, `city`, `country` . Then only providing results.

**Comment by ditsme** [comment]
Please guide for looking into the code base as I am new to SUSI. Is there a way to improve the API used?

**Comment by rupav** [comment]
@ditsme you can claim this issue. I suggest you to look into OSM API ...
And as for SUSI (I am new too). Please tag maintainers of this project to get suggestions. Good luck.

**Comment by mabrar21** [comment]
Is this issue claimed? @ditsme

**Comment by ditsme** [comment]
No @mabrar21 , it isn't claimed.You can surely go ahead.

**Comment by mabrar21** [comment]
@ditsme  Thank you. I would certainly like to claim the issue. Currently my approach would be to get the zoom level based to search query, provided by osm nominatim service, which returns the rank (e.g "country" for India), and set the zoom level accordingly while rendering map. This would require modification in ai/susi/geo/NominatimService.java and ai/susi/geo/IntegerGeoPoint along with en_0200_facts_knowledge.json (i havent figured out which java class handles these queries, help would be appreciated).

**Comment by hkedia321** [comment]
Out of scope currently. Thanks.
