### ISSUE TITLE
Different answers to same question

### ISSUE THREAD

**Issue by ditsme** [fossasia/susi_server#659]
Actual Behaviour

Different answer for same question asked to SUSI

Expected Behaviour

It should answer one precise answer, maybe with better framed reply.

Steps to reproduce it

Adding responses to the server file for appropriate duplicate question check and accordingly answer it in a better way

**LogCat for the issue**

NA

Screenshots of the issue

![susi2](https://user-images.githubusercontent.com/32769743/36297339-4a6865e6-1318-11e8-9eeb-ca5db34e571b.PNG)

Would you like to work on the issue?

Yes with due guidance of locating the file for making the changes

**Comment by ditsme** [comment]
@Orbiter @robbyoconnor @leto @rctay @hongquan

**Comment by dynamitechetan** [comment]
Hi. To locate the skill from which the answer came you can send "analyse" command. Susi will tell you the file from which the answer is coming.

**Comment by ditsme** [comment]
Oh. Thankyou for the help! @dynamitechetan

**Comment by robbyoconnor** [comment]
...why was I tagged?

**Comment by hkedia321** [comment]
The responses are decided by the particular skill and it can include responding with different answers.
