### ISSUE TITLE
Add susi-gh-bot as a collaborator

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/susi_server#66]
To push the documentation to the gh-pages on each update the script gh-pagesUpdater.sh uses a bot called @susi-gh-bot, to push the changes back as a commit it would need write access so please add it as a collaborator.

Mentors this one is for you and I hope you have done what I requested you to do in the task in the task I had done earlier? [Hint: Adding an environment variable to the Travis dashboard]

**Comment by Abhi2424shek** [comment]
Any updates guys

**Comment by Abhi2424shek** [comment]
I ask for updates if any.

**Comment by mariobehling** [comment]
Was done days ago.
