### ISSUE TITLE
No reply to "?" message

### ISSUE THREAD

**Issue by ditsme** [fossasia/susi_server#660]
Actual Behaviour

Susi doesn't reply to the message "?"

Expected Behaviour

It should reply by answering with a message like "Sorry I didn't get you." or repeat the previous answer in a better way

Steps to reproduce it
Changing the server file answer by adding a condition to answer "?" message according to previous answer.

LogCat for the issue

NA

Screenshots of the issue

![susi3](https://user-images.githubusercontent.com/32769743/36298200-e6fdf4bc-131c-11e8-98e3-97424954ae12.PNG)

Would you like to work on the issue?

Yes I would like to work on the issue with due  guidance.
@Orbiter

**Comment by dynamitechetan** [comment]
hi @ditsme. Please open these issues at https://github.com/fossasia/susi_skill_data or better create a new susi skill on /http://skills.susi.ai/. Skill CMS is a web app to create and edit susi skills.

**Comment by SanjanaSanikommu** [comment]
When I opened this issue I found this answer.
Here is the screenshot


![question](https://user-images.githubusercontent.com/29593345/40878087-19090dbe-6649-11e8-931b-518673e943a7.png)

**Comment by SanjanaSanikommu** [comment]
Closes #660

**Comment by SanjanaSanikommu** [comment]
resolved #660

**Comment by hkedia321** [comment]
Closing this for now. @ditsme @SanjanaSanikommu Please look at https://github.com/fossasia/susi_skill_data to propose a solution for this. Thanks.
