### ISSUE TITLE
Suggestions in the issue template should be commented out

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#662]
**Actual Behaviour**

Suggestions are simply written in the issue template.

**Expected Behaviour**

Rather, they should be commented out so that contributor doesn't have to delete them manually.

**Would you like to work on the issue?**

Yes

**Comment by punarvasu510** [comment]
I have worked on this. Can I issue a PR?

**Comment by Akshat-Jain** [comment]
Sorry, I've already issued a PR..
