### ISSUE TITLE
Logo should be center aligned

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_server#667]
**Actual Behaviour**
Logo is left aligned.

**Expected Behaviour**
It should be center aligned.

**Screenshots of the issue**
![screenshot from 2018-03-02 14-25-51](https://user-images.githubusercontent.com/30981465/36883704-4011ea00-1e02-11e8-839a-e40bd4f20abd.png)

**Would you like to work on the issue?**
Yes.

**Comment by AnupKumarPanwar** [comment]
I think it will appear weird in the center.

**Comment by aniket-agarwal1999** [comment]
Yes @AnupKumarPanwar you are quite right, the reading is always from left to right, so I guess the current orientation of the heading is quite suited for the same
