### ISSUE TITLE
Unable to build the project on windows

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#676]
**Actual Behaviour**

> ant jar produces error
```
Buildfile: build.xml does not exist!
Build failed
```

**Expected Behaviour**

There should be a build.xml file in the root directory.

**Steps to reproduce it**

> ant jar produces error

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/37159841-d2236ef2-2314-11e8-9685-901c0b958132.png)

**Would you like to work on the issue?**

Yes

**Comment by sudheesh001** [comment]
The project has moved to gradle builds instead of `ant` builds and that's not supported anymore. This was a part of the legacy codebase from loklak. In case traces of it still exist on the codebase they need to be removed.
