### ISSUE TITLE
No support for windows style file path.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#677]
**Actual Behaviour**

The current code supports only Unix style file path format, i.e., path with forward slashes. There is no support for windows style file path, i.e., path with backward slashes.

```
Unix style - /home/user/
Windows style - C:\Windows\
```

**Expected Behaviour**

The code must support both path formats.

**Steps to reproduce it**

For example the following code snippet of SusiSkill.java will never give desired output on Windows.

```
public ID(File origin) throws UnsupportedOperationException {
            this.skillpath = origin.getAbsolutePath();
            // The skillpath must start with the root path of either the susi_skill_data git repository or of susi_server git repository.
            // In both cases the path must start with a "/".
            int i = this.skillpath.indexOf("/susi");
            if (i < 0) throw new UnsupportedOperationException("the file path does not point to a susi skill model repository: " + origin.getAbsolutePath());
            this.skillpath = this.skillpath.substring(i);
            if (this.skillpath.startsWith("/susi/")) this.skillpath = this.skillpath.substring(5);
        }
```

**LogCat for the issue**

```
java.lang.UnsupportedOperationException: the file path does not point to a susi skill model repository: D:\GSOC\susi_server\conf\susi\de_0010_abstraction.json
	at ai.susi.mind.SusiSkill$ID.<init>(SusiSkill.java:76)
	at ai.susi.mind.SusiMind.learn(SusiMind.java:163)
	at ai.susi.mind.SusiMind.observe(SusiMind.java:148)
	at ai.susi.mind.SusiMind.observe(SusiMind.java:122)
	at ai.susi.mind.SusiMind.<init>(SusiMind.java:82)
	at ai.susi.DAO.init(DAO.java:159)
	at ai.susi.SusiServer.main(SusiServer.java:209)
.
.
.
```

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/10573038/37165599-0d76421e-2323-11e8-875c-41af35429dee.png)

**Would you like to work on the issue?**

Yes

**Comment by sudheesh001** [comment]
Agreed this works with #678 but there could've been a more elegant way. Maybe we could clean it up in the efforts later through this summer. Thank you @AnupKumarPanwar for the patch.
