### ISSUE TITLE
Missing statements in some catch blocks

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#679]
**Actual Behaviour**

There are some catch blocks with missing statements.

**Expected Behaviour**

Server should log the exceptions for their identification and fixation.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by sudheesh001** [comment]
I believe this is addressed by #680 This can be safely closed. Please reopen if needed.
