### ISSUE TITLE
Problem while pushing the app on Heroku

### ISSUE THREAD

**Issue by meets2tushar** [fossasia/susi_server#68]
Following this [readme](https://github.com/fossasia/susi_server/blob/development/docs/installation_heroku.md) , while pushing on Heroku  `git push heroku master` ;  it gives the error as:
error: src refspec master does not match any.
error: failed to push some refs to 'https://git.heroku.com/sleepy-ridge-23846.git'

Then while using `git push heroku HEAD:master` ;  it gets pushed to Heroku.
[Got_it_from_here](http://stackoverflow.com/questions/4181861/src-refspec-master-does-not-match-any-when-pushing-commits-in-git)

[Image](https://s27.postimg.org/j8mvesooz/Screenshot_from_2017_01_11_03_52_08.png)

**Comment by Abhi2424shek** [comment]
@meets2tushar did you properly add the remote.

**Comment by meets2tushar** [comment]
@Abhi2424shek I checked using git remote -v 
It gives the Heroku URL

**Comment by Abhi2424shek** [comment]
@meets2tushar can you try again pls (from 0 to 1)

**Comment by meets2tushar** [comment]
@Abhi2424shek 
I tried it two times not only with susi_server  but also with loklak_server and this is common in both.

**Comment by Abhi2424shek** [comment]
give me the output of: `git remote -v` pls

**Comment by meets2tushar** [comment]
same with open-event-webapp too
here is the output
`heroku	https://git.heroku.com/stormy-dusk-25339.git (fetch)
 heroku	https://git.heroku.com/stormy-dusk-25339.git (push)
 origin	https://github.com/meets2tushar/open-event-webapp.git (fetch)
 origin	https://github.com/meets2tushar/open-event-webapp.git (push)`

**Comment by meets2tushar** [comment]
But in open-event-webapp it mention as
'git push heroku development:master'
`git push heroku master`

**Comment by Abhi2424shek** [comment]
@meets2tushar which branch are you in?

**Comment by meets2tushar** [comment]
@Abhi2424shek  I am in master branch ; it gets warning in different branch.

**Comment by Abhi2424shek** [comment]
@meets2tushar yep I know that just wanted to confirm, let me try running it locally

**Comment by Orbiter** [comment]
is there any update here?

**Comment by Abhi2424shek** [comment]
Can you test it, pinky please @Orbiter

**Comment by meets2tushar** [comment]
@Abhi2424shek @Orbiter  Let me see it again

**Comment by mayank408** [comment]
@meets2tarun @Orbiter I am too facing the facing the same problem.

**Comment by meets2tarun** [comment]
Let me to two reproduce same again

**Comment by Abhi2424shek** [comment]
But `git push heroku HEAD:master` and git push heroku master` should be equal if you got a correct `.git/config` with the master pointing to `refs/heads/master`, what's your `.git/config` containing @mayank408 @meets2tarun

**Comment by mariobehling** [comment]
It seems to working for autodeployment. Therefore closing it.
