### ISSUE TITLE
Placeholder text changes with screen width on index page.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#681]
**Actual Behaviour**

The placeholder text of the input filed on home page changes with screen width. On wider screen it shows 
"Chat with Susi", while on smaller width it shows "Search Twitter & the loklak network".

**Expected Behaviour**

Same text should be displayed on all screen sizes.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/37241107-d25c4892-2479-11e8-8a61-0233c1994282.png)

![image](https://user-images.githubusercontent.com/10573038/37241114-ea5fe1f6-2479-11e8-8bbd-078c221a9abe.png)

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
@AnupKumarPanwar please close. :smile:
