### ISSUE TITLE
500 Error on fetching skills related to communication group

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_server#686]
**Actual Behaviour**

Calling this api gives 500 error
https://api.susi.ai/cms/getSkillList.json?group=Communication

Response
```
HTTP ERROR 500

Problem accessing /cms/getSkillList.json. Reason:

    Server Error

Caused by:

java.lang.NullPointerException

```

**Expected Behaviour**

Rest all group works fine. Was it deleted or something. Not sure. Need to figure out. 

**Would you like to work on the issue?**
yes

**Comment by sudheesh001** [comment]
I believe this was a temporary downtime issue. It seems to be working now.
