### ISSUE TITLE
Write tests for DateParser.java

### ISSUE THREAD

**Issue by mayank8318** [fossasia/susi_server#688]
**Actual Behaviour**

There are no tests for DateParser

**Expected Behaviour**

There should be tests.

**Would you like to work on the issue?**

Yes

**Comment by dynamitechetan** [comment]
sure! 👍

**Comment by yashLadha** [comment]
Can i send a PR for this. I have prepared the PR @mayank8318

**Comment by sudheesh001** [comment]
@yashLadha Is there an open pull request which addresses this? Yes you could work on it if you're interested.
