### ISSUE TITLE
Implement Swagger and generate static version in gh-pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#69]
[Swagger](http://swagger.io/) is a great way to document APIs. 
* [ ] Please add Swagger to the system at `/api/v1/`
* [ ] On pull requests also generate a static version in the pages branch at http://dev.asksusi.com/api/v1/

**Comment by Abhi2424shek** [comment]
The loklak repository is autogenerated

**Comment by dynamitechetan** [comment]
@mariobehling  working on this issue.
