### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by mayankpi** [fossasia/susi_server#693]
**Actual Behaviour**

There is a typo in the kubernetes setup documentation.

**Expected Behaviour**

N/a

**Steps to reproduce it**

N/A
**LogCat for the issue**

N/A
**Screenshots of the issue**

N/A
**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
YES

**Comment by prateekiiest** [comment]
What is the typo?
