### ISSUE TITLE
Implement documentation site using travis and sphinx

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#70]
It seems to work out well with the site generated for the loklak documentation. 

Please have a look at the script (https://github.com/loklak/loklak_server/blob/development/.utility/push-docs-to-gh-pages.sh) and docs site and duplicate the way it is done here.

**Comment by Abhi2424shek** [comment]
@mariobehling the @susi-gh-bit would work from the next merged pr

**Comment by Abhi2424shek** [comment]
@mariobehling can we close this as the @susi-gh-bot would work on? Is this still needed?

**Comment by mariobehling** [comment]
@Abhi2424shek http://dev.asksusi.com does not work as expected. Right now is only displays the Readme.md page. It does not generate a full site with search features and subpages from the docs branch. This issue is open and we need help solving it.

**Comment by aviaryan** [comment]
@mariobehling There seems to be a PR available for it at #95 but it has conflicts. I have pinged the OP (@pri22296), waiting for their reply.

**Comment by pri22296** [comment]
@mariobehling can we close this? PR #99 which solves this has has been merged successfully.
