### ISSUE TITLE
API to fetch skills created by a user is crashing

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#700]
**Actual Behaviour**

The server crashes on query for the list for the skills created by a particular user.

**Expected Behaviour**

The server should send proper data to susi_skill_cms for showing a list of skills created by a particular user.

**Steps to reproduce it**

1. Go to https://skills.susi.ai/
2. Click on any skill and open its details
3. Click on the author name to load the list of skills created by him

**LogCat for the issue**

NA

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/39593095-782e363c-4f26-11e8-9de0-15db9fd933f0.png)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
@AnupKumarPanwar @saurabhjn76 This issue can be closed, as it is already merged.
