### ISSUE TITLE
getSkillList servlet needs modifications to show JSON data of all skills

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#705]
**Actual Behaviour**

Currently, the getSkillList servlet is showing JSON data for only skills which fall under the group "Knowledge". 

**Expected Behaviour**

It should show JSON data of all skills.

**Steps to reproduce it**
Go to https://api.susi.ai/cms/getSkillList.json. We can see that JSON data is being shown for only the skills under the group "Knowledge".

**Would you like to work on the issue?**

Yes

**Comment by dynamitechetan** [comment]
Hi @Akshat-Jain.
https://api.susi.ai/cms/getSkillList.json this endpoint accept one get parameter, "group". If no "group" is given in the get parameter then by default it takes the group as "Knowledge".
To try open `https://api.susi.ai/cms/getSkillList.json?group=Social` it will show you the skills under "Social" Category.

**Comment by Akshat-Jain** [comment]
@dynamitechetan So is this how it is intended to be ?? Because I thought that https://api.susi.ai/cms/getSkillList.json this endpoint should show all skills under all categories, so I was trying to merge all the different JSONs and return them, but was not really successful in doing that..

**Comment by Akshat-Jain** [comment]
@AnupKumarPanwar I tried running a for loop on an array which contained all the groups as strings. The main problem I was getting was that I wasn't able to append the JSONs one after the other as in the end, return new ServiceResponse(json); is being used. Anyways, can you help me in doing it your way, if possible ??

**Comment by AnupKumarPanwar** [comment]
Hmm yes I guess you can go with the for loop way also but for that you need to have an array of directories  prior to running the loop. Recursion may be a better way.

**Comment by Akshat-Jain** [comment]
@AnupKumarPanwar What I mean to say is that instead of the way we are putting stuff in JSON (whether it be a looping approach or a recursive), we need to do something of the return statement....What do you think ?
