### ISSUE TITLE
mic button is not working... 

### ISSUE THREAD

**Issue by Nikmachine** [fossasia/susi_server#707]
**Actual Behaviour**

In our fork, the mic button is not working. 
http://nefertiti-chat.surge.sh/

**Expected Behaviour**

To use the voice control to communicate with the bot.

**Steps to reproduce it**

http://nefertiti-chat.surge.sh/

**LogCat for the issue**

there are none in the browser

**Screenshots of the issue**

![bildschirmfoto 2018-05-07 um 15 23 59](https://user-images.githubusercontent.com/33403721/39704223-f5536ca4-520a-11e8-84fa-cce1427bba7f.png)

**Would you like to work on the issue?**

I worked on solving this and can't fix it.

**Comment by Orbiter** [comment]
I believe this bug belongs to the web client https://github.com/fossasia/chat.susi.ai
Do you use a fork? Which repository?
I would like to ask if you merged recent updates to your repository.

**Comment by Nikmachine** [comment]
we checked out origin/master earlier today and pushed it to our server, so we aren't using a diverging fork

**Comment by Nikmachine** [comment]
this is our repos: https://github.com/vidbina/chat.susi.ai
