### ISSUE TITLE
Adding support of emoji feature in susi server

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_server#72]
Currently susi server doesn't have the support to emoji characters. We can add feature as most of the have this feature.

**Comment by jig08** [comment]
Closing this, duplicate of Issue https://github.com/fossasia/susi_server/issues/3

**Comment by saketkumar95** [comment]
@jig08 i was asked [here](https://github.com/fossasia/susi_android/issues/462) to open this issue. :)

**Comment by jig08** [comment]
Pls follow up on the previous one then :)
