### ISSUE TITLE
Modify the skill rating system to accept 5 star user rating system and move the previous rating system to userFeedbackService

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_server#724]
**Actual Behaviour**
We need to modify the current rating system to accept 5 star ratings from users so it is possible for users to view top rated skills, the present rating system will be moved to feedback service which users will be able to use to provide feedback.

**Expected Behaviour**
Offer endpoints to provide the above-stated functionality.

**Would you like to work on the issue?**
Yes, along with the analytics team.

**Comment by Akshat-Jain** [comment]
@anshumanv I'd like to work together with you on this one. Cool ?

**Comment by anshumanv** [comment]
Yes, let's do that. :smile:

**Comment by AnupKumarPanwar** [comment]
I would also like to work on this at the server side.
