### ISSUE TITLE
Create a CMS endpoint for returning general metrics for users

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#725]
**Actual Behaviour**
No such endpoint available.

**Expected Behaviour**
There should be an endpoint that returns the general metrics like Top Skills, Latest Skills and Top Rated Skills.

**Would you like to work on the issue?**
Yes, I would like to work on it.

**Comment by Akshat-Jain** [comment]
@akshatnitd I think this issue can be closed now as we already have an endpoint implemented for the same. Hence, closing this. Thanks :-)
