### ISSUE TITLE
Table and Map type of responses stopped coming

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_server#726]
**Actual Behaviour**

`table` and `map` type of responses are no longer coming from the SUSI server.

**Expected Behaviour**

`table` and `map` type of responses should come for queries like `universities in India`, `where is India?`

**Steps to reproduce it**

For table type of response ask susi - `universities in India`.
For map type of response ask susi - `where is India?`.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/17807257/40230628-cf9c0ee0-5ab5-11e8-9d77-1431200e2441.png)

**Would you like to work on the issue?**

No, I am working on the client side.

**Comment by prateekiiest** [comment]
yes, this has been an issue.

`Tell me where am I` only replies as `Here you are`

Is that a problem of the location being turned off?

**Comment by hkedia321** [comment]
The `table` type of response is now correctly coming. But `map` type of response is still not coming. Earlier, for queries like `https://api.susi.ai/susi/chat.json?q=where%20is%20india?`, an action type of `map` used to come which is now not coming.
```
"actions": [{
      "type": "answer",
      "expression": "India (IAST: Bhārat), also called the Republic of India (IAST: Bhārat Gaṇarājya), is a country in South Asia."
    }]
```

**Comment by hkedia321** [comment]
Working now. :+1: 
https://github.com/fossasia/susi_server/pull/913
