### ISSUE TITLE
Create an endpoint to store the device's (smart speaker) information in the User's accounting model

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#727]
As discussed in the meeting, the list of connected devices are supposed to be displayed on the web client. Hence, there needs to be an API implemented which when called from the Android/iOS devices on SignUp using Wifi Direct, will store the information of the connected device (Smart speaker). The information will have to be stored in the accounting model of the particular User.

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
You must first formulate in detail which data structure is required to add a new device. Find out how a connection of a new device works. There must be some identification credentials and that must be stored.

The pull request you made is lacking the required data structures and it does not actually address the problem. Please see my comment in https://github.com/fossasia/susi_server/pull/728#issuecomment-390920880

When you have noted how a "connect a device" works, you can define the required data. Then have a look which APIs are already there and if the APIs are not sufficient, use the existing principles (here Accounting) to store the connection information.

**Comment by Akshat-Jain** [comment]
@arundhati24 @batbrain7 @imjog @stealthanthrax Please give feedback. 

@Orbiter The plan is to make an API call immediately after the initial SignUp process during WiFi Direct connection process to store the device's information.

**Comment by stealthanthrax** [comment]
@Orbiter , I have tried to implement something like this http://solderandflux.com/2017/02/07/wifi-direct-style-wifi-setup-on-a-raspberry-pi/ to establish a wifi direct connection.

**Comment by Akshat-Jain** [comment]
@arundhati24 @batbrain7 @imjog Will this approach enable you to add devices via Android/iOS app ?
