### ISSUE TITLE
Enhance the Console Rule Learning App for Susi Server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#73]
A basic console learning app is implemented in the server already (see [here](http://susi-server.herokuapp.com/apps/consolerule/)). The goal of this project is to make it easy now to create new console rules a) to connect new APIs to Susi and b) to add the rules itself.

The rules are the method to attach external knowledge to Susi. To check and store new console rules, there is now the rule learning backend api, the details are described here: https://github.com/fossasia/susi_server/blob/development/src/org/loklak/api/learning/ConsoleLearning.java#L45-L163

To store a new console rule, the user has to enter at least the following entries:
- the external json API address
- an example input for that API
- a name for the new console rule

Furthermore, the user must submit a jsonpath which points into an result array within the JSON from the console API. The new back-end process supports the user by finding that jsonpath automatically.

What we need:
- an input window for those three options
- a 'verify' button which calls the backend. That will return a lot of information together with the jsonpath which the user can edit. 
- a 'store' button which can be used when the user is satisfied with the back-end verification.

**Comment by saurabhjn76** [comment]
I would like to work on this issue.
