### ISSUE TITLE
Server error in retrieving skill data

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_server#731]
**Actual Behaviour**

http://localhost:4000/cms/getSkillMetadata.json?model=general&group=Knowledge&language=en&skill=aboutsusi

Try to get any skill data, server throws a 500

**Expected Behaviour**
It should return data.

**Steps to reproduce it**

Try visiting http://localhost:4000/cms/getSkillMetadata.json?model=general&group=Knowledge&language=en&skill=aboutsusi

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/21009455/40279481-eab4bcb6-5c60-11e8-8160-a48d58eb2ac0.png)

**Would you like to work on the issue?**
Trying to figure out what;s causing this.

**Comment by anshumanv** [comment]
@Akshat-Jain @AnupKumarPanwar please see if you can reproduce this.

**Comment by AnupKumarPanwar** [comment]
Yeah sure. I can fix it.

**Comment by AnupKumarPanwar** [comment]
It's working in my case as well as it is working on the currently deployed susi server. 
Try `git pull upstream development`

**Comment by AnupKumarPanwar** [comment]
Cloned the fossasia repo or your form?

**Comment by anshumanv** [comment]
Any help @AnupKumarPanwar @Akshat-Jain?

**Comment by Akshat-Jain** [comment]
@anshumanv It's working for me. Are you facing issues with other endpoints too ?

**Comment by anshumanv** [comment]
Got it working, thanks @Akshat-Jain @AnupKumarPanwar @akshatnitd
