### ISSUE TITLE
User should be able to add private skills after logging in for SUSI.AI conversational web plugin

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#738]
**Actual Behaviour**

Currently, a user can add skills to SUSI after logging in. All these skills are public.

**Expected Behaviour**

We want user to be able to add some private skills that will be only applicable to his/her SUSI AI web plugin bot along with all the public skills. User should be able to add/modify/delete these skills after logging in.

**Would you like to work on the issue?**

Yes. I and @hkedia321 are working on this together.

**Comment by DNS-404** [comment]
This issue is for the following project - https://github.com/fossasia/labs.fossasia.org/issues/288

**Comment by DNS-404** [comment]
We've created a basic version of how SUSI AI web plugin bot would look like. Check it out [here](https://rawgit.com/DNS-404/susi_widget_sample/master/index.html). Link to the repo is [here](https://github.com/DNS-404/susi_widget_sample).

**Comment by DNS-404** [comment]
@Orbiter, Can you please guide us on how to proceed with this issue? 😅 
I and @hkedia321 have already created the frontend part for SUSI AI web plugin. https://github.com/fossasia/susi_skill_cms/pull/478
Please guide us on adding private skills to susi web plugin. Any help would be really appreciated.
Thanks!

**Comment by DNS-404** [comment]
This is how we're going to implement it -

Step 1 -
We're creating an option for users to add private skills after logging in. Now, these private skills will be identified by the email ID of the logged in user. So when the same user is logged in who created the skill, these skills would be applicable otherwise not.
Step 2 -
Once creation of private skills is successful via using email as a parameter, we're going to make it more secure because if someone can use your private skills just by adding your email ID then it defeats the purpose of making it "private".

For implementing step 1, two things need to be done -
- In susi_skill_data, two new parameters needs to be added (email ID and skill type) which will identify if the skill is private or public and what is the email ID of user who created the skill. 
- In susi_server, if the user is logged in then while fetching skills, it should look for the private skills in which the email ID matches. Otherwise not.

**Comment by Orbiter** [comment]
For private skills, https://github.com/fossasia/susi_server/issues/815 is not sufficient (it's explained in my comment there). What we need for real private skills is, that we do not publish them in our git repository https://github.com/fossasia/susi_skill_data

Instead, all private skills must be published in another git repository which will not be published.

This private skill repository must have a different structure than the existing public. While the public repository has the following structure:
```
└── models
    ├── README_models.md
    ├── custom
    │   ├── Alarms\ and\ Clocks
    │   ├── Astrology
    │   ├── Business\ an\ Finance
    │   ├── Calculators
    │   ├── Calendars\ and\ Reminders
    │   ├── Communication
    │   ├── Connected\ Car
    │   ├── Cooking\ and\ Recipe
    │   ├── Currency\ Guides\ and\ Converters
    │   ├── Dating
    │   ├── Delivery\ and\ Takeout
    │   ├── Device\ Tracking
    │   ├── Education\ and\ Reference
    │   ├── Event\ Finders
    │   ├── Exercise\ and\ Workout
    │   ├── Fashion\ and\ Style
    │   ├── Flight\ Finders
    │   ├── Friends\ and\ Family
    │   ├── Game\ Info\ and\ Accessory
    │   ├── Games
    │   ├── Health\ and\ Fitness
    │   ├── Hotel\ Finders
    │   ├── Knowledge\ and\ Trivia
    │   ├── Movie\ Info\ and\ Reviews
    │   ├── Movie\ Knowledge\ and\ Trivia
    │   ├── Movie\ Showtimes
    │   ├── Music\ Info\ Reviews\ and\ Recognition\ Service
    │   ├── Music\ and\ Audio\ Accessories
    │   ├── Music\ and\ Audio\ Knowledge\ and\ Trivia
    │   ├── Navigation\ and\ Trip\ Planner
    │   ├── News
    │   ├── Novelty
    │   ├── Organizers\ and\ Assistants
    │   ├── Pets\ and\ Animal
    │   ├── Podcasts
    │   ├── Public\ Transportation
    │   ├── Religion\ and\ Spirituality
    │   ├── Restaurant\ Booking\ Info\ and\ Review
    │   ├── Schools
    │   ├── Score\ Keeping
    │   ├── Self\ Improvement
    │   ├── Shopping
    │   ├── Smart\ Home
    │   ├── Social\ Networking
    │   ├── Sports\ Games
    │   ├── Sports\ News
    │   ├── Streaming\ Service
    │   ├── TV\ Guides
    │   ├── Taxi\ and\ Ridesharing
    │   ├── To\ Do\ Lists\ and\ Notes
    │   ├── Translators
    │   ├── Unit\ Converters
    │   ├── Weather
    │   ├── Wine\ and\ Beverage
    │   └── ZIP\ Code\ Lookup
    ├── general
    │   ├── Business\ and\ Finance
    │   ├── Communication
    │   ├── Connected\ Car
    │   ├── Food\ and\ Drink
    │   ├── Games,\ Trivia\ and\ Accessories
    │   ├── Health\ and\ Fitness
    │   ├── Knowledge
    │   ├── Lifestyle
    │   ├── Movies\ and\ TV
    │   ├── Music\ and\ Audio
    │   ├── News
    │   ├── Novelty\ and\ Humour
    │   ├── Problem\ Solving
    │   ├── Productivity
    │   ├── README_skill_categories.md
    │   ├── Shopping
    │   ├── Social
    │   ├── Sports
    │   ├── Travel\ and\ Transportation
    │   ├── Utilities
    │   └── Weather
    ├── persona
    │   ├── Fictional\ Characters
    │   ├── Machines\ and\ Automation
    │   ├── Real\ Humans
    │   └── Societies
    └── tutorial
        ├── README_experts.md
        └── levels
```
.. the new repository must be in the form
```
└── users
    ├── user-id 1
    │   ├── custom skill group for user 1
    │  │   ├── en
    ├── user-id 2
    │   ├── custom skill group for user 2
    │  │   ├── fr

... and so on.
```
That means that the whole directory structure for the private skills would be very similar to the public skills, the path construction is the same, but it also means that every skill is only associated to a single user an that only that user is allowed to do editing there.

The advantage of this process is, that we don't need much changes. We just need another access path to the private skill repository.

**Comment by DNS-404** [comment]
This is solved now.
