### ISSUE TITLE
Create a contributor-guide page

### ISSUE THREAD

**Issue by AnaghHegde** [fossasia/susi_server#74]
Currently `README.md` page contains lot of information( Continuing from #6  ) - also contains some information related to contributors guide but its not solid. So its better to divide the `README.md` into : 

1.contributor-guide page and give a link from readme to contributor-guide page
     
   - This contains all the contents under the sub head `How to compile using Gradle?` and 
      `How do I install Susi: Download, Build, Run`.  
   
2.documentation page give a link from readme to documentation page 
   
   - This will have all the contents under the sub head `Where can I find documentation?` 

Remaining information will be there in `README.md` and it also contains links to both of of these pages.

Reasons to do so : 

* Looks good. 

* It will be easy to maintain.

* Removes unnecessary( not required in readme but in some other doc) contents from `readme.md`.

**Comment by AnaghHegde** [comment]
@Abhi2424shek What's your opinion on this?. Shall i submit a PR?.

**Comment by daminisatya** [comment]
@AnaghHegde Looks great. Please create a PR, and then we can review!

**Comment by Abhi2424shek** [comment]
@AnaghHegde LGTM go on pls, we await your PR
