### ISSUE TITLE
Store timestamp and user id along with the rating

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_server#744]
**Actual Behaviour**

Currently the 5 star rating system store the rating only and no extra information like who and when has rated the skill is stored.

**Expected Behaviour**

Timestamp and user id should be stored along with the rating which will be helpful if a user wants to update his ratings later.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by Akshat-Jain** [comment]
@AnupKumarPanwar I think this issue can be closed. Please check once and close this issue. Thanks :-)
