### ISSUE TITLE
Unable to fetch ratings data from the getSkillRating endpoint

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_server#746]
**Actual Behaviour**
Sample endpoint to get skill rating for a skill - 
```
/cms/getSkillRating.json?model=general&group=Knowledge&language=en&skill=aboutsusi&callback=pc&_=1525446551181
```
isn't returning the updated skill ratings.

**Expected Behaviour**
It should return the ratings distribution in terms of stars.

**Steps to reproduce it**
Visit - https://api.susi.ai/cms/getSkillRating.json?model=general&group=Knowledge&language=en&skill=aboutsusi&callback=pc&_=1525446551181

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/40501943-0b6a1f16-5fa7-11e8-9fa1-803220d7603f.png)

**Would you like to work on the issue?**
@AnupKumarPanwar is already working on this.

**Comment by akshatnitd** [comment]
@anshumanv  This can be closed, already fixed!

**Comment by anshumanv** [comment]
Works well now!

Thanks for mentioning @akshatnitd :smile:
