### ISSUE TITLE
Implementation of contact bot in server (for SUSI AI Web Plugin)

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#748]
The contact bot should be identified by the bot creator's email ID(for now, can be made more secure later on) and it should ask the users following questions -
- What is your name?
- What is your Email?
- What is your message?

Then this info should be stored in the database and will be displayed on the "Chatbot plugin" page of skills cms after bot creator logs in.

**Would you like to work on the issue?**

Yes.

**Comment by DNS-404** [comment]
@mariobehling @Orbiter, I've found a possible solution for this. Please tell me if this can be implemented or not.
There is a dedicated API to store user's personal information. Its endpoint is:
```
https://api.susi.ai/aaa/storePersonalInfo.json
```
This can be used for both storing the details and getting the details of user. Minimal user role is `USER` and I've made each contact bot unique by adding `access_token` of bot creator in it so they're not `ANONYMOUS` anymore. 
We can store the name, email id and message of users who use the contact bot in this API as key-value pairs for the account of bot creator. So that when bot creator logs in, he/she can then send a request to this API and receive name, email id and message of users who used the contact bot in bot builder page. Or I can create a separate page for contact bot?
What do you think about this?

**Comment by DNS-404** [comment]
@mariobehling @Orbiter Here's our previous conversation regarding this issue. I'm providing it in order to keep all the ideas together. 😄 

<img width="627" alt="screen shot 2018-05-31 at 1 01 23 pm" src="https://user-images.githubusercontent.com/31174685/40768451-fcdf6bf0-64d2-11e8-836f-f3f4ab68cdd4.png">
<img width="612" alt="screen shot 2018-05-31 at 1 01 31 pm" src="https://user-images.githubusercontent.com/31174685/40768457-ff71375e-64d2-11e8-9a54-4da97e0fcb81.png">
<img width="647" alt="screen shot 2018-05-31 at 1 01 42 pm" src="https://user-images.githubusercontent.com/31174685/40768464-02e92414-64d3-11e8-8d96-507596bad8c9.png">
<img width="613" alt="screen shot 2018-05-31 at 1 01 57 pm" src="https://user-images.githubusercontent.com/31174685/40768473-07b146b6-64d3-11e8-8c6b-d1c42daa8501.png">

**Comment by Orbiter** [comment]
my citation did not belong to this issue; it was a comment about the data which shall be stored as a result of the conversation. This is unrelated here.

**Comment by DNS-404** [comment]
Okay. Sorry 😓

**Comment by Orbiter** [comment]
I'm not sure about this. What is the actual use case?

**Comment by Akshat-Jain** [comment]
@Orbiter The information of all Clients (the answers to the 3 questions that the Contact Bot asks each Client) that use Contact Bot of a particular User need to be stored.
@hkedia321 @DNS-404 Is that correct ? Please add more to it as per your requirements. Thanks :-)

**Comment by hkedia321** [comment]
> @Orbiter The information of all Clients (the answers to the 3 questions that the Contact Bot asks each Client) that use Contact Bot of a particular User need to be stored.

yes, this is the requirement for implementing the pre-coded contact bot. The answers to these three question:
- tell me your name
- give me your Email ID
- What is your message?

needs to be stored in the server for each client. The data is being identified by the email address of the person who created the bot. 
A demo of the contact bot can be found at https://dns-404.github.io/.

**Comment by DNS-404** [comment]
Yes. Correct, we have to store the answers of three questions that clients enter. I don't know if this is the best way to do it but I think it can work. 😅

**Comment by Akshat-Jain** [comment]
@Orbiter Can you please follow up on this, if any changes are to be done? Otherwise I can start working on https://github.com/fossasia/susi_server/issues/795. Thanks :-)

**Comment by Akshat-Jain** [comment]
@sudheesh001 Please read the conversation above. Thanks :-)

**Comment by Orbiter** [comment]
I don't see how this can be embedded into a skill. What is the concept to do so?

**Comment by DNS-404** [comment]
@Orbiter, We're not embedding it into a skill. The concept on which I built contact bot is different. Contact bot is not at all related to the SUSI AI web bot.
Contact bot is "pre-coded" so bot creator can't add more skills or anything to it. It's a ready made bot that just takes answers of three questions from the users(people using the contact bot on website of bot creator) and then displays the answers to bot creator.
Check it out here - https://dns-404.github.io/
Currently the answers are displayed in console.

**Comment by sudheesh001** [comment]
So this is a request to be contacted service in case someone lands on a page where the bot is powered by Susi? Something like intercom? https://www.intercom.com/ but just taking in someone's name, email and message and sending an owner an email/notification about a potential customer?

**Comment by DNS-404** [comment]
Yes exactly

**Comment by Akshat-Jain** [comment]
@Orbiter @sudheesh001 Can you please follow up on this, if any changes are to be done? If not, can it be merged please? This is a blocker to #795. Thanks :-)

**Comment by Orbiter** [comment]
I don't like the whole attempt to do this in the way it's done here. You are basically creating a mini-mini-mini Susi for one single purpose. And then for this out-of-susi-in-webclient process there is a storage facility which stored data which is created in that out-of-architecture hack.

We should do this in a much different way. Our conversation rules should be able to add a 'store' marker to each intent so that the answer which the user gives for the question that susi asks is stored in a generic storage space. That is complex, I know. But we still should not add a hack like this, it will kill the project structure because the next hack will be made ontop of it soon.
