### ISSUE TITLE
To add an 'usb_play' action

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#749]
**Actual Behaviour**

No 'usb_play' action

**Expected Behaviour**

To add an 'usb_play' action.
This action will trigger the media discovery daemon in the susi_linux client and will play the music from the USB device

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
This is the wrong way. the current play actions are able to play from the usb device by giving a path.
The question is regarding how to discover the USB content and write custom skills to play them.
We don't need a special usb_play action

**Comment by Orbiter** [comment]
This functionality is now covered with issue https://github.com/fossasia/susi_linux/issues/126
