### ISSUE TITLE
Change storing of 5-star rating mapping to email

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#751]
**Actual Behaviour**

Currently. the rating to each skill is stored according to access_token which is an incorrect approach, as access_toekn keeps on changing

**Expected Behaviour**
Change storing of 5-star rating mapped to email

**Would you like to work on the issue?**
Yes

**Comment by AnupKumarPanwar** [comment]
@akshatnitd  What is the primary key to of the user besides email?
