### ISSUE TITLE
move to gradle build process

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#76]
Today susi builds are based on libraries we ship within the git repository.
We should use gradle builds exclusive in the future.

We already have a gradle build which uses these libraries
```
repositories {
  flatDir {
    dirs 'lib'
  }
}
```
We should move to a build using maven libraries like 
```
repositories {
     mavenCentral()
}
```

also, we should use gradle run as start method.
All cloud deployment options must be migrated to use the gradle build process as well.

If this works, the libraries in lib should be removed.

**Comment by Orbiter** [comment]
please see a first attempt in https://github.com/fossasia/susi_server/pull/42 which provides already a gradle build. Don't take all that code because it was a 'change everything' job which is not wanted here. Just concentrate on removing ant and replacing it with gradle.

The result should be, that a 'gradle run' is possible.

**Comment by AnaghHegde** [comment]
@Orbiter can i work on this ?

**Comment by Abhi2424shek** [comment]
@AnaghHegde sure, make a try
