### ISSUE TITLE
User Settings are not being saved in the server

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_server#763]
**Actual Behaviour**

User settings(such as color, theme, etc) are not being persistently saved in the backend. After changing a setting value, it shows the correct settings for about 1 hr (sometimes even less), but after that, resets everything to its default values.
APIs used: 
- for changing settings: `https://api.susi.ai/aaa/changeUserSettings.json?&access_token=mytoken&key1=theme&value1=themecustom&count=1`
- for getting settings: `https://api.susi.ai/aaa/listUserSettings.json?access_token=mytoken`

**Expected Behaviour**

The settings saved should be persistent.

**Steps to reproduce it**

- First change any setting using the above API. (`changeUserSettings.json`)
- See the settings using the `listUserSettings.json` API after about 1 hr. The changed settings will not reflect.

**Screenshots of the issue**

Just after changing the settings (`theme` field set to `themecustom`)
![image](https://user-images.githubusercontent.com/17807257/40731630-19ab4b7a-644f-11e8-9118-14b13d12609c.png)
After 50 mins, it was itself set to the default value:(`theme` field showing `light`)
![image](https://user-images.githubusercontent.com/17807257/40731640-22794f86-644f-11e8-9051-c1132c4956f6.png)

**Would you like to work on the issue?**

No, I am working on the client side. I am working on this issue([add option for custom design](https://github.com/fossasia/susi_skill_cms/issues/511)) which requires to store few new keys and values in this API. As I tried to store new key in this API, I discovered that it is getting removed after about 1hr.

**Comment by Orbiter** [comment]
fixed with https://github.com/fossasia/susi_server/commit/6d6be528da7f3aa3859c99e272a64dd5a8e01400
