### ISSUE TITLE
Improve the Icon for hamburger menu

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_server#764]
**Actual Behaviour**

Current only a box

**Expected Behaviour**

To add a better icon

**Screenshots of the issue**

<img width="996" alt="screen shot 2018-05-31 at 1 30 02 am" src="https://user-images.githubusercontent.com/29942790/40744516-669d4e38-6472-11e8-805d-bcd30e9149b0.png">

**Would you like to work on the issue?**

Yes

**Comment by prateekiiest** [comment]
I guess that's the issue since the page takes time loading time.
After a few seconds, you will see the dropdown menu
