### ISSUE TITLE
Make an API to reset user settings

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#765]
**Actual Behaviour**
No such API available

**Expected Behaviour**
An API should be present to reset user settings. Basically, need to delete the settings in the accounting model.
**Steps to reproduce it**
NA

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
This issue causes problems: it deletes a setting `"anonymous": false` which causes that the user is allowed to make further changes in the skills, like setting of the five-star rating.

I believe it is a very bad idea to delete all settings of a user. Can we omit this API completely?

**Comment by akshatnitd** [comment]
@Orbiter Yes we can omit this, this API is not being used currently.

**Comment by Orbiter** [comment]
Please work on this, it causes that all new users are blocked from API functions.

**Comment by akshatnitd** [comment]
@Orbiter Here is the PR that removes this API implemenation.
