### ISSUE TITLE
Add details regarding workflow 

### ISSUE THREAD

**Issue by AnaghHegde** [fossasia/susi_server#77]
Continuing from #6 , workflow of the project has to be added to the new file. It includes 

* Coding style (Standard Practice)

* Branch Policy

* Squashing of commits

**Comment by AnaghHegde** [comment]
@daminisatya @Abhi2424shek Any inputs ?.

**Comment by jig08** [comment]
@AnaghHegde If these arent present already, pls go ahead.

**Comment by AnaghHegde** [comment]
@daminisatya What all should i have to include in the coding policy or standards ?.

**Comment by Abhi2424shek** [comment]
Commenting on issues and informing the approach is one of the best fossasia policies. Take a look at the contributing.md files in the various repositories. @AnaghHegde

**Comment by AnaghHegde** [comment]
@Abhi2424shek Right now i am having exmas so i can't spend much time. Once they get over(4-5days) i will start working on this. Sorry for the delay.

**Comment by mariobehling** [comment]
Sorry, as we don't have a huge project, we should keep basic info in the Readme.md. Please compare to other FOSSASIA projects e.g. Open Event Orga Server.

**Comment by AnaghHegde** [comment]
@mariobehling ok. Thanks for pointing it out.
