### ISSUE TITLE
Make fork me on GitHub logo look better

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/susi_server#772]
**Actual Behaviour**

Currently it looks like this

![screenshot 104](https://user-images.githubusercontent.com/16035442/40784325-fcd95d0c-6502-11e8-9c33-237c77e3f311.png)

**Expected Behaviour**

New logo
![forkme_right_green_007200](https://user-images.githubusercontent.com/16035442/40784339-05b75e6a-6503-11e8-9c2d-b8bcfb2b9c0b.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Not required.
