### ISSUE TITLE
Frequent issues fetching skill data

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_server#791]
**Actual Behaviour**

Currently, there are very frequent instances of skills not being fetched properly. We see placeholder data instead. I faced this quite often in the Android client and recently in the Skills CMS.

**Expected Behaviour**

The skills should be fetched properly. These frequent errors loading skill data need to be checked.

**Screenshots of the issue on Skills CMS**

<img width="1440" alt="screen shot 2018-06-04 at 2 16 07 am" src="https://user-images.githubusercontent.com/30979369/40899686-ce4c74e8-67e5-11e8-9bf3-053fe854ac55.png">

**Would you like to work on the issue?**

No, anybody is free to take it up.

**Comment by akshatnitd** [comment]
@arundhati24 Thanks for pointing this out. Looking into it :+1:

**Comment by arundhati24** [comment]
Thanks @akshatnitd :)

**Comment by akshatnitd** [comment]
On investigation of this issue further, it was found that, `getSkillList` API returns null value for all attributes for a skill sometimes. Also, we see that, once with get to the detailed page of a skill, `getSkillMetadata` API call is made, after which the `getSkillList` API starts to work fine. That is the reason, we see sometimes that home page loads up correctly when we go back from skill details page to home page. It is due to some inconsistency, which is a bit hard to find. Anyone, if finds a solution to this can take this up and solve :v:

**Comment by prateekiiest** [comment]
Faced this too. Also when you open any specific skill , the name and other details dont appear sometimes, in the same format as shown above

**Comment by Orbiter** [comment]
I found the following entry in the log:

```
2018-08-13 07:32:21.175 WARN org.eclipse.jetty.servlet.ServletHandler  - /cms/getSkillMetadata.json
org.json.JSONException: JSONObject["null"] not found.
        at org.json.JSONObject.get(JSONObject.java:581)
        at org.json.JSONObject.getJSONObject(JSONObject.java:793)
        at ai.susi.json.JsonTray.getJSONObject(JsonTray.java:134)
        at ai.susi.server.api.cms.GetSkillMetadataService.serviceImpl(GetSkillMetadataService.java:82)
        at ai.susi.server.AbstractAPIHandler.process(AbstractAPIHandler.java:138)
        at ai.susi.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:78)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
```

The reason is that in GetSkillMetadataService line 82 the code
```
JSONObject userObject = chatbot.getJSONObject(userid);
```
is called with NULL.

That means that the `userid` attribute was not passed correctly at that time.
Can you please check if that is given correctly?

**Comment by akshatnitd** [comment]
@Orbiter I think this is not the reason behind the issue, since this bug has been happening since long time, even before chat bots were implemented.

**Comment by akshatnitd** [comment]
The issue is not being reproduced now.
