### ISSUE TITLE
Add option to remove user skill ratings

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#822]
Actual Behaviour
Not present

Expected Behaviour
Add option to remove user skill ratings, this will complete all the APIs related to ratings.

- [x] Post Ratings
- [x]  Get Ratings
- [ ]  Delete Ratings

Would you like to work on the issue?
Yes

**Comment by AnupKumarPanwar** [comment]
Duplicate issue to https://github.com/fossasia/susi_server/issues/821
