### ISSUE TITLE
Add support to give image as a response

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_server#827]
**Feature**

Currently the image responses are not present, add support for the image responses from the server that can be displayed in the mobile clients. This could be implemented as a separate action like for  eg : "Show images of giraffe",  or an additional field for image in the existing actions

**Would you like to work on the issue?**

no, @AnupKumarPanwar or @akshatnitd may take this up.

**Comment by hkedia321** [comment]
@batbrain7 @akshatnitd @AnupKumarPanwar I think image response do come from for queries like 
https://api.susi.ai/susi/chat.json?q=image%20of%20cat
```
{
      "language": "en",
      "type": "answer",
      "expression": "https://pixabay.com/get/ea31b30b2ffd003ed1584d05fb1d4790e076e7d610ac104497f8c871afedb2ba_640.jpg"
    }
```
We need to detect this kind of link on the client side and display the images accordingly.
Is the issue still needed or can we close this issue? Thanks.

**Comment by batbrain7** [comment]
@hkedia321 thanks for pointing this out

**Comment by Akshat-Jain** [comment]
@batbrain7 @hkedia321 As this issue has been solved already, hence I'm closing this. Thanks :-)
