### ISSUE TITLE
Generate user id for each user 

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_server#837]
**Actual Behaviour**

No user id present for each user. Only user email is used to identify the user.

**Expected Behaviour**

Unique user id should be generated and assigned to each user when they sign up. This user id would be used in places where email id can't used for privacy reasons (like storing images, for bot token, etc). Also email can change, but user id would be permanent.

**Would you like to work on the issue?**

Yes, along with @akshatnitd and @AnupKumarPanwar.

**Comment by mariobehling** [comment]
@hkedia321 Please research how Facebook does this. What kind of - internal - user-ID do they have? I am not talking about the user name or email login. Please check on their user-ID approach. We can follow the same.

**Comment by hkedia321** [comment]
@mariobehling Facebook uses [Presto](https://www.facebook.com/notes/facebook-engineering/presto-interacting-with-petabytes-of-data-at-facebook/10151786197628920/?s=keen-io) which is based on SQL. 
For generating user id in java, I found this [UUID](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html) class. Some relevant findings regarding using UUID are: [create a GUID in Java](https://stackoverflow.com/questions/2982748/create-a-guid-in-java) and [wikipedia - UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions). So UUID seems to be a standard way to generate unique user id and I think we can use this. Please let me know if we need to change this. Thanks.

**Comment by hkedia321** [comment]
Already Solved in c212cb70d17ab2e881558fd034412683f2de27fb
