### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#838]
Recently a number of APIs were implemented. However the API documentation has little info and no documentation was added. Please add relevant information here: https://github.com/fossasia/susi_server/blob/development/docs/api/api.md

Alternatively propose a way to automatically generate API docs.

Previously Swagger was used and we generated Swagger docs in the github pages branch. Please consider this as an option as well.

**Comment by AnupKumarPanwar** [comment]
I think Swagger is a good alternative as the current docs look quite unreadable and complex.

**Comment by yashasvi128** [comment]
I would like to work on this.

**Comment by AnupKumarPanwar** [comment]
@yashasvi128 please go ahead.

**Comment by ms10398** [comment]
I would try to add swagger to most of the endpoints

Will make a PR about it soon
