### ISSUE TITLE
Issues with lexicographical filter on /cms/getSkillList.json endpoint

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_server#840]
**Actual Behaviour**

The Skills are not being sorted in a lexicographical order in `/cms/getSkillList.json` output if we apply the filter `filter_name=ascending&filter_type=lexicographical` or `filter_name=descending&filter_type=lexicographical` as URL parameters. This is also causing the A-Z and Z-A sorting of the Skill CMS to not function as expected.

**Expected Behaviour**

The Skills should get sorted in a lexicographical ascending/descending order.

**Steps to reproduce it**

Visit this link: https://api.susi.ai/cms/getSkillList.json?group=All&applyFilter=true&filter_name=ascending&filter_type=lexicographical. This should be giving the Skills in a lexicographical (ascending) order in the `filteredData` object. But the Skills are not in the expected order.

**Would you like to work on the issue?**

Yes

**Comment by AnupKumarPanwar** [comment]
replace compareTo() with compareToIgnoreCase() in the lexicographical sorting part.
