### ISSUE TITLE
Add action for volume control

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#850]
**Expected Behaviour**

The user shall be able to set the output colume with phrases like
"set volume to 80%"
"reduce volume"

We need 
* a new action type
* skills to operate on the action type

**Would you like to work on the issue?**

**Comment by Orbiter** [comment]
I will work on the foundation

**Comment by mariobehling** [comment]
It is done according to @stealthanthrax Closing it therefore.
