### ISSUE TITLE
Send skill identifier along with other skill data in getSkillList.json API

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_server#852]
**Actual Behaviour**

Currently, there is no way by which we can identify the skill name, which is the key identifier for any skill, when parsing filteredData array.

**Expected Behaviour**

The skill_identifier should be sent along with other values like author name, skill image, ratings etc. as this is needed in the client for various other tasks like sending the skill ratings to the server using fiveStarRateSkill.json API.
 
**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
This is a good idea but we should here make the concept better by using not only the skill name as metadata but also the skill path. It would be better to identify the skill by it's path but currently we are identifying it by the name. Nevertheless the name is not a good identifier. Therefore we should not name the "name" a "identifier".

Here we should start to make the concept better by using two identification attributes (which we should both not call identifier:
`skill_name`
and
`skill_path`.

Where the `skill_path` would be the same path as we get from the method SusiSkill.ID.getPath().
