### ISSUE TITLE
API for support for both skill star rating and feedback 

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#854]
**Actual Behaviour**

getSkillFeedback only sends feedback

**Expected Behaviour**

This would require API to support review rating + feedback support

Required by https://github.com/fossasia/susi_skill_cms/issues/759

**Would you like to work on the issue?**

No

**Comment by ashgarg143** [comment]
Is anyone working on this? 
If not, can someone please assign this to me.
