### ISSUE TITLE
The user should receive a confirmation email after the password is reset

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_server#865]
**Actual Behaviour**

Currently, only the password recovery mail is sent to the user after selecting the reset password option and no confirmation mail is sent, once the password is reset.

**Expected Behaviour**

A confirmation mail should be sent to the user once the password is reset.

**Steps to reproduce it**

On any client select the reset password option and reset your password, no confirmation mail is sent.

**Would you like to work on the issue?**

Yes, but anyone can take this up

**Comment by Akshat-Jain** [comment]
@batbrain7 I'll work on this :-)

**Comment by batbrain7** [comment]
Sure, @Akshat-Jain
