### ISSUE TITLE
SUSI.AI svg file is not displaying

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#883]
**Actual Behaviour**

SUSI.AI svg file is present but not displaying on [api.susi.ai](api.susi.ai). 
<img width="100" alt="screen shot 2018-06-25 at 1 53 04 am" src="https://user-images.githubusercontent.com/31174685/41823253-a4c16ac6-781a-11e8-9290-673794b5f1b2.png">
This is maybe because server is serving it with an incorrect `content-type`. It's described in detail [here](https://css-tricks.com/snippets/htaccess/serve-svg-correct-content-type/).

**Expected Behaviour**

It should work. All the images are in png format. So I'll use the png image in place of svg image.
I was able to see the image when I tested the website on my local machine. Problem arrises when it's run on a web server.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Seems to be working now
