### ISSUE TITLE
Deployment buttons not working on all platforms

### ISSUE THREAD

**Issue by AnaghHegde** [fossasia/susi_server#92]
Continuing from [loklak/loklak_server #1001](https://github.com/loklak/loklak_server/issues/1001).

**Comment by AnaghHegde** [comment]
I think the cause for thisgoes something like this.

According to docker documentation  

`You must be logged into the docker account before trying to deploy. Otherwise you will get the error 404 not found`. For more information check [this.](https://docs.docker.com/docker-cloud/apps/deploy-to-cloud-btn/) This solves docker problem.

From other platforms like dev.loklak.org its not possible to deploy both heroku and docker.

- For herkou check [this](https://devcenter.heroku.com/articles/heroku-button) it says the `app.json` file  has to be in root directory. But in dev.loklak.org there is no such file. 

- The same applies to docker except it needs stack file.

**Comment by Abhi2424shek** [comment]
@AnaghHegde heroku should be deployed not from the gh-pages branch, so that solved the problem :) for heroku, we really need heroku.

**Comment by AnaghHegde** [comment]
@Abhi2424shek  Can you be more specific?. I didn't get your point.

**Comment by Abhi2424shek** [comment]
Heroku is not deployed from the gh-pages branch so the branch need not have the app.json file.
