### ISSUE TITLE
Email Verification Success Response in JSON

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#94]
Wouldn't it be better to show user a simple page that his email is verified instead of JSON response.

![Screenshot](https://cloud.githubusercontent.com/assets/16765805/20642288/62d0dc86-b431-11e6-89e3-11c9f6cc52ca.png)

**Comment by aksh98** [comment]
I'm working on this.

**Comment by betterclever** [comment]
@dynamitechetan Isn't this response meant for Susi Apps? We utilize this on Android App. This is on purpose AFAIK.

**Comment by Orbiter** [comment]
true, this is on purpose. Please create a Susi app for that
