### ISSUE TITLE
Change "From" of SUSI Email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#941]
The SUSI reset email shows: 

"Susi Email Daemon DO NOT REPLY"

Please change from name simply to

"SUSI.AI"

![screenshot from 2018-07-07 12-04-29](https://user-images.githubusercontent.com/1583873/42409656-f0659688-81dd-11e8-935c-ec740cd2778c.png)

**Comment by akshatnitd** [comment]
Working on it

**Comment by akshatnitd** [comment]
Regarding this issue, we need to make changes on the configuration file(`conf/config.properties`) on the server.
The change to be made on the file is - 
 `smtp.sender.displayname=SUSI.AI`

**Comment by Orbiter** [comment]
ok, changed the config!

**Comment by akshatnitd** [comment]
@Orbiter Thanks. Checked it, its working :fireworks:

**Comment by akshatnitd** [comment]
Issue solved, hence closing.
