### ISSUE TITLE
Rewrite EmailHandler

### ISSUE THREAD

**Issue by aksh98** [fossasia/susi_server#97]
[Simple JavaMail](http://www.simplejavamail.org/#/features) is a better and more lightweight alternative to the JavaMail API used currently in EmailHandler. It has validation checks and DKIM built in, and is simpler to use, so rewriting the current EmailHandler code with this API will add more features.

@Orbiter @mariobehling should I work on this? We could also possibly close #96 in favour of this, since DKIM auth is already incorporated here.

**Comment by Orbiter** [comment]
can you do the Simple JavaMail integration in such a way that the existing `smtp.` properties can be used, so a re-configuration is not necessary?

**Comment by aksh98** [comment]
Sure ! I ll work on this :)

**Comment by mariobehling** [comment]
@aksh98 Are you still up for this task?
