### ISSUE TITLE
Make a skill review status false when it has been reported for 5 times

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#973]
**Actual Behaviour**
* No such functionality present.

**Expected Behaviour**
* Make a skill review status false when it has been reported for 5 times.

**Would you like to work on the issue?**
Yes, after https://github.com/fossasia/susi_server/pull/972 gets merged.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd I think we should make a separate API for that and give the rights to ADMINS. My idea is to show the reported skills on the Admin dashboard with the number of reports and the status of the skill. The admin should be able to turn them down or reinstate them with a toggle button.
