### ISSUE TITLE
Implement feature of saving draft of chatbot

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#994]
**Actual Behaviour**

Currently, if you close your browser tab in between the process of creating your bot, no draft is saved and all the process is lost.

**Expected Behaviour**

A draft of the bot should be saved at that time. This draft bot will be visible under "My bots" and will allow user to continue creating chatbot from where he left it.
Issue in Skills CMS: https://github.com/fossasia/susi_skill_cms/issues/1142

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
implemented in https://github.com/fossasia/susi_server/commit/3de86216c78b2d73c82dcef1a12381d113d2e5b2

The draft must be an json object, not a plain text. That gives the opportunity to store more metadata from the client with it.

Example usages are:

Store a draft without giving an id for it; it will generate one and return it;
http://localhost:4000/cms/storeDraft.json?object={"test":"123"}

Same with a given ID:
http://localhost:4000/cms/storeDraft.json?object={"tset":"123"}&id=aabbcc

Read a specific draft with a given ID
http://localhost:4000/cms/readDraft.json?id=aabbcc

If it is not know which draft are stored, the id can be omitted and the server will respond with all existing ids.
http://localhost:4000/cms/readDraft.json

Delete a draft with a given ID:
http://localhost:4000/cms/deleteDraft.json?id=aabbcc
